### DISCUSSION TITLE
Helm use a different filer store backend

### DISCUSSION THREAD

**Discussion by summerisc** [seaweedfs/seaweedfs#1853] [Q&A] [answered]
Current helm uses mySQL as the default filer store backend and it can be configured within the values yaml like:

```
 extraEnvironmentVars:
    WEED_MYSQL_ENABLED: "true"
    WEED_MYSQL_HOSTNAME: "sw-database"
    WEED_MYSQL_PORT: "3306"
    WEED_MYSQL_DATABASE: "sw_database"
    WEED_MYSQL_CONNECTION_MAX_IDLE: "5"
    WEED_MYSQL_CONNECTION_MAX_OPEN: "75"
```
What if we want to try something else for the backend. For example, let's say we want to use Redis cause it's the fastest one, how to configure in the filer statefulSet to make it work? I think values yaml might not support this change right?

Also, currently, there is no database(storage service) chart in the helm charts, is there any plan to add this later? We can deploy our own database using a separate chart, but just want to ask here if this will be a plan.
