### DISCUSSION TITLE
Data gone after changing docker-compose script

### DISCUSSION THREAD

**Discussion by andrewleech** [seaweedfs/seaweedfs#2300] [Q&A]
New user here, hoping to migrate my old JBOD `mergerfs` server system to using seaweedfs, it looks like the perfect solution for my personal nas/server needs!

I'm running into a problem with using docker-compose to manage seaweedfs however, if I change anything in the docker-compose.yml such that it re-creates the containers, all my data is gone.

I've got a bunch of drives that are mounted with fstab as such
```
LABEL=g3t /mnt/merge_g3t auto defaults,nofail,noatime,nodiratime 0 1
LABEL=toshdata /mnt/merge_tosh auto defaults,nofail,noatime,nodiratime 0 1
LABEL=ironData /mnt/merge_iron auto defaults,nofail,noatime,nodiratime 0 1
LABEL=iron8mfs /mnt/merge_iron8 xfs defaults,nofail,noatime,nodiratime 0 1
```

I've set up a docker-compose.yml script to use a subfolder on each of these drives as such:
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    restart: unless-stopped
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"

  vol_g3t:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
      - 8080:8080
      - 18080:18080
      - 9315:9315
    command: 'volume -dir=/filerldb2 -mserver="master:9333" -port=8080  -metricsPort=9315'
    volumes:
      - /mnt/merge_g3t/weed:/filerldb2
    depends_on:
      - master

  vol_tosh:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
      - 8081:8081
      - 18081:18081
      - 9316:9316
    command: 'volume -dir=/filerldb2 -mserver="master:9333" -port=8081  -metricsPort=9316'
    volumes:
      - /mnt/merge_tosh/weed:/filerldb2
    depends_on:
      - master

  vol_iron:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
      - 8082:8082
      - 18082:18082
      - 9317:9317
    command: 'volume -dir=/filerldb2 -mserver="master:9333" -port=8082  -metricsPort=9317'
    volumes:
      - /mnt/merge_iron/weed:/filerldb2
    depends_on:
      - master

  vol_iron8:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
      - 8083:8083
      - 18083:18083
      - 9318:9318
    command: 'volume -dir=/filerldb2 -mserver="master:9333" -port=8083  -metricsPort=9318'
    volumes:
      - /mnt/merge_iron8/weed:/filerldb2
    depends_on:
      - master

  filer:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333"  -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - vol_g3t
      - vol_tosh
      - vol_iron
      - vol_iron8

  cronjob:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    command: 'cronjob'
    environment:
      # Run re-replication every 2 minutes
      CRON_SCHEDULE: '*/2 * * * * *' # Default: '*/5 * * * * *'
      WEED_MASTER: master:9333 # Default: localhost:9333
    depends_on:
      - master
      - filer

  s3:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
      - 8333:8333
      - 9327:9327
    command: 's3 -filer="filer:8888" -metricsPort=9327'
    depends_on:
      - master
      - filer

  webdav:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
      - 7333:7333
    command: 'webdav -filer="filer:8888"'
    depends_on:
      - master
      - filer

  prometheus:
    image: prom/prometheus:v2.21.0
    restart: always
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - s3
      - webdav
```
and I've added the final line to fstab
```
fuse /weed fuse.weed filer=localhost:8888,filer.path=/,uid=1000 1 3
```

This seems to work well on the face of it, I can start it with `docker-compose up -d` then fuse mount it with `sudo mount /weed` and it's all up and running
```
sudo mount | grep weed
localhost:8888:/ on /weed type fuse.seaweedfs (rw,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
```
I can write files to it just fine. 
`sudo umount /weed; sudo mount /weed` all good, files still there.
`sudo umount /weed; docker-compose down; docker-compose up -d; sudo mount /weed` all good, files still there.
```
sudo umount /weed; docker-compose down; 
touch docker-compose.yml; 
docker-compose up -d; sudo mount /weed
``` 
**files gone :-(**

I'm assuming there's metadata stored in one/some of the containers that's crucial to maintain? Is this documented somewhere I've missed, that I could/should volume and backup somehow? Or is my volume bind configuration wrong? Or fuse mount wrong?

Thanks!
