### DISCUSSION TITLE
Why redis2 filer is slower than leveldb2?

### DISCUSSION THREAD

**Discussion by meotimdihia** [seaweedfs/seaweedfs#2639] [General]
Why is the Redis2 filer slower than leveldb2?
This is my setup: 

```shell
sudo docker run --name weed_filer --restart always -d \
--net=host \
-v /home/seaweedfs/s3config.json:/s3config.json \
-v /home/seaweedfs/filer.toml:/etc/seaweedfs/filer.toml \
-v /home/seaweedfs/data/filer:/data/ \
-v /home/seaweedfs/security.toml:/etc/seaweedfs/security.toml \
-v /home/seaweedfs/certs/weed:/etc/seaweedfs/certs \
chrislusf/seaweedfs filer -s3 -s3.config=/s3config.json \
-ip=(curl -s https://ipinfo.io/ip) \
-master=localhost:9333


# redis
sudo docker run -d --restart always \
-p 6379:6379 \
-v /home/seaweedfs/redis.conf:/etc/redis/redis.conf \
-v /home/seaweedfs/data/redis:/data \
--name redis redis redis-server /etc/redis/redis.conf
```

```toml
filer.toml
[redis2]
enabled = true
address = "localhost:6379"
password = "DG3E5N4brhvYL4FixxxE6oDQw40HmCp3xxxaDDzvbX09EQjV1"
database = 0
```
Please give me a tip about this 😀
