### DISCUSSION TITLE
Filesystem lost after reboot, how to make it persistent?

### DISCUSSION THREAD

**Discussion by kralicky** [seaweedfs/seaweedfs#2977] [Q&A]
After restarting the filer, it seems to have erased its filesystem information, although it looks like the files are still there in the volume. I assume this is a configuration issue on my end; how do I ensure the filesystem is persisted? And is there any way to get the orphan files back from the volume? I'm using the seaweedfs helm chart.
```
> volume.fsck
volume:4        entries:1       orphan:1        100.00% 1857B
volume:5        entries:10      orphan:10       100.00% 1587749B
volume:6        entries:10      orphan:10       100.00% 17604B
volume:7        entries:7       orphan:7        100.00% 8767B
volume:3        entries:9       orphan:9        100.00% 11539B
volume:2        entries:10      orphan:10       100.00% 1718171B
volume:1        entries:5       orphan:5        100.00% 978616B

Total           entries:52      orphan:52       100.00% 4324303B
This could be normal if multiple filers or no filers are used.
> fs.tree
0 directories, 0 files
```

**Comment by chrislusf** [comment]
seems the filer store is not configured properly

**Reply by kralicky** [reply]
What values in the helm chart are needed for filer persistence?

**Reply by chrislusf** [reply]
this section:
```
  # extraEnvVars is a list of extra enviroment variables to set with the stateful set.
  extraEnvironmentVars:
    WEED_MYSQL_ENABLED: "true"
    WEED_MYSQL_HOSTNAME: "mysql-db-host"
    WEED_MYSQL_PORT: "3306"
    WEED_MYSQL_DATABASE: "sw_database"
    WEED_MYSQL_CONNECTION_MAX_IDLE: "5"
    WEED_MYSQL_CONNECTION_MAX_OPEN: "75"
    # "refresh" connection every 10 minutes, eliminating mysql closing "old" connections
    WEED_MYSQL_CONNECTION_MAX_LIFETIME_SECONDS: "600"
    # enable usage of memsql as filer backend
    WEED_MYSQL_INTERPOLATEPARAMS: "true"
    # if you want to use leveldb2, then should enable "enablePVC". or you may lose your data.
    WEED_LEVELDB2_ENABLED: "false"
    # with http DELETE, by default the filer would check whether a folder is empty.
    # recursive_delete will delete all sub folders and files, similar to "rm -Rf"
    WEED_FILER_OPTIONS_RECURSIVE_DELETE: "false"
    # directories under this folder will be automatically creating a separate bucket
    WEED_FILER_BUCKETS_FOLDER: "/buckets"

```
