### DISCUSSION TITLE
Filer web interface not showing files

### DISCUSSION THREAD

**Discussion by jhill2727** [seaweedfs/seaweedfs#3133] [General]
Very simple docker setup using 3.06. One server running all 3 containers. master is accepting and volume is writing files, but the filer is not showing the files for playback. It was working until we bumped from 2.56 to 3.06. Docker compose file below. Any thoughts?
```
services:
  master:
    image: chrislusf/seaweedfs:3.06 # use a remote image
    volumes:
      - ./mdir:/data
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
    restart: always
  volume:
    image: chrislusf/seaweedfs:3.06 # use a remote image
    volumes:
      - ./data:/data
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="master:9333" -port=8080 -max=500 -metricsPort=9325 -minFreeSpacePercent=1'
    depends_on:
      - master
    restart: always
  filer:
    image: chrislusf/seaweedfs:3.06 # use a remote image
    volumes:
      - ./fdir:/data/filerldb2
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333"  -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
    restart: always
```
