### DISCUSSION TITLE
how to setup grafana?

### DISCUSSION THREAD

**Discussion by eleaner** [seaweedfs/seaweedfs#3470] [Q&A]
Hi, 

I am new to the topic of seaweed.
I set up the cluster using docker-compose, but the supplied example only provides Prometheus and not grafana.
I see some grafana json files. but I don't know how to use them

could someone please help?

**Comment by noinhotnn** [comment]
Follow info: https://github.com/seaweedfs/seaweedfs/wiki/System-Metrics
Config prometheus:
You must config prometheus get data from pushgateway
prometheus.yaml like:
```
scrape_configs:
  - job_name: "prometheus"
   
    static_configs:
      - targets: ["localhost:9091"]
```
