### DISCUSSION TITLE
SignatureDoesNotMatch on S3 Presigned URLs

### DISCUSSION THREAD

**Discussion by Fabricio20** [seaweedfs/seaweedfs#3976] [Q&A]
Hello,

I've been trying to set up seaweedfs with s3 gateway and I've stumbled upon a weird issue when using presigned urls. It seems that for some reason, I'm unable to PUT files, as the requests fail with `SignatureDoesNotMatch`, however the same presigned URL works fine over GET.

Response body:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
    <Resource>/test/upload.png</Resource>
    <RequestId>1668429294792225800</RequestId>
    <Key>upload.png</Key>
    <BucketName>test</BucketName>
</Error>
```

I'm running three separate services on the same machine for testing, this issue does not seem to happen when running everything as all-in-one (via `weed server -s3`):

Master:
```
[Unit]
Description=SeaweedFS Master
After=network.target

[Service]
Type=simple
User=root
Group=root

ExecStart=/usr/bin/weed master -ip=127.0.0.1 -mdir=/mnt/backups/master
SyslogIdentifier=seaweedfs-master

[Install]
WantedBy=multi-user.target
```

Volume (weed-large binary due to 30TB of disk size):
```
[Unit]
Description=SeaweedFS Volume
After=network.target

[Service]
Type=simple
User=root
Group=root

ExecStart=/usr/bin/weed volume -ip=127.0.0.1 -max=0 -mserver="127.0.0.1:9333" -dir=/mnt/backups/volume
SyslogIdentifier=seaweedfs-volume

[Install]
WantedBy=multi-user.target
```

Filer + S3:
```
[Unit]
Description=SeaweedFS S3
After=network.target

[Service]
Type=simple
User=root
Group=root

ExecStart=/usr/bin/weed filer -ip=<public ip> -master="127.0.0.1:9333" -s3 -s3.domainName=s3.domain.tld -s3.config=/etc/seaweedfs/s3.json
SyslogIdentifier=seaweedfs-s3

[Install]
WantedBy=multi-user.target
```

I've omitted the public ip address and domain of the test server but they are valid, I've also tested against the direct ip address + port of the s3 gateway (8333) so it doesn't seem to be related to any proxies (like nginx/cloudflare).

**Comment by Fabricio20** [comment]
I've managed to reproduce the issue in a docker-compose environment.

```yaml
version: '3'

services:
  master:
    image: chrislusf/seaweedfs:latest
    network_mode: host
    command: "master -ip=127.0.0.1 -mdir=/master"
    volumes:
      - ./seaweed/master:/master
  volume:
    image: chrislusf/seaweedfs:latest
    network_mode: host
    command: "volume -ip=127.0.0.1 -max=0 -mserver=127.0.0.1:9333 -dir=/volume"
    volumes:
      - ./seaweed/volume:/volume
  filer:
    image: chrislusf/seaweedfs:latest
    network_mode: host
    command: "filer -ip=127.0.0.1 -master=127.0.0.1:9333 -s3 -s3.config=/s3.json"
    volumes:
      - ./seaweed/s3.json:/s3.json
```

For the S3 config file:
```json
{
  "identities": [
    {
      "name": "admin",
      "credentials": [
        {
          "accessKey": "admin",
          "secretKey": "be09cee4795d4695809ac3d8386c826b"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "Write",
        "List",
        "Tagging"
      ]
    }
  ]
}
```

Set up authentication and signature version:
```
$ aws configure
AWS Access Key ID [None]: admin
AWS Secret Access Key [None]: be09cee4795d4695809ac3d8386c826b
Default region name [None]: us-east-1
Default output format [None]:

# Then also
$ aws configure set default.s3.signature_version s3v4
```

Then presign a url:
```
aws --endpoint-url http://127.0.0.1:8333 s3 mb s3://test
aws --endpoint-url http://127.0.0.1:8333 s3 presign s3://test/upload.png
```
