### DISCUSSION TITLE
请问为什么设置 TTL 后 每个volume 最多只能写入1GB的空间

### DISCUSSION THREAD

**Discussion by dc-vin** [seaweedfs/seaweedfs#4625] [Q&A]
当我设置 TTL 上传文件时，默认30GB空间并不能写满，会被拆开很多个 volume ，并且大小被限制在1GB左右，下面是我的dockerfile。是不是因为 TTL 的精确度是秒级别的？
配置
```
services:
  master:
    image: chrislusf/seaweedfs:${FS_VERSION}
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /seaweedfs/master:/data
      - /seaweedfs/master-log:/mlog
    ports:
      - 9333:9333
      - 19333:19333
    command: 'master -ip.bind=0.0.0.0 -port=9333 logdir=/mlog -mdir=/data -volumeSizeLimitMB=30000'
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai


  volume_1:
    image: chrislusf/seaweedfs:${FS_VERSION}
    ports:
      - 8080:8080
      - 18080:18080
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /seaweedfs/volume/data:/data
      - /seaweedfs/volume/idx:/idx
    command: 'volume -mserver="master:9333" -ip=${volume_1_ip} -publicUrl=${volume_1_ip}:8080 -ip.bind=0.0.0.0 -port=8080 -index=leveldb3 -dir=/data -dir.idx=/idx -max=0 -idleTimeout=60 -readBufferSizeMB=64'
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    depends_on:
      - master
```
![image](https://github.com/seaweedfs/seaweedfs/assets/29142176/a3f9e5ed-8bb1-46b8-b30b-ef3b6eaba015)
