### DISCUSSION TITLE
Lost data on recreating containers with -p

### DISCUSSION THREAD

**Discussion by therealparham** [seaweedfs/seaweedfs#4800] [Q&A]
I have a docker-compose file with the following setup,
```
version: '3.1'
services:
  weed-master:
    container_name: test-wm
    image: chrislusf/seaweedfs
    command: "master -ip=weed-master -volumeSizeLimitMB=10000"
  weed-volume:
    container_name: test-wv
    image: chrislusf/seaweedfs
    volumes: 
      - seaweedvolume:/data
    command: 'volume -mserver="weed-master:9333" -port=8080'
    depends_on:
      - weed-master
  weed-filer:
    container_name: test-wf
    image: chrislusf/seaweedfs
    command: 'filer -master="weed-master:9333"'
    tty: true
    stdin_open: true
    depends_on:
      - weed-master
      - weed-volume
  api:
    container_name: test-api
    image: test/api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - weed-filer

volumes:
  seaweedvolume:

networks:
  default:
    external:
      name: nginx-proxy
```

There were some conflicts with another project, in a way that when this one got run the other went down.
So I changed the command to `docker-compose -p test up -d`,
I got some errors that the containers already existed, so I stopped and removed them.
But now, the seaweed docker volumes are completely new and I can't figure out a way to restore the previous ones.
