### DISCUSSION TITLE
Exactly 7 volumes being assigned per collection/layout?

### DISCUSSION THREAD

**Discussion by reberhardt7** [seaweedfs/seaweedfs#5944] [Q&A]
I am running seaweedfs 3.72 deployed via the helm chart, and I am reading and writing files via the filer (I don't use the master or volume servers directly). I've run into a problem where one of my collections ran out of space, despite having many free volumes available.

I get this error in the filer:
```
failing to assign a file id: rpc error: code = Unknown desc = failed to find writable volumes for collection:my-volume-name replication:000 ttl:3d error: No writable volumes in volume layout
```

And when I query the master `http://localhost:9333/dir/status?pretty=y`, I see that there are no more `writables` for this layout:
```
{
  "Topology": {
    "Max": 33,
    "Free": 12,
    "DataCenters": [
      {
        "Id": "us-west1",
        "Racks": [
          {
            "Id": "persistent-disk",
            "DataNodes": [
              {
                "Url": "seaweedfs-volume-0.seaweedfs-volume.storage:8080",
                "PublicUrl": "seaweedfs-volume-0.seaweedfs-volume.storage:8080",
                "Volumes": 21,
                "EcShards": 0,
                "Max": 33,
                "VolumeIds": " 29-35 43-56"
              }
            ]
          }
        ]
      }
    ],
    "Layouts": [
      {
        "replication": "000",
        "ttl": "3d",
        "writables": [],
        "collection": "my-volume-name",
        "diskType": "hdd"
      },
...
```

There are 7 volumes assigned to this layout. I noticed that there are also 7 volumes assigned to the default collection despite that one using very little space. Then, I tried changing the TTL for new files written into this collection, which produced a new layout (ttl: 2d) that was also assigned 7 volumes.

Why are there always exactly 7 volumes in the layout -- is this a configuration parameter somewhere? How can I get seaweedfs to add more volumes to the collection when it's out of space?

**Comment by chrislusf** [comment]
what is the output of 'volume.list' from 'weed shell'?

**Reply by reberhardt7** [reply]
@chrislusf 

```
Topology volumeSizeLimit:30000 MB hdd(volume:21/33 active:14 free:12 remote:0)
  DataCenter us-west1 hdd(volume:21/33 active:14 free:12 remote:0)
    Rack persistent-disk hdd(volume:21/33 active:14 free:12 remote:0)
      DataNode seaweedfs-volume-0.seaweedfs-volume.storage:8080 hdd(volume:21/33 active:14 free:12 remote:0)
        Disk hdd(volume:21/33 active:14 free:12 remote:0)
          volume id:31  size:31457636456  collection:"my-volume-name"  file_count:201929  delete_count:39795  deleted_byte_count:4996528917  version:3  ttl:771  compact_revision:9  modified_at_second:1724715276 
          volume id:46  size:1465610792  collection:"my-volume-name"  file_count:9720  delete_count:3368  deleted_byte_count:270267919  version:3  ttl:515  compact_revision:2  modified_at_second:1724715342 
          volume id:48  size:1376183920  collection:"my-volume-name"  file_count:9669  delete_count:3317  deleted_byte_count:269592008  version:3  ttl:515  compact_revision:2  modified_at_second:1724715342 
          volume id:49  size:1613914160  collection:"my-volume-name"  file_count:11407  delete_count:5149  deleted_byte_count:452026265  version:3  ttl:515  compact_revision:2  modified_at_second:1724715342 
          volume id:34  size:31460747976  collection:"my-volume-name"  file_count:200828  delete_count:38174  deleted_byte_count:4755145567  version:3  ttl:771  compact_revision:9  modified_at_second:1724714998 
          volume id:32  size:31457646832  collection:"my-volume-name"  file_count:200643  delete_count:40016  deleted_byte_count:4973946407  version:3  ttl:771  compact_revision:9  modified_at_second:1724714998 
          volume id:30  size:31460804888  collection:"my-volume-name"  file_count:201061  delete_count:37965  deleted_byte_count:4740033704  version:3  ttl:771  compact_revision:8  modified_at_second:1724714796 
          volume id:55  size:7514496  file_count:45  version:3  modified_at_second:1724713960 
          volume id:56  size:3657480  file_count:53  version:3  modified_at_second:1724715220 
          volume id:44  size:1182959112  collection:"my-volume-name"  file_count:6867  delete_count:546  deleted_byte_count:52292108  version:3  ttl:515  compact_revision:3  modified_at_second:1724715342 
          volume id:29  size:31459626976  collection:"my-volume-name"  file_count:202689  delete_count:38096  deleted_byte_count:4673558456  version:3  ttl:771  compact_revision:9  modified_at_second:1724715276 
          volume id:45  size:1587457528  collection:"my-volume-name"  file_count:11421  delete_count:5015  deleted_byte_count:446904621  version:3  ttl:515  compact_revision:2  modified_at_second:1724715342 
          volume id:47  size:1440486320  collection:"my-volume-name"  file_count:9677  delete_count:3375  deleted_byte_count:285605847  version:3  ttl:515  compact_revision:2  modified_at_second:1724715342 
          volume id:51  size:5601856  file_count:40  version:3  modified_at_second:1724715160 
          volume id:53  size:7100880  file_count:43  version:3  modified_at_second:1724715340 
          volume id:54  size:8868328  file_count:50  version:3  modified_at_second:1724714500 
          volume id:33  size:31458147880  collection:"my-volume-name"  file_count:201011  delete_count:39954  deleted_byte_count:4901426430  version:3  ttl:771  compact_revision:9  modified_at_second:1724715283 
          volume id:35  size:31457639584  collection:"my-volume-name"  file_count:204027  delete_count:44761  deleted_byte_count:5402155706  version:3  ttl:771  compact_revision:9  modified_at_second:1724715284 
          volume id:43  size:1442776584  collection:"my-volume-name"  file_count:9708  delete_count:3369  deleted_byte_count:256574318  version:3  ttl:515  compact_revision:2  modified_at_second:1724715342 
          volume id:50  size:5848944  file_count:45  version:3  modified_at_second:1724715100 
          volume id:52  size:4361456  file_count:55  version:3  modified_at_second:1724715280 
        Disk hdd total size:230364592448 file_count:1480988 deleted_file:302900 deleted_bytes:36476058273 
      DataNode seaweedfs-volume-0.seaweedfs-volume.storage:8080 total size:230364592448 file_count:1480988 deleted_file:302900 deleted_bytes:36476058273 
    Rack persistent-disk total size:230364592448 file_count:1480988 deleted_file:302900 deleted_bytes:36476058273 
  DataCenter us-west1 total size:230364592448 file_count:1480988 deleted_file:302900 deleted_bytes:36476058273 
total size:230364592448 file_count:1480988 deleted_file:302900 deleted_bytes:36476058273
```

**Comment by chrislusf** [comment]
is it one error or a lot of similar errors?

**Reply by reberhardt7** [reply]
We had >100k of these filer errors over the span of 5 hours

**Reply by chrislusf** [reply]
ok. this seems a bug but no clear clue. How to reproduce this?

**Reply by reberhardt7** [reply]
Is it normal for new layouts to start with 7 volumes allocated, even with very little storage used? This should be easy for me to get a repro set up, in case that is not normal. I can try to write a script repro filling up the layout tomorrow, but obviously that is a little trickier to do.

Here is my values.yaml:

```
filer:
  data:
    size: 64Gi
    storageClass: premium-rwo
    type: persistentVolumeClaim
  logs:
    type: 
  nodeSelector: |
    cloud.google.com/machine-family: c3
  redirectOnRead: false
  replicas: 1
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 3000m
      memory: 8Gi
global: {}
master:
  data:
    type: emptyDir
  logs:
    type: 
  nodeSelector: |
    # Require nodes with Local SSD
    requiresLocalSSD: 'true'
  resources:
    limits:
      ephemeral-storage: 200Gi
      memory: 6Gi
    requests:
      cpu: '3'
      ephemeral-storage: 200Gi
      memory: 6Gi
  tolerations: |
    # Allow scheduling on nodes with Local SSD
    - effect: NoSchedule
      key: requiresLocalSSD
      operator: Equal
      value: 'true'
  volumeSizeLimitMB: 30000
podAnnotations:
  prometheus.io/path: "/metrics"
  prometheus.io/port: '9327'
  prometheus.io/scheme: http
  prometheus.io/scrape: 'true'
volume:
  dataCenter: us-west1
  dataDirs:
  - maxVolumes: 0
    name: data
    size: 1Ti
    storageClass: standard-rwo
    type: persistentVolumeClaim
  index: memory
  nodeSelector: |
    cloud.google.com/machine-family: c3
  podManagementPolicy: Parallel
  rack: persistent-disk
  replicas: 1
  resources:
    limits:
      memory: 12Gi
    requests:
      cpu: 3500m
      memory: 12Gi
```
