### ISSUE TITLE
Corrupted Files in Cluster

### ISSUE THREAD

**Issue by ProjectInitiative** [seaweedfs/seaweedfs#3183]
**Describe the bug**
Files copied to FUSE filer mount are being corrupted.

**System Setup**
- OS version **Debian GNU/Linux 11 (bullseye)**
- output of `weed version` **version 8000GB 3.11 d4ef06cdcf320f8b8b17279586e0738894869eff linux amd64**

```toml
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = true

[leveldb3]
# similar to leveldb2.
# each bucket has its own meta store.
enabled = true
dir = "/opt/seaweedfs/REDACTED/filer/filerldb3"                    # directory to store level db files
```

**Expected behavior**
Files copied via FUSE mount should match md5sum like any other mount.

**Additional context**
fstab entry:

```ini
fuse /mnt/swfs/localshared fuse.weed filer='REDACTED:8889,REDACTED:8889,REDACTED:8889',filer.path=/,nofail 0 0
```

```bash
root:~# md5sum /var/lib/pve/local-btrfs/images/526/vm-526-disk-0/disk.raw 
fba3db35d8d631a8014bbf89dbb3e9ca  /var/lib/pve/local-btrfs/images/526/vm-526-disk-0/disk.raw
root:~# cp /var/lib/pve/local-btrfs/images/526/vm-526-disk-0/disk.raw /mnt/swfs/localshared/
root:~# md5sum /mnt/swfs/localshared/disk.raw 
f8555d7c8bc4e0081dde769255ddc815  /mnt/swfs/localshared/disk.raw
```
