### ISSUE TITLE
crash in webdav

### ISSUE THREAD

**Issue by InitBing** [seaweedfs/seaweedfs#3440]
**Describe the bug**
crash in webdav

**System Setup**
default docker-compose.yml up
centos 7
version 30GB 3.20 0854171d linux amd64

**Expected behavior**
Files review in webdav

**Screenshots**
![image](https://user-images.githubusercontent.com/3724483/184581614-d524539c-01a9-40a0-92f1-ab2fb2fd7106.png)

volume permisions
![image](https://user-images.githubusercontent.com/3724483/184581655-5aae2c06-0f12-4c13-9c2a-31a87edb420d.png)

**Comment by InitBing** [comment]
```
version: '2'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    command: "master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324"
    restart: always
    volumes:
      - /data/master:/data
  volume:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325'
    volumes:
      - /data/volume:/data
    restart: always
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    volumes:
      - /data/filer:/data
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8333:8333
      - 9327:9327
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9327'
    volumes:
      - /data/s3:/data
    restart: always
    depends_on:
      - master
      - volume
      - filer
  webdav:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 7333:7333
    command: 'webdav -filer="filer:8888"'
    volumes:
      - /data/webdav:/data
    restart: always
    depends_on:
      - master
      - volume
      - filer
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - s3
    restart: always
```
