### ISSUE TITLE
Parallelized synchronization may block the volume server?

### ISSUE THREAD

**Issue by bernardx** [seaweedfs/seaweedfs#3553]
**Describe the bug**
We are using active-active replication between 3 nodes. This service has been running for about one year without any problem. By upgrading to the latest version(3.24), the newly added parallelized synchronization greatly improved the sync speed. However,  since the upgrade, we noticed that normal http request to the server hangs frequently.  After some investigation, we notice that this only happens if we enable the replication service. Here are some details:

- no error logs ~~
- only HTTP requests get blocked while the replication progress goes normally
```
 curl http://10.117.12.31:8888/buckets/main/reader/1.png -v
*   Trying 10.117.12.31...
* Connected to 10.117.12.31 (10.117.12.31) port 8888 (#0)
> GET /buckets/main/reader/1.png HTTP/1.1
> Host: 10.117.12.31:8888
> User-Agent: curl/7.47.0
> Accept: */*
> 
```

```
weedfs_replication_cn0 | I0830 10:13:47.080398 filer_sync.go:267 sync 10.117.22.2:8888 to 10.117.12.31:8888 progressed to 2022-08-25 20:41:56.33476931 +0000 UTC 210.09/sec
weedfs_replication_cn0 | I0830 10:13:50.122573 filer_sync.go:267 sync 10.117.22.2:8888 to 10.117.12.31:8888 progressed to 2022-08-25 20:41:56.33476931 +0000 UTC 274.47/sec
weedfs_replication_cn0 | I0830 10:13:53.248176 filer_sync.go:267 sync 10.117.22.2:8888 to 10.117.12.31:8888 progressed to 2022-08-25 20:41:56.33476931 +0000 UTC 257.23/sec
weedfs_replication_cn0 | I0830 10:13:56.460483 filer_sync.go:267 sync 10.117.22.2:8888 to 10.117.12.31:8888 progressed to 2022-08-25 20:41:56.33476931 +0000 UTC 220.40/sec
weedfs_replication_cn0 | I0830 10:13:59.586523 filer_sync.go:267 sync 10.117.22.2:8888 to 10.117.12.31:8888 progressed to 2022-08-25 20:41:56.33476931 +0000 UTC 180.42/sec
weedfs_replication_cn0 | I0830 10:14:02.703318 filer_sync.go:267 sync 10.117.22.2:8888 to 10.117.12.31:8888 progressed to 2022-08-25 20:41:56.33476931 +0000 UTC 230.36/sec
```
- restart filer and master server won't work, restart the volume server works
-  It does seem like a "running out of resources" issue, we tried to adjust ulimit, not working
 

**System Setup**
- We use docker-compose to deploy, here is the volume server part:
```
 volume:
    restart: always
    ports:
      - 8081:8081
      - 18081:18081
    ulimits:
      nproc: 65535
      nofile:
        soft: 1000000
        hard: 1000000
    privileged: true
    command: 'volume -disk=hdd,cold,temp -dir=/data,/data_cold,/data_temp -mserver="localhost:9333" -max=2000 -port 8081 -ip.bind="0.0.0.0"'
    volumes:
      - /data/weedvol:/data
      - /data/weedvol_cold:/data_cold
      - /data/weedvol_temp:/data_temp
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - master
```
- OS version ubuntu 18.04
- output of `weed version`
volume server 30GB 3.24 b7a887fe
- if using filer, show the content of `filer.toml`
```
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"

[leveldb3]
enabled = true
dir = "/data/filerldb3"
```
