### ISSUE TITLE
Can't use SeaweedFS with Outline Wiki

### ISSUE THREAD

**Issue by helmut72** [seaweedfs/seaweedfs#3737]
**Describe the bug**

[Outline Wiki](https://github.com/outline/outline) is setup to use bucket `outline`, but wants to upload to `outlineuploads` instead of `outline/uploads` when using SeaweedFS instead of Minio:

```
I0925 17:41:23.812434 common.go:70 response method:PUT URL:/buckets/outlineuploads/eaf10b3b-3b3a-4dcd-92a7-edf2a512276e/67b8b9bf-7cca-4cb6-9b34-22fcb4d6e27d/Bildschirmfoto%202022-09-19%20um%2021.38.37.png with httpStatus:500 and JSON:{"error":"rpc error: code = Unknown desc = no free volumes left for {\"collection\":\"outlineuploads\",\"replication\":{},\"ttl\":{\"Count\":0,\"Unit\":0}}"}
```

Correct, because there is no outlineuploads bucket. Just to show what I mean.

**System Setup**

docker-compose.yml

```
version: '3.8'

networks:
  seaweedfs:
    name: seaweedfs
    external: false

services:
  seaweedfs:
    container_name: seaweedfs
    image: chrislusf/seaweedfs
    restart: always
    command: -v=3 server -s3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /docker/data/seaweedfs:/data
    networks:
      - seaweedfs
    ports:
      - 8333:8333
```

- `s3.bucket.create -name outline`
- `s3.configure -access_key=outlinetest -secret_key=supersecrettest -buckets=outline -user=outlineuser -actions=Read,Write,List,Tagging,Admin -apply`
- `weed version` 30GB 3.27 d8ca7d34 linux amd64
- Using Caddy as Reverse Proxy for everything, about 30-40 Webapps

Output of Outline S3 configuration:

```
AWS_ACCESS_KEY_ID=outlinetest
AWS_SECRET_ACCESS_KEY=supersecrettest
AWS_REGION=us-east-1
AWS_S3_UPLOAD_BUCKET_URL=https://sea.example.com
AWS_S3_ACCELERATE_URL=
AWS_S3_UPLOAD_BUCKET_NAME=outline
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=true
AWS_S3_ACL=private
```

**Expected behavior**

SeaweedFS should be compatible with S3 lib used by Outline and allow uploading content.

**Additional context**

The same configuration works with Minio, just by replacing the URL to minio.example.com. Nothing more. Same bucket, same username + password. When sync from Minio to SeaweedFS with rclone, all synced content can be read by Outline:

```
I0925 17:41:00.518407 s3api_object_handlers.go:165 GetObjectHandler outline /uploads/eaf10b3b-3b3a-4dcd-92a7-edf2a512276e/b8b645bd-ac95-4020-a8d2-2a63012c024d/macbook-air-spacegray-gallery2-20220606_GEO_DE.jpeg
I0925 17:41:00.518458 s3api_object_handlers.go:342 s3 proxying GET to http://172.28.0.2:8888/buckets/outline/uploads/eaf10b3b-3b3a-4dcd-92a7-edf2a512276e/b8b645bd-ac95-4020-a8d2-2a63012c024d/macbook-air-spacegray-gallery2-20220606_GEO_DE.jpeg
```

Problem only exists while uploading content. Of course it can be also a problem with Outline, but I need to start somewhere. Thank you.
