### ISSUE TITLE
filer.sync dies on large files without message

### ISSUE THREAD

**Issue by michagruner** [seaweedfs/seaweedfs#3787]
**Describe the bug**
When I try to use filer.sync on a file larger than the available memory it dies without any message.

**System Setup**
Create a new Linux-VM (debian 11 in my case with 2GB of memory and 1GB of swap). Everything using weed 3.30

Create a large file with
`fallocate -l2G testfile.img`

Start up source-cluster with docker-compose.yaml

```
version: '2'

services:
  db:
    image: postgres:14-bullseye
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: seaweed.Pwd
      POSTGRES_USER: seaweed
      POSTGRES_DB: seaweedfs
    volumes: 
      - /home/mgruner/source/postgres:/var/lib/postgresql/data

  master0:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
      - 19333:19333
    volumes:
      - /home/mgruner/source/master:/data
    command: "master -ip=weedtest -ip.bind=0.0.0.0 -mdir=/data/m1"
    restart: unless-stopped
  volume1:
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
      - 18080:18080
    volumes:
      - /home/mgruner/source/volume1:/data
    command: 'volume -mserver="weedtest:9333" -port=8080 -ip.bind=0.0.0.0 -ip=weedtest -dir=/data/'
    restart: unless-stopped
    depends_on:
      - master0
  filer:
    image: chrislusf/seaweedfs
    ports:
      - 8888:8888
      - 18888:18888
    volumes:
      - /home/mgruner/source/filer:/data
      - ./filer.toml:/etc/seaweedfs/filer.toml
    command: 'filer -master="weedtest:9333" -ip.bind=0.0.0.0 -ip=weedtest'
    restart: unless-stopped
    depends_on:
      - master0
      - db

```
source filer.toml

```
# A sample TOML config file for SeaweedFS filer store
# Used with "weed filer" or "weed server -filer"
# Put this file to one of the location, with descending priority
#    ./filer.toml
#    $HOME/.seaweedfs/filer.toml
#    /etc/seaweedfs/filer.toml

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"


[postgres2]
enabled = true
createTable = """
  CREATE TABLE IF NOT EXISTS "%s" (
    dirhash   BIGINT,
    name      VARCHAR(65535),
    directory VARCHAR(65535),
    meta      bytea,
    PRIMARY KEY (dirhash, name)
  );
"""
hostname = "weedtest"
port = 5432
username = "seaweed"
password = "seaweed.Pwd"
database = "seaweedfs"          # create or use an existing database
schema = ""
sslmode = "disable"
connection_max_idle = 100
connection_max_open = 100
connection_max_lifetime_seconds = 0
# if insert/upsert failing, you can disable upsert or update query syntax to match your RDBMS syntax:
enableUpsert = true
upsertQuery = """INSERT INTO "%[1]s" (dirhash,name,directory,meta) VALUES($1,$2,$3,$4) ON CONFLICT (dirhash,name) DO UPDATE SET meta = EXCLUDED.meta WHERE "%[1]s".meta != EXCLUDED.meta"""

```
destination docker-compose.yaml:

```
version: '2'

services:
  db:
    image: postgres:14-bullseye
    restart: unless-stopped
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: seaweed.Pwd
      POSTGRES_USER: seaweed
      POSTGRES_DB: seaweedfs
    volumes: 
      - /home/mgruner/destination/postgres:/var/lib/postgresql/data

  master0:
    image: chrislusf/seaweedfs
    ports:
      - 9334:9334
      - 19334:19334
    volumes:
      - /home/mgruner/destination/master:/data
    command: "master -ip=weedtest -ip.bind=0.0.0.0 -port=9334 -mdir=/data/m1"
    restart: unless-stopped
  volume1:
    image: chrislusf/seaweedfs
    ports:
      - 8081:8081
      - 18081:18081
    volumes:
      - /home/mgruner/destination/volume1:/data
    command: 'volume -mserver="weedtest:9334" -port=8081 -ip.bind=0.0.0.0 -ip=weedtest -dir=/data/'
    restart: unless-stopped
    depends_on:
      - master0
  filer:
    image: chrislusf/seaweedfs
    ports:
      - 8889:8889
      - 18889:18889
    volumes:
      - /home/mgruner/destination/filer:/data
      - ./filer.toml:/etc/seaweedfs/filer.toml
    command: 'filer -master="weedtest:9334" -port=8889 -ip.bind=0.0.0.0 -ip=weedtest'
    restart: unless-stopped
    depends_on:
      - master0
      - db

```
destination filer.toml

```
# A sample TOML config file for SeaweedFS filer store
# Used with "weed filer" or "weed server -filer"
# Put this file to one of the location, with descending priority
#    ./filer.toml
#    $HOME/.seaweedfs/filer.toml
#    /etc/seaweedfs/filer.toml

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"


[postgres2]
enabled = true
createTable = """
  CREATE TABLE IF NOT EXISTS "%s" (
    dirhash   BIGINT,
    name      VARCHAR(65535),
    directory VARCHAR(65535),
    meta      bytea,
    PRIMARY KEY (dirhash, name)
  );
"""
hostname = "weedtest"
port = 54321
username = "seaweed"
password = "seaweed.Pwd"
database = "seaweedfs"          # create or use an existing database
schema = ""
sslmode = "disable"
connection_max_idle = 100
connection_max_open = 100
connection_max_lifetime_seconds = 0
# if insert/upsert failing, you can disable upsert or update query syntax to match your RDBMS syntax:
enableUpsert = true
upsertQuery = """INSERT INTO "%[1]s" (dirhash,name,directory,meta) VALUES($1,$2,$3,$4) ON CONFLICT (dirhash,name) DO UPDATE SET meta = EXCLUDED.meta WHERE "%[1]s".meta != EXCLUDED.meta"""


```
copy the file to the source-cluster:

`./weed filer.copy testfile.img http://weedtest:8888/`

sync the clusters:
`./weed -v 4 filer.sync -a weedtest:8888 -b weedtest:8889 -isActivePassive`

After weed dies equip the machine with 8GB of memory, restart it and try again. It works then.

**Expected behavior**
Sync files that are larger than the available memory.
