### ISSUE TITLE
Up/Download slow (~15MB/s) on docker / OSX M1 / boto3

### ISSUE THREAD

**Issue by mskoenz** [seaweedfs/seaweedfs#4246]
(really cool project, thx!!)

**Describe the bug**
Not a bug per se, just an observation: using a localhost setup with master, volume, filer and s3, I only reach ~15MB/sec for a movie up and download with the boto3 client.

**System Setup**
using the docker container:
```bash
> docker pull  chrislusf/seaweedfs
Using default tag: latest
latest: Pulling from chrislusf/seaweedfs
Digest: sha256:2c8227c96817dc9981796e1b6118812523fb910a28e91512fd15db84654aa104
Status: Image is up to date for chrislusf/seaweedfs:latest
docker.io/chrislusf/seaweedfs:latest
```
Version is:
```
> docker run chrislusf/seaweedfs version
version 30GB 3.43 673214574 linux arm64
```

with this compose file, run locally on an Apple MBP, 2020, M1, docker desktop Version 4.13.1:

```yml
version: '3.9'

services:
    sw-master:
        image: chrislusf/seaweedfs
        ports:
        -   9333:9333
        -   19333:19333 #gRPC
        -   9324:9324
        command: "master -ip=sw-master -ip.bind=0.0.0.0 -metricsPort=9324"
    sw-volume:
        image: chrislusf/seaweedfs
        ports:
        -   8080:8080
        -   18080:18080 #gRPC
        -   9325:9325
        volumes:
        -   ./data/volume:/data
        command: 'volume -mserver="sw-master:9333" -ip.bind=0.0.0.0 -port=8080 -metricsPort=9325'
        depends_on:
        -   sw-master
    sw-filer:
        image: chrislusf/seaweedfs
        ports:
        -   8888:8888
        -   18888:18888 #gRPC
        -   9326:9326
        command: 'filer -master="sw-master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
        volumes:
        -   ./data/filer:/data
        tty: true
        stdin_open: true
        depends_on:
        -   sw-master
        -   sw-volume
    sw-s3:
        image: chrislusf/seaweedfs
        ports:
        -   8333:8333
        -   9327:9327
        volumes:
        -   ./seaweedfs-s3-config.json:/config.json
        command: 's3 -filer="sw-filer:8888" -ip.bind=0.0.0.0 -metricsPort=9327 -config=/config.json'
        depends_on:
        -   sw-master
        -   sw-volume
        -   sw-filer


```

running the following python script (uploading and downloading a movie):
```python
#!/usr/bin/env python
import boto3
import time

def main():
    s3 = boto3.client('s3',
            aws_access_key_id="abc",
            aws_secret_access_key= "abc",
            endpoint_url = "http://localhost:8333",
    )

    file_name = '2_7_GB_file.mp4'
    download_name = '2_7_GB_file_dl.mp4'
    object_name = "2_7_GB_file.mp4"
    bucket = "Buk"

    start = time.time()
    s3.upload_file(file_name, bucket, object_name)
    print("upload took", time.time()-start)

    start = time.time()
    s3.download_file(bucket, object_name, download_name)
    print("download took", time.time()-start)

if __name__ == "__main__":
    main()
```

This takes:
```
upload took 157.8
download took 183.4
```

which makes the up and download rate ~15MB/s.

I tested removing the volume mounts, as it could be faster within the container, but results were the same.

**Expected behavior**

More than ~15MB/s on a localhost setup.
Likely I missed a configuration option, just started out with the docker example and trimmed it down...
