### ISSUE TITLE
Dose Filer Stores  support etcd username and password

### ISSUE THREAD

**Issue by ibanmen** [seaweedfs/seaweedfs#4262]
- use helm chart install seaweedfs 3.34 in k8s cluster 
```
  extraEnvironmentVars:
    WEED_ETCD_ENABLED: "true"
    WEED_ETCD_SERVERS: "http://etcd.sso:2379"
    WEED_ETCD_TIMEOUT: "3s"
    WEED_ETCD_USERNAME: "root"
    WEED_ETCD_PASSWORD: 
```
- run the command:  helm install seaweedfs -f values.yaml seaweedfs-3.43.tgz
- see the error
```
{"level":"warn","ts":"2023-03-02T10:16:05.254Z","logger":"etcd-client","caller":"v3@v3.5.7/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00066c380/etcd.sso:2379","attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty"}
F0302 10:16:05.254230 filer.go:133 read filer.store.id= : kv get: etcdserver: user name is empty
goroutine 1 [running]:
```

**Comment by chrislusf** [comment]
https://github.com/seaweedfs/seaweedfs/blob/master/weed/filer/etcd/etcd_store.go#L34

No. But it should be very simple to add them. You are welcome to send a PR.

**Comment by mhameed** [comment]
Hi @chrislusf
Firs time contributing to a go project, so forgive me if I have overlooked something.
The commit addresses the issue mensioned and seems to work ok in my environment.
Does it look ok to you?

**Comment by chrislusf** [comment]
Looks good. But you would need to create a PR for it.

**Comment by cr1cr1** [comment]
Thank you for implementing this. The problem when setting just `WEED_ETCD_USERNAME` as `root` (with etcd is always root), the etcd client is throwing misleading error `kv get: etcdserver: user name is empty`.

Setting the password as well, works. Could be set in the helm chart values:
```yaml
filer:
  ...
  extraEnvironmentVars:
    ...
    WEED_ETCD_USERNAME: root
    WEED_ETCD_PASSWORD:
      secretKeyRef:
        name: etcd
        key: etcd-root-password
```
