### ISSUE TITLE
Bucket Files via S3 Do not Persist After docker-compose down

### ISSUE THREAD

**Issue by diegoripley** [seaweedfs/seaweedfs#4266]
**Describe the bug**

1. I create a bucket via `mc` successfully (see image below) and upload some files via `mc cp`

![2023-03-02-165418_746x295_scrot](https://user-images.githubusercontent.com/6893641/222567205-39935139-5591-4bfe-ac80-c04e26bd2006.png)

2. After I do `docker-compose down` and `docker-compose up -d`, the buckets no longer available via the S3 URL

![2023-03-02-165834_776x205_scrot](https://user-images.githubusercontent.com/6893641/222568115-86ae712b-7738-402b-a731-9f1fbb648d60.png)

3. When looking at the volume files, it seems that the `test` bucket files are still there
![2023-03-02-171135_507x404_scrot](https://user-images.githubusercontent.com/6893641/222570606-48117bbf-4863-4fef-be01-6867ddd95cf7.png)

**System Setup**
Docker setup, see below for `docker-compose.yml` and `s3.json`
```
version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs 
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    command: "master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324"
  volume:
    image: chrislusf/seaweedfs 
    ports:
      - 8085:8085
      - 18085:18085
      - 9325:9325
    command: 'volume -dir="/data" -mserver="master:9333" -ip.bind=0.0.0.0 -port=8085  -metricsPort=9325'
    volumes:
      - /mnt/bay-01/apps/seaweedfs/data:/data
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
  s3:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8333:8333
      - 9327:9327
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9327'
    volumes:
      - ./s3.json:/etc/seaweedfs/s3.json
    depends_on:
      - master
      - volume
      - filer
```
```
{
  "identities": [
    {
      "name": "ripledi",
      "credentials": [
        {
          "accessKey": "XayorXXeZFUhdKSwuXhxcLeZUzYj2rSU7eEx8e8pxTDeLtXy7eJdKTT",
          "secretKey": "FmZ2qVfve8CFUkGkh5sddZfT5LU6h5F2C8ZnzbE77CcdGxN6roCX6Km"
        }
      ],
      "actions": [
        "Admin",
        "Read",
        "List",
        "Tagging",
        "Write"
      ]
    }
  ]
}
```

**Expected behavior**
I expect to see in the S3 API end-point the bucket/files that I uploaded prior to `docker-compose down`

Thank you in advance!

**Comment by chrislusf** [comment]
If you setup an external filer store, such as mysql, the bucket data will persist.

**Comment by diegoripley** [comment]
@chrislusf I looked through all of the examples in the docker folder and do not see an example on how to do this, do you mind giving me an example? I looked through the documentation and the only thing I could find is the following.

https://github.com/seaweedfs/seaweedfs/issues/1227
https://github.com/seaweedfs/seaweedfs/tree/master/weed/filer/postgres

**Comment by diegoripley** [comment]
OK I tried the following and it still is not working. 

Added a PostgreSQL database to my `docker-compose.yml` and mounted the `filer.toml`
**filer.toml**
```
[postgres] # or cockroachdb, YugabyteDB
# CREATE TABLE IF NOT EXISTS filemeta (
#   dirhash     BIGINT,
#   name        VARCHAR(65535),
#   directory   VARCHAR(65535),
#   meta        bytea,
#   PRIMARY KEY (dirhash, name)
# );
enabled = true
hostname = "db"
port = 5432
username = "postgres"
password = "3QdWxScW8jv6yHn9"
database = "seaweedfs"          # create or use an existing database
schema = ""
sslmode = "disable"
connection_max_idle = 100
connection_max_open = 100
connection_max_lifetime_seconds = 0
# if insert/upsert failing, you can disable upsert or update query syntax to match your RDBMS syntax:
enableUpsert = true
upsertQuery = """INSERT INTO "%[1]s" (dirhash,name,directory,meta) VALUES($1,$2,$3,$4) ON CONFLICT (dirhash,name) DO UPDATE SET meta = EXCLUDED.meta WHERE "%[1]s".meta != EXCLUDED.meta"""

```

```
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
    tty: true
    stdin_open: true
    volumes:
      - ./filer.toml:/etc/seaweedfs/filer.toml
    depends_on:
      - master
      - volume
      - db
  db:
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3QdWxScW8jv6yHn9
      - POSTGRES_DB=seaweedfs
```
