### ISSUE TITLE
Successful but incomplete upload when volume server appears during upload

### ISSUE THREAD

**Issue by thcyron** [seaweedfs/seaweedfs#4408]
**Describe the bug**

I’m testing SeaweedFS’s resiliency when it comes to volume server availability and observed the following issue multiple times:

* Setup with 1 master, 1 filer, 1 S3, and 2 volume servers, replication is set to 001
* Stop volume server 2
* Start upload of a 100MB file
* Because there are not enough volume servers to fulfill replication requirements, the upload doesn’t finish
* Bring back volume server 2
* Eventually, the upload finishes successfully
* File on server is less than 100MB (usually between 60 and 90 MB)

```
$ du -sh ~/Downloads/100MB.bin 
100M	/Users/thomas/Downloads/100MB.bin

$ mc cp ~/Downloads/100MB.bin weed/test/100MB.bin
...omas/Downloads/100MB.bin: 100.00 MiB / 100.00 MiB

$ mc ls weed/test                                
[2023-04-17 12:22:10 CEST]  64MiB STANDARD 100MB.bin

$ mc cp weed/test/100MB.bin .
...host:8333/test/100MB.bin: 64.00 MiB / 64.00 MiB

$ du -sh 100MB.bin 
 64M	100MB.bin

```

It does not happen all the time, but quite often. It’s also reproducible with `aws s3` so I would say it’s not a client issue. Tested with both 3.45 and 3.46.

**How to reproduce**

Using the following Docker Compose `bug.yml`:

```
version: '3.9'

services:
  master:
    image: chrislusf/seaweedfs:3.46
    ports:
      - 9333:9333
      - 19333:19333
    command: "-v=4 master -ip=master -defaultReplication=001"
  volume1:
    image: chrislusf/seaweedfs:3.46
    ports:
      - 8080:8080
      - 18080:18080
    command: '-v=4 volume -mserver=master:9333 -port=8080 -ip=volume1'
    depends_on:
      - master
  volume2:
    image: chrislusf/seaweedfs:3.46
    ports:
      - 8082:8082
      - 18082:18082
    command: '-v=4 volume -mserver=master:9333 -port=8082 -ip=volume2'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs:3.46
    ports:
      - 8888:8888
      - 18888:18888
      - 8111:8111
    command: '-v=4 filer -master=master:9333'
    depends_on:
      - master
  s3:
    image: chrislusf/seaweedfs:3.46
    ports:
      - 8333:8333
    command: '-v=4 s3 -ip.bind=0.0.0.0 -filer=filer:8888'
    depends_on:
      - master
      - filer
```

1. `docker-compose -f bug.yml up -d`
2. `docker-compose -f bug.yml stop volume2`
3. `mc cp 100MB.bin weed/test/100MB.bin`
4. `docker-compose -f bug.yml start volume2`
5. `mc ls weed/test`

**Expected behavior**
The full 100MB file is uploaded, i.e. no silent data loss.
