### ISSUE TITLE
Auth Value of gRPC Response of LookupVolume is empty instead of containing a JWT

### ISSUE THREAD

**Issue by lorenzvoss** [seaweedfs/seaweedfs#4577]
**Describe the bug**
When calling the Method "LookupVolume" with a FileId via gRPC on the Master Server the Auth-Value of the response is empty even though i added a security.toml with jwt keys to my servers.
```
var channel = GrpcChannel.ForAddress("<ip address>");
            var client = new Seaweed.SeaweedClient(channel);
            LookupVolumeRequest request = new LookupVolumeRequest();
            request.VolumeOrFileIds.Add("1,290c3fc91f20");
            var res = client.LookupVolume(request);
            Console.WriteLine("Auth: '" + res.VolumeIdLocations[0].Auth + "'");
```
The Console Part outputs nothing and res.Auth == "" is True.

**System Setup**
Seaweed running via docker with this compose file:

```
version: '3.9'

services:
  masterjwt:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    container_name: seaweedfs-master-jwt
    command: "master -ip=172.28.0.102 -ip.bind=0.0.0.0 -metricsPort=9324" 
  volume1jwt:
    image: chrislusf/seaweedfs # use a remote image
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    container_name: seaweedfs-volume-1-jwt
    command: 'volume -mserver="masterjwt:9333" -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325 -publicUrl=<ip>'
    depends_on:
      - masterjwt
```

- output of `weed version`: version 30GB 3.51 4310e1fac linux amd64
- i added following security.toml file to volume and master server:

```
[jwt.signing]
key = "<my key>"
expires_after_seconds = 120           # seconds

[access]
ui = true


[jwt.signing.read]
key = "<m< key>"
expires_after_seconds = 120           # seconds
```

**Expected behavior**
I excpect the Response to include a JWT in the Auth value to read or update the given file. It works fine via http like this:
`curl -i "<ip master>:9333/dir/lookup?fileId=1,290c3fc91f20&read=yes"`
