### ISSUE TITLE
New version of seaweedfs can't list directory using s3 api

### ISSUE THREAD

**Issue by Zen3515** [seaweedfs/seaweedfs#4668]
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/seaweedfs/seaweedfs/discussions

**Describe the bug**
Let me show you the behaviour, the client I used was minio client. with seaweed version 3.53 and 3.43
```shell
# using weed version 3.53
$ mc ls weed-admin/images/reverse_bag_images/
# NO OUTPUT FOR THE ABOVE COMMAND
$ mc ls weed-admin/images/reverse_bag_images
[2023-07-12 12:06:09 +07]     0B reverse_bag_images/

# revert update to version 3.43
$ mc ls weed-admin/images/reverse_bag_images
[2023-07-12 12:13:17 +07]     0B 2023-07-03/
[2023-07-12 12:13:17 +07]     0B 2023-07-04/
$ mc ls weed-admin/images/reverse_bag_images/
[2023-07-12 12:13:19 +07]     0B 2023-07-03/
[2023-07-12 12:13:19 +07]     0B 2023-07-04/
```
As you can see from the above output, s3 file list was only working when I uses the older version of seaweedfs.

**My story**

I was happily using seaweedfs for a long time without any problem, until yesterday that I try update my servers to newest version, that I encounter this problem. After browsing through the releases changes log, I suspect [this release](https://github.com/seaweedfs/seaweedfs/releases/tag/3.46). My current solution is to revert the update, and continue to use 3.43 for now.

**System Setup**
```shell
$ uname -a
Linux example-storage-2 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ weed version
version 30GB 3.43 3227e4175e2bf8df2ac8aeeff8cf73a819abc5a7 linux amd64

$ /usr/bin/weed master -mdir=/etc/seaweedfs/weed-meta -ip=storage2.example.com -ip.bind=0.0.0.0 -port=9333 -defaultReplication=010 -peers=storage3.example.com:9333,storage4.example.com:9333
$ /usr/bin/weed volume -mserver=storage2.example.com:9333,storage3.example.com:9333,storage4.example.com:9333 -max=0 -ip.bind=0.0.0.0 -port=8081 -dataCenter=main-site -rack=example-storage-2 -dir=/mnt/nvme1/seaweedfs,/mnt/nvme2/seaweedfs,/mnt/nvme3/seaweedfs,/mnt/nvme4/seaweedfs
$ /usr/bin/weed filer -master=storage2.example.com:9333,storage3.example.com:9333,storage4.example.com:9333 -dataCenter=main-site -ip=storage2.example.com -ip.bind=0.0.0.0 -s3 -s3.dataCenter=main-site -s3.config=/etc/seaweedfs/s3-config.json -s3.cert.file=/data/letsencrypt/certificates/example-storage-2.example.com.crt -s3.key.file=/data/letsencrypt/certificates/example-storage-2.example.com.key
```

```shell
$ cat /etc/seaweedfs/filer.toml
```
```toml
# A TOML config file for SeaweedFS filer store

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false

####################################################
# The following are filer store options
####################################################
# We're forced to use redis sentinel since redis cluster require at least 6 nodes (we have only 4)
[redis3_sentinel]
enabled = true
addresses = ["redis1.storage.example:26379","redis2.storage.example:26379","redis3.storage.example:26379","redis4.storage.example:26379"]
masterName = "mymaster"
username = "default"
password = "RETRACTED"
database = 0
```

**Expected behavior**
I expect that I can use s3 api to list files

**Comment by ldapomni** [comment]
I think this problem is of the same type with #4645

**Comment by Zen3515** [comment]
> I think this problem is of the same type with #4645. For the correct display of directories via s3, special metadata FolderMimeType = "httpd/unix-directory" was introduced. But it doesn't seem to be finished

In that case, can you test if older version of seaweedfs works? Maybe we could pinpoint the exact version that this issue first appear.

**Comment by ldapomni** [comment]
Yes, it used to be fine in the old versions

**Comment by agipson33** [comment]
I can confirm this happened with the release of 3.46. Directory listings using the s3 service works as expected through version 3.45.

**Comment by chrislusf** [comment]
can not reproduce. Does this problem only happen to old directories?

**Comment by ldapomni** [comment]
> can not reproduce. Does this problem only happen to old directories?

Old directories work fine. Problem when creating new directories in NC

**Comment by Zen3515** [comment]
> can not reproduce. Does this problem only happen to old directories?

I could not revert my production back to reproduce, but here are my points based on my observation.

- Filer works just fine (port 8888)
- Directory depth may matters, the first folder (bucket) works, the nested one after this doesn't.
```shell
# Below are working
$ mc ls S3CON/ # listing bucket
$ mc ls S3CON/bucket/ # listing inside a bucket

# Below is not working
$ mc ls S3CON/bucket/folder_inside_bucket/ # listing folder inside a bucket
```
- If I recall correctly, createing directory with `fs.mkdir` may works, but don't take my word for it.

**Comment by SmsS4** [comment]
I have the same problem when connectin [Filestash](https://github.com/mickael-kerjean/filestash) to my s3 and create a folder using Filestash

**Comment by renweijun** [comment]
I have the same problem to new directories and old directories
# Below are working with the release 3.43～3.45
s5cmd ls  s3://s3bucket/2023/* 
2023/07/13 04:03:00                 2 3
# Below is not working with the release of 3.46～3.53
s5cmd ls  s3://s3bucket/2023/* 
ERROR "ls s3://s3bucket/2023/*": no object found

**Comment by chrislusf** [comment]
Some steps to reproduce this would be helpful.

**Comment by renweijun** [comment]
Here are the steps to reproduce it:

```
echo "s3.bucket.create -name s3bucket "|weed shell
echo "s3.configure -access_key=s3bucket -secret_key=key123456 -buckets=s3bucket -user=s3bucket-actions=Read,Write,List,Tagging,Admin -apply"|weed shell
echo "mkdir buckets/s3bucket/2023/1" |weed shell
./weed filer.copy  filer.toml http://master1:8888/buckets/s3bucket/2023/1 
download s5cmd ,https://github.com/peak/s5cmd/releases/tag/v2.1.0
export S3_ENDPOINT_URL="http://master1:8888/"
export AWS_ACCESS_KEY_ID=s3bucket
export AWS_SECRET_ACCESS_KEY=key123456
```
```
weed version 3.46
./s5cmd ls  s3://s3bucket/2023/1/*
ERROR "ls s3://s3bucket/2023/1/*": no object found
weed version 3.45
./s5cmd ls  s3://s3bucket/2023/1/*
2023/07/14 12:04:42              7906  filer.toml
```

**Comment by chrislusf** [comment]
@renweijun followed the steps, seems working well:
```
chrislu/tmp ()  > echo "s3.bucket.create -name s3bucket "|weed shell
I0716 13:33:23.053597 masterclient.go:209 master localhost:9333 redirected to leader 192.168.2.7:9333
.master: localhost:9333 filers: [192.168.2.7:8888]
create bucket under /buckets
created bucket s3bucket
chrislu/tmp ()  > echo "mkdir buckets/s3bucket/2023/1" |weed shell
I0716 13:33:33.647634 masterclient.go:209 master localhost:9333 redirected to leader 192.168.2.7:9333
.master: localhost:9333 filers: [192.168.2.7:8888]
chrislu/tmp ()  > weed filer.copy local11.option http://localhost:8888/buckets/s3bucket/2023/1
The last argument should be a folder and end with "/"
...
chrislu/tmp ()  > weed filer.copy local11.option http://localhost:8888/buckets/s3bucket/2023/1/
chrislu/tmp ()  > s5cmd ls  s3://s3bucket/2023/1/*
zsh: no matches found: s3://s3bucket/2023/1/*
chrislu/tmp ()  > s5cmd ls  s3://s3bucket/2023/1/
2023/07/16 20:34:21               212  local11.option
```

**Comment by renweijun** [comment]
@chrislusf Sorry, the Filer Store I used is redis_cluster3，I just tested OK with leveldb3, is it related to Filer Store？
```
[redis_cluster3] # beta
enabled = true
addresses = [
    "192.168.1.2:6379",
    "192.168.1.3:6379",
    "192.168.1.4:6379",
]
password = "keypass"
# allows reads from slave servers or the master, but all writes still go to the master
readOnly = false
# automatically use the closest Redis server for reads
routeByLatency = false
```

**Comment by chrislusf** [comment]
@Zen3515 @SmsS4 do you have some reproducible steps for 3.53?

**Comment by Zen3515** [comment]
> @Zen3515 @SmsS4 do you have some reproducible steps for 3.53?

I've spin up a new server just for this, surprisingly I could not reproduce it, The only different were 
1. I switch from `redis3_sentinel` to `leveldb2`.
2. I switch from 3 nodes -- 3 masters, 3 volume, 3 filers to 1 node -- 1 master, 1 volume, 1 filer.

Can someone else confirm if they're using the same filer store?  
@SmsS4 Do you uses Redis as well?  
How many nodes do you have?  

My production filer

```toml
# A TOML config file for SeaweedFS filer store

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false

####################################################
# The following are filer store options
####################################################
# We're forced to use redis sentinel since redis cluster require at least 6 nodes (we have only 4)
[redis3_sentinel]
enabled = true
addresses = ["redis1.storage.example:26379","redis2.storage.example:26379","redis3.storage.example:26379","redis4.storage.example:26379"]
masterName = "mymaster"
username = "default"
password = "RETRACTED"
database = 0
```

My new filer

```toml
# A TOML config file for SeaweedFS filer store

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false

####################################################
# The following are filer store options
####################################################
# We're forced to use redis sentinel since redis cluster require at least 6 nodes (we have only 4)
[leveldb2]
# local on disk, mostly for simple single-machine setup, fairly scalable
# faster than previous leveldb, recommended.
enabled = true
dir = "/etc/seaweedfs/filerldb2"                    # directory to store level db files
```
