### ISSUE TITLE
Only has 1 racks with more than 1 free data nodes, not enough for 2.

### ISSUE THREAD

**Issue by ghpdc** [seaweedfs/seaweedfs#4763]
I'm trying to replicate existing volumes from one NAS to another one.  Getting the following error:

> I0817 18:42:21.720527 volume_growth.go:100 create 6 volume, created 0: No matching data node found! 
> home:Only has 1 racks with more than 1 free data nodes, not enough for 2.

**System Setup**
NAS 1 (qnap rack)

```
services:
  master:
    command: 'master -ip="192.168.1.208" -ip.bind=0.0.0.0 -metricsPort=9321 -volumeSizeLimitMB=250000 -volumePreallocate -defaultReplication=010'
    environment: ['PUID=${PUID}', 'PGID=${PGID}', 'TZ=${TIMEZONE}']
    image: chrislusf/seaweedfs:3.53_large_disk
    network_mode: "host"
    restart: always   
    volumes: ['${CONFIG_DIR}/seaweed/master:/data'] 
  filer:
    command: 'filer -master="192.168.1.208:9333" -ip.bind=0.0.0.0 -metricsPort=9322'    
    depends_on: [master, volume_0, volume_1, volume_2, volume_3]
    environment: ['PUID=${PUID}', 'PGID=${PGID}', 'TZ=${TIMEZONE}']
    image: chrislusf/seaweedfs:3.53_large_disk
    network_mode: "host"
    restart: always   
    stdin_open: true
    tty: true
    volumes: ['${CONFIG_DIR}/seaweed/filer:/data']
  mount:
    cap_add: [SYS_ADMIN]
    depends_on: [volume_0, volume_1, volume_2, volume_3, filer]
    devices: [fuse]
    entrypoint: '/bin/sh -c "weed -v=4 mount -filer=192.168.1.208:8888 -filer.path=/ -cacheCapacityMB=0 -memprofile=/data/mount.mem.pprof"'
    image: chrislusf/seaweedfs:3.53_large_disk
    network_mode: "host"
    privileged: true
    restart: always
    security_opt: ['apparmor=unconfined']
    volumes:
    - bind: {propagation: shared}
      source: /share/Public/seaweedfs_mount
      target: /data
      type: bind    
  volume_0:
    command: 'volume -mserver="192.168.1.208:9333" -ip.bind=0.0.0.0 -port=8082  -metricsPort=9323 -dataCenter=home -rack=qnap -max 69'
    depends_on: [master]
    environment: ['PUID=${PUID}', 'PGID=${PGID}', 'TZ=${TIMEZONE}']
    image: chrislusf/seaweedfs:3.53_large_disk
    network_mode: "host"
    restart: always
    volumes: ['/share/Public/seaweedfs_vol0:/data']      
  volume_1:
    command: 'volume -mserver="192.168.1.208:9333" -ip.bind=0.0.0.0 -port=8083  -metricsPort=9324 -dataCenter=home -rack=qnap'
    depends_on: [master]
    environment: ['PUID=${PUID}', 'PGID=${PGID}', 'TZ=${TIMEZONE}']
    image: chrislusf/seaweedfs:3.53_large_disk
    network_mode: "host"
    restart: always
    volumes: ['/share/ext1/seaweedfs_vol1:/data']
  volume_2:
    command: 'volume -mserver="192.168.1.208:9333" -ip.bind=0.0.0.0 -port=8084  -metricsPort=9325 -dataCenter=home -rack=qnap'
    depends_on: [master]
    environment: ['PUID=${PUID}', 'PGID=${PGID}', 'TZ=${TIMEZONE}']
    image: chrislusf/seaweedfs:3.53_large_disk
    network_mode: "host"
    restart: always
    volumes: ['/share/ext2/seaweedfs_vol2:/data']
  volume_3:
    command: 'volume -mserver="192.168.1.208:9333" -ip.bind=0.0.0.0 -port=8085  -metricsPort=9326 -dataCenter=home -rack=qnap'
    depends_on: [master]
    environment: ['PUID=${PUID}', 'PGID=${PGID}', 'TZ=${TIMEZONE}']
    image: chrislusf/seaweedfs:3.53_large_disk
    network_mode: "host"
    restart: always
    volumes: ['/share/ext3/seaweedfs_vol3:/data']  
version: '3.9'
```

NAS 2 (qnap96 rack)

```
services:
  filer:
    command: 'filer -master="192.168.1.208:9333" -ip.bind=0.0.0.0 -metricsPort=9322'    
    depends_on: [volume_0]
    environment: ['PUID=${PUID}', 'PGID=${PGID}', 'TZ=${TIMEZONE}']
    image: chrislusf/seaweedfs:3.53_large_disk
    network_mode: "host"
    restart: always   
    stdin_open: true
    tty: true
    volumes: ['${CONFIG_DIR}/seaweed/filer:/data']
  mount:
    cap_add: [SYS_ADMIN]
    depends_on: [volume_0, filer]
    devices: [fuse]
    entrypoint: '/bin/sh -c "weed -v=4 mount -filer=192.168.1.208:8888 -filer.path=/ -cacheCapacityMB=0 -memprofile=/data/mount.mem.pprof"'
    image: chrislusf/seaweedfs:3.53_large_disk
    network_mode: "host"
    privileged: true
    restart: always
    security_opt: ['apparmor=unconfined']
    volumes:
    - bind: {propagation: shared}
      source: /share/Public/seaweedfs_mount
      target: /data
      type: bind    
  volume_0:
    command: 'volume -mserver="192.168.1.208:9333" -ip.bind=0.0.0.0 -port=8082  -metricsPort=9323 -dataCenter=home -rack=qnap96'
#    depends_on: [master]
    environment: ['PUID=${PUID}', 'PGID=${PGID}', 'TZ=${TIMEZONE}']
    image: chrislusf/seaweedfs:3.53_large_disk
    network_mode: "host"
    restart: always
    volumes: ['/share/Public/seaweedfs_vol0:/data']           
version: '3.9'
```

I expected seaweed to allocate volumes on NAS 2 and replicate existing volumes on NAS 1 to NAS 2.

<img width="1205" alt="Screenshot 2023-08-17 at 2 25 47 PM" src="https://github.com/seaweedfs/seaweedfs/assets/142535009/95d914a6-8a23-46db-a240-a5f6af4b64c6">

Thanks very much for your help!
