### ISSUE TITLE
Wrong default value for volume.ressource

### ISSUE THREAD

**Issue by armandleopold** [seaweedfs/seaweedfs#4854]
https://github.com/seaweedfs/seaweedfs/blob/0bb97709d41b1be4c74f01dcc65aac6d5f88bd16/k8s/charts/seaweedfs/values.yaml#L283

Getting  : 

aleopold@aleopold:~/desktop/helm/charts/qalita$ helm lint -f values.yaml .
coalesce.go:220: warning: cannot overwrite table with non table for qalita.seaweedfs.volume.resources (map[])
coalesce.go:220: warning: cannot overwrite table with non table for qalita.seaweedfs.volume.resources (map[])
coalesce.go:220: warning: cannot overwrite table with non table for qalita.seaweedfs.volume.resources (map[])
coalesce.go:220: warning: cannot overwrite table with non table for qalita.seaweedfs.volume.resources (map[])

when values are : 

```yaml
seaweedfs:
  volume:
    resources: |
      requests:
        memory: "100Mi"
        cpu: "50m"
...
```

Please replace to : 

```yaml
resources: null
```
