### ISSUE TITLE
Documentation update - docker use / mount directory on host from docker compose

### ISSUE THREAD

**Issue by zguig52** [seaweedfs/seaweedfs#5078]
**Describe the bug**
The procedure to mount from docker container a filer exposed to the host is not working (https://github.com/seaweedfs/seaweedfs/wiki/FUSE-Mount):
```
Mount directory on host from docker-compose
If docker compose is being used to manage the server (eg. https://github.com/seaweedfs/seaweedfs/wiki/Getting-Started#with-compose) it's possible to mount a directory on the host with docker privileged mode like so:

  mount_1:
    # Mount my weed seaweed volume to host /weed path
    image: chrislusf/seaweedfs
    privileged: true
    pid: host
    entrypoint: 'nsenter -t 1 -m -u -n -i -- /usr/bin/weed mount -filer="localhost:8888,localhost:8889" -filer.path=/weed -dir=/weed'
    depends_on:
      - master
      - filer

```

It did not work as the nsenter command was implyoing searching binaries on the host filesystem (at least I was having /usr/bin/weed not found error messages so that is my assumption)

**System Setup**
docker run chrislusf/seaweedfs version
version 30GB 3.59 27b34f379 linux amd64
Using RockyLinux 9 with SELinux enabled and docker 24.0.7

**Expected behavior**
I managed to make it work with different research on docker mount capabilities. My final minimalized working configuration (adapted to the wiki conventions) is the following:
```
  mount_1:
    image: chrislusf/seaweedfs
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes:
      - "/hostdata/mount:/mnt:z,shared"
    entrypoint: weed
    command: mount
    environment:
      - DIR=/mnt/data
      - DIRAUTOCREATE=true
      - FILER=localhost:8888,localhost:8889
```

Please note following important options:
1.    cap_add:
      - SYS_ADMIN
=> to minimize the privileges required and not provide all like with privileged: true
2.    devices:
      - "/dev/fuse:/dev/fuse"
=> to allow access to host fuse module (otherwhile it fails with module fuse not found)
3.    volumes:
      - "/hostdata/mount:/mnt:z,shared"
=> z to allow SeLinux and most important the shared bind mode allowing to propagate (cf: https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation)
4.    environment:
      - DIR=/mnt/data
      - DIRAUTOCREATE=true
==> It did not work when I was using the same mount point as the bind mount but as soon as I used a subfolder mount point it was working fine

**Side note**
Congrats for this amazing project, really simple to understand, start and configurable to allow scalling on small setups as well as big ones...
