### ISSUE TITLE
Can't upload files to multiple buckets

### ISSUE THREAD

**Issue by dsgibbons** [seaweedfs/seaweedfs#5104]
**Describe the bug**
When using `docker compose` to spin up `seaweedfs`, I can only upload files to the first bucket that contains a file. Uploads to any other buckets fail.

**System Setup**
Save the following file to `docker-compose.yml`:
```yaml
version: "3.8"
services:
  s3:
    image: chrislusf/seaweedfs
    restart: always
    ports:
      - 8333:8333
    command: 'server -dir=/data -s3 -idleTimeout=30'
```
Run `docker compose up -d`.

Install `awscli` using `pip install awscli`.

Create buckets:
```bash
aws s3 mb s3://test/ --endpoint-url http://localhost:8333 --no-sign-request
aws s3 mb s3://test2/ --endpoint-url http://localhost:8333 --no-sign-request
```

Create a file to upload:
```bash
echo "This is a test" > ./test.txt
```

Upload the first file:
```bash
aws s3 cp ./test.txt s3://test/folder/test.txt --endpoint-url http://localhost:8333 --no-sign-request
```

Works fine. Then, upload the same file to the other bucket:
```bash
aws s3 cp ./test.txt s3://test2/folder/test.txt --endpoint-url http://localhost:8333 --no-sign-request
```

Receive the following error:
```bash
upload failed: ./test.txt to s3://test2/folder/test.txt An error occurred (InternalError) when calling the PutObject operation (max retries: 4): We encountered an internal error, please try again.
```

This error occurs regardless of S3 client (`awscli`, `mc`, lakeFS). I can load multiple objects into the first bucket fine.

**Expected behavior**
Should be able to upload objects into multiple buckets via the S3 API

**Comment by dsgibbons** [comment]
This issue does not seem to replicate across machines. Let me revise this issue.

**Comment by dsgibbons** [comment]
After reading https://github-wiki-see.page/m/seaweedfs/seaweedfs/wiki/Amazon-S3-API, I think the original machine may have been running out of space without me realising. I'll try again tomorrow and reduce the volume size.

**Comment by dsgibbons** [comment]
This issue was resolved by including additional `-master.volume` options.

```yaml
seaweedfs:
    image: chrislusf/seaweedfs
    restart: always
    ports:
      - 8333:8333
    command: 'server -dir=/data -s3 -idleTimeout=30 -master.volumePreallocate=false -master.volumeSizeLimitMB=1024'
```
