### ISSUE TITLE
helm template for post install bucket hook is failing after #5081 was merged. error: no template "master.hostpath_exists" associated with template "gotpl"

### ISSUE THREAD

**Issue by jessebot** [seaweedfs/seaweedfs#5107]
## Describe the bug
When https://github.com/seaweedfs/seaweedfs/pull/5081 removed `master.hostpath_exists` and `master.existing_claims`, it wasn't removed from here:
https://github.com/seaweedfs/seaweedfs/blob/4538265412466e27dc138e3559a0ee528fd12096/k8s/charts/seaweedfs/templates/post-install-bucket-hook.yaml#L84-L85

however, it doesn't seem to be doing anything anyway...

```console
$ helm template . --name-template nextcloud-seaweedfs --namespace nextcloud --kube-version 1.27 --values /tmp/4639d6f4-1a20-47a5-9e35-288c9bf1584c --include-crds
Error: template: seaweedfs/templates/post-install-bucket-hook.yaml:84:28: 
executing "seaweedfs/templates/post-install-bucket-hook.yaml" at <include "master.hostpath_exists" .>: 
error calling include: template: no template "master.hostpath_exists" associated with template "gotpl" 
Use --debug flag to render out invalid YAML
```

**System Setup**
This is the helm chart, so I'm running k3s, and then I'm using Argo CD to deploy this chart.

The values I'm using in my [Seaweedfs Argo CD ApplicationSet for nextcloud](https://github.com/small-hack/argocd-apps/blob/main/nextcloud/storage/seaweedfs/seaweedfs_argocd_appset.yaml) to reproduce this error:
```yaml
filer:
  # this enables the filer and s3 which are both required to be deployed together
  s3:
    enabled: true
    allowEmptyFolder: false
    domainName: 's3.example.com'
    # enable user & permission to s3 (need to inject to all services)
    enableAuth: true
    existingConfigSecret: seaweedfs-s3-secret
    createBuckets:
      - name: nextcloud-data
        anonymousRead: false
      - name: nextcloud-postgres
        anonymousRead: false
```

**Expected behavior**
I'd expect the above to work as normal and deploy the post install hook for the bucket creation.

## Additional context
Can submit a PR to fix this. If I do, please merge this one first: https://github.com/seaweedfs/seaweedfs/pull/5106 so we can make sure it's working in this repo.
