### ISSUE TITLE
duplicate volume id

### ISSUE THREAD

**Issue by SmsS4** [seaweedfs/seaweedfs#5189]
**Describe the bug**
Looks like we have 3 volume with id 80704 (replication is 000) and content of these volumes are different and even one of volumes collection is different.
```
 volume id:80704 size:5350319080 collection:"logz" file_count:4654 version:3 modified_at_second:1704381595
volume id:80704 size:173786736 collection:"logz" file_count:102 version:3 modified_at_second:1704473684 
volume id:80704 size:21016624 file_count:243 version:3 modified_at_second:1704952643 
```

**System Setup**
- I had some network issues 
- Master restarted frequently
- version 30GB 3.61 8ae00e47a linux amd64
- filer.toml:
```toml
[cassandra]
enabled = true
keyspace="main_logz"
hosts=[
    "scylla.logz.svc"
]
```

How can I fix this issue?

Thanks
