### ISSUE TITLE
Upgrading from helm chart 3.60 results in error

### ISSUE THREAD

**Issue by mergwyn** [seaweedfs/seaweedfs#5263]
**Describe the bug**
Upgrading helm chart version 3.60 to 3.62 in place gives error regarding updating certain values in the statefulset
`spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden`

PR #5207  looks related and was committed on the same day as `Chart.yaml` was uplifted to 3.62.  It's not clear if `helm upgrade` is picking up this change or not.

**System Setup**
seaweedfs installed in to k3s cluster using helm
Ubuntu 22.04: Linux hotel 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
k3s version v1.28.4+k3s2 (6ba6c1b6)

Contents of values.yaml:
```
global:
  enableReplication: true
  monitoring:
    enabled: true

master:
  replicas: 1
  data:
    hostPathPrefix: /srv/seaweedfs/ssd
  logs:
    hostPathPrefix: /srv/seaweedfs/storage
  config: |-
    [master.maintenance]
    # periodically run these scripts are the same as running them from 'weed shell'
    scripts = """
      lock
      ec.encode -fullPercent=95 -quietFor=1h
      ec.rebuild -force
      ec.balance -force
      volume.balance -force
      volume.fix.replication
      unlock
    """ 
    sleep_minutes = 17

volume:
  replicas: 3
  data:
    hostPathPrefix: /srv/seaweedfs/storage
  idx:
    hostPathPrefix: /srv/seaweedfs/ssd
  logs:
    hostPathPrefix: /srv/seaweedfs/storage

filer:
  replicas: 1
  data:
    hostPathPrefix: /srv/seaweedfs/storage
  logs:
    hostPathPrefix: /srv/seaweedfs/storage
  s3:
    enabled: true
    enableAuth: true
    skipAuthSecretCreation: true
    existingConfigSecret: seaweedfs-s3-config

s3:
  enabled: true
  enableAuth: true
  skipAuthSecretCreation: true
  existingConfigSecret: seaweedfs-s3-config
  ingress:
    enabled: true
    className: "traefik"
    annotations:
      "traefik.ingress.kubernetes.io/router.entrypoints": websecure
    host: "s3.<example>.com"
    tls:
      - hosts:
        - "*.<example>.com"
  logs:
    hostPathPrefix: /srv/seaweedfs/storage
```

**Expected behavior**
Chart upgrade to work, or README to cover steps on how to achieve upgrade.

**Screenshots**
```
$ helm upgrade --install --create-namespace --namespace seaweedfs seaweedfs seaweedfs/seaweedfs --values=values.yaml
Error: UPGRADE FAILED: cannot patch "seaweedfs-s3" with kind Deployment: Deployment.apps "seaweedfs-s3" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"s3", "app.kubernetes.io/instance":"seaweedfs", "app.kubernetes.io/name":"seaweedfs", "helm.sh/chart":"seaweedfs-3.62.0"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && cannot patch "seaweedfs-filer" with kind StatefulSet: StatefulSet.apps "seaweedfs-filer" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden && cannot patch "seaweedfs-master" with kind StatefulSet: StatefulSet.apps "seaweedfs-master" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden && cannot patch "seaweedfs-volume" with kind StatefulSet: StatefulSet.apps "seaweedfs-volume" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```
