### ISSUE TITLE
Any chance to save the data?

### ISSUE THREAD

**Issue by SonGokussj4** [seaweedfs/seaweedfs#5277]
**Describe the problem**
Can I save/export my data, somewhat export them to "visible state" (readable format like jpg, png, file tree structure) that I can copy somewhere else if I by mistake deleted the "indexer" with docker compose down command?

**System Setup**
- OS version: Linux, SeaweedFS running in docker
- Version: 3.57

**Docker Compose setup**
```
seaweedfs_master:
    image: chrislusf/seaweedfs:3.57
    ports:
        - 9333
        - 19333
        - 9324
    command: "master -ip=seaweedfs_master -ip.bind=0.0.0.0 -metricsPort=9324 -volumeSizeLimitMB=8192"
    environment:
        TZ: ${TIMEZONE}

seaweedfs_volume:
    image: chrislusf/seaweedfs:3.57
    ports:
        - 8080
        - 18080
        - 9325
    command: 'volume -mserver="seaweedfs_master:9333" -ip.bind=0.0.0.0 -port=8080 -metricsPort=9325 -dir="/data/seaweedfs/volume" -max=128 -dataCenter=dc1 -rack=rack1'
    volumes:
        - ${FILESERVER_DATA_PATH}:/data/seaweedfs/volume
    depends_on:
        - seaweedfs_master
    environment:
        TZ: ${TIMEZONE}

seaweedfs_filer:
    image: chrislusf/seaweedfs:3.57
    ports:
        - 8888
        - 18888
        - 9326
        - 9000
    command: 'filer -master="seaweedfs_master:9333" -ip.bind=0.0.0.0 -metricsPort=9326 -s3 -s3.port=9000'
    tty: true
    stdin_open: true
    depends_on:
        - seaweedfs_master
        - seaweedfs_volume
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=${PROXY_NETWORK}"
        - "traefik.http.routers.${PROXY_PREFIX}-filer_console.service=${PROXY_PREFIX}-filer_console"
        - "traefik.http.routers.${PROXY_PREFIX}-filer_console.rule=(Host(`${PROXY_FILER_HOST}`))"
        - "traefik.http.services.${PROXY_PREFIX}-filer_console.loadbalancer.server.port=8888"
        - "traefik.http.routers.${PROXY_PREFIX}-filer_console.entrypoints=minio_console"
        - "traefik.http.routers.${PROXY_PREFIX}-filer.service=${PROXY_PREFIX}-filer"
        - "traefik.http.routers.${PROXY_PREFIX}-filer.rule=(Host(`${PROXY_FILER_HOST}`))"
        - "traefik.http.services.${PROXY_PREFIX}-filer.loadbalancer.server.port=9000"
        - "traefik.http.routers.${PROXY_PREFIX}-filer.entrypoints=minio"
    environment:
        TZ: ${TIMEZONE}
```

**Expected behavior**
By mistake, I've issued a command `docker compose down` instead of `docker compose stop`.
The **data** are OK, still in the storage. But when I **upped** my app, I can't see them anymore and when I open the filer, it seems to be empty...

On my docker volumes I've still got the `idx`, `dat` and `vif` files but not sure how to export them to something I can open or copy somewhere as a normal data.

**Comment by chrislusf** [comment]
The directory info is in the filer store, which seems not available any more.

From the `.dat` files, you can check `weed export -h`. It should be able to dump out the file contents. the file names may or may not be available.

**Comment by SonGokussj4** [comment]
I'm not following how to get the data. 
Even when I created a new, clean data, I've copied the whole directory to a test one and installed the `weed` command and used
```
$ for i in {1..30}; do weed export -dir=. -volumeId=${i} -o=EXPORT/output${i}.tar; done
# Or just to print:
$ for i in {1..30}; do weed export -dir=. -volumeId=${i} -o=-; done
```

The result is:
```
/buckets/models4
37"�������0���"/buckets/models2�퓋�������
/buckets/models/37��
Cat_46_055dc382c6.jpg4��� �������*YBOCrwV0mjbmTq07xE7kig==:	q�ߋ"2�������0���:
image/jpegr`��t�6�N�;�N�"/buckets/models/372�퓋�������
...
/buckets/models/37��
thumbnail_Cat_55_7304efb71c.jpg2�y ʋ�����*Nw/Ig76RGuEFU5RmsEaQlA==:     Q���"�y����0���:
image/jpegr7ȃ���S�f�F��"/buckets/models/372�퓋������������������
/buckets/models/37��
Cat_14_fec9fd83c9.jpg4Ĺ� �������*qwsYWkhC79EGtIGQWxV5uQ==:    R���"Ĺ�����0���:
image/jpegr�
            ZHB�����[y�"/buckets/models/372�퓋�������γ�
/buckets/models/37��
thumbnail_Cat_14_fec9fd83c9.jpg2�X �̼����*ddcC56XXefPTj9P4gK6PUw==:
...
```

But no data. I'm not understanding how to export them without using the filer as a web service

**Comment by jerebear12** [comment]
You can set up a Filer with an S3 gateway and use RClone to copy all files from Seaweed to a local directory. RClone can copy to a myriad of technologies if needed too.

**Comment by SonGokussj4** [comment]
I took all day today and kind of came up with a way to persist index data if I do `docker compose down`.

```yaml
seaweedfs_filer:
        image: chrislusf/seaweedfs:3.57
        ports:
            - 8888
            - 18888
            - 9326
        tty: true
        stdin_open: true
        command: 'filer -master="seaweedfs_master:9333" -ip.bind=0.0.0.0 -metricsPort=9326'
        depends_on:
            - seaweedfs_master
            - seaweedfs_volume
        volumes:
            - seaweedfs_filerldb2:/data/filerldb2  # <-- filer metadata/indexer
```

Now the images and their paths persis. Yay!

**BUT** after each `docker compose down` and `docker compose up` **3 new folders are created** -> **anonymous docker volumes**...

```sh
/var/lib/docker/volumes# tree -CL 4
.
├── 36c6add0099f2f72337c5f487408867392c0763518822fa413b391c0e1143fbc
│   └── _data
│       ├── filerldb2
│       └── seaweedfs
│           └── volume
├── 5d341543436635b781a276609cf42a320bf8b898eb11e7d86e9e55664bcded98
│   └── _data
│       ├── filerldb2
│       └── m9333
│           ├── conf
│           ├── log
│           └── snapshot
├── 672bf79835c4786e9bf3550a04d2c3fe81aeaa195ba554899741c480dd2d3cc3
│   └── _data
│       └── filerldb2
...
```

So after 3 `docker compose down/up` there are 9 new docker volumes... But only 3 are active.

when I tried to add another volume to **seaweedfs_s3** service
```yaml
seaweedfs_s3:
        image: chrislusf/seaweedfs:3.57 # 3.57_large_disk
        ports:
            - 9000
            - 9327
        command: 's3 -filer="seaweedfs_filer:8888" -port=9000 -ip.bind=0.0.0.0 -metricsPort=9327'
volumes:
            - seaweedfs_s3_data:/data/filerldb2
```

Then it creates 4 anonymous volumes each time. What is happening here.

**Comment by SonGokussj4** [comment]
> You can set up a Filer with an S3 gateway and use RClone to copy all files from Seaweed to a local directory. RClone can copy to a myriad of technologies if needed too.

I have filer setup with s3 (you can see from my first post) or do you have in mind some other configuration? Can you show me?

Thank you for the RClone tip. I'll investigate if that's usable in my case :-)

**Comment by jerebear12** [comment]
Your issue with the `docker compose down` command is it removes the containers, which detaches them from the volumes. Use `docker compose stop` to preserve your the link between your index data(aka file metadata) and your containers. See the [docker compose docs](https://docs.docker.com/engine/reference/commandline/compose_down/).

RClone is only necessary if you want to create a backup in a secondary location. I didn't fully read your post when I suggested it.

**Comment by SonGokussj4** [comment]
I appreciate your help but the problem is not that I should be using `compose stop` instead of `compose down`. 

We were using `compose stop` all the time but after a month or so `compose down` was mistakenly issued and it destroyed the connection to our data. 

And if you have correctly set up volumes to persist the data, it should not matter if you use `stop` or `down`. `down` is sometimes needed. So for now I figured the correct bind mount for the indexer data but am still confused why 3 anonymous volumes are created everytime I issue `compose up`.

**Comment by jerebear12** [comment]
> I appreciate your help but the problem is not that I should be using `compose stop` instead of `compose down`.

I see, sorry for assuming!

> We were using `compose stop` all the time but after a month or so `compose down` was mistakenly issued and it destroyed the connection to our data.

Ah, I understand. 

> And if you have correctly set up volumes to persist the data, it should not matter if you use `stop` or `down`. `down` is sometimes needed. So for now I figured the correct bind mount for the indexer data but am still confused why 3 anonymous volumes are created everytime I issue `compose up`.

These three are created on the docker compose up command. You then run docker compose down, deleting the three containers that the volumes are bound to. The three volumes are left hanging, unattached to anything. Then you run docker compose up which says "create three brand new containers with three brand new volumes for each". Now you have a total of 6 volumes with the 3 new ones attached to the 3 new containers. Does this sound right to you?

I can see the .dat files in Docker Desktop on my computer. There appears to be a way to download all the data from the volumes. Are you looking to recover your data or simply prevent this in the future?

**Comment by SonGokussj4** [comment]
I have settled on a solution but don't know if it's OK. Those dangling volumes were created because I've been mounting `/data/seaweedfs/volume` but there was still `/data/filerldb2` path so that was mounted as anonymous volume...

My solution: have all services to mount each of their `/data` internal path. And I've chosen to mount it into 1 volume, not three separated ones. Not sure if it's a great idea but it works and I don't see, for now, any performance drawback.

**My current docker-compose setup:**
```yaml
---
version: "3.8"

services:
    seaweedfs_master:
        image: chrislusf/seaweedfs:3.57
        expose:
            - 9333
            - 19333
            - 9324
        command: "master -ip=seaweedfs_master -ip.bind=0.0.0.0 -metricsPort=9324 -volumeSizeLimitMB=8192"
        environment:
            TZ: ${TIMEZONE}
        volumes:
            - fileserver:/data

    seaweedfs_volume:
        image: chrislusf/seaweedfs:3.57
        expose:
            - 8080
            - 18080
            - 9325
        command: 'volume -mserver="seaweedfs_master:9333" -ip.bind=0.0.0.0 -port=8080 -metricsPort=9325 -max=128 -dataCenter=dc1 -rack=rack1'
        environment:
            TZ: ${TIMEZONE}
        depends_on:
            - seaweedfs_master
        volumes:
            - fileserver:/data

    seaweedfs_filer:
        image: chrislusf/seaweedfs:3.57
        expose:
            - 8888
            - 18888
            - 9326
            - 9000
        command: 'filer -master="seaweedfs_master:9333" -ip.bind=0.0.0.0 -metricsPort=9326 -s3 -s3.port=9000'
        tty: true
        stdin_open: true
        environment:
            TZ: ${TIMEZONE}
        depends_on:
            - seaweedfs_master
            - seaweedfs_volume
        volumes:
            - fileserver:/data

volumes:
    fileserver:

```

The volume then contains this file structure:
```bash
/var/lib/docker/volumes/prerelease_fileserver# tree
.
└── _data
    ├── 1.dat
    ├── 1.idx
    ├── 1.vif
    ....
    ├── 7.dat
    ├── 7.idx
    ├── 7.vif
    ├── filerldb2
    │   ├── 00
    │   │   ├── 000001.log
    │   │   ├── CURRENT
    │   │   ├── LOCK
    │   │   ├── LOG
    │   │   └── MANIFEST-000000
    ....
    │   └── 07
    │       ├── 000001.log
    │       ├── CURRENT
    │       ├── LOCK
    │       ├── LOG
    │       └── MANIFEST-000000
    ├── m9333
    │   ├── conf
    │   ├── log
    │   └── snapshot
    ├── models_10.dat
    ├── models_10.idx
    ├── models_10.vif
    ...
    ├── models_9.dat
    ├── models_9.idx
    ├── models_9.vif
    └── vol_dir.uuid
```

Everything works through `compose down` and `compose up` and is saved in one volume so it's clean. Not sure about the posible performance impact of not dividing it into three volumes `sw_master`, `sw_filer`, `sw_volume` for example. Only time will tell.

Hope this helps someone. Or me in the future... :-D
