### ISSUE TITLE
Cannot reach Volume Server outside the K8s cluster

### ISSUE THREAD

**Issue by juan131** [seaweedfs/seaweedfs#5469]
**Describe the bug**

Volume Servers are ignoring `port.public` and `publicUrl` flags since the "advertised" URL by Master Server to connect to Volume Server uses the K8s internal hostnames.

**System Setup**

I deployed SeaweedFS with one master and one volume server replica using the K8s manifests below:

- Master Server manifests:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seaweedfs-master
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: master
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/component: master
  serviceName: seaweedfs-master-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seaweedfs
        app.kubernetes.io/component: master
    spec:
      containers:
        - name: seaweedfs
          image: docker.io/chrislusf/seaweedfs:latest
          args:
            - -logtostderr=true
            - -v=1
            - master
            - -mdir=/data
            - -ip.bind=0.0.0.0
            - -ip=$(POD_NAME).seaweedfs-master-headless.$(NAMESPACE).svc.cluster.local
            - -port=9333
            - -port.grpc=19333
            - -peers=seaweedfs-master-0.seaweedfs-master-headless.$(NAMESPACE).svc.cluster.local:9333
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 9333
            - name: grpc
              containerPort: 19333
          volumeMounts:
            - name: data
              mountPath: /data
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-master-headless
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: master
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 9333
      protocol: TCP
    - name: grpc
      port: 19333
      protocol: TCP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: master
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-master
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: master
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 9333
      protocol: TCP
    - name: grpc
      port: 19333
      protocol: TCP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: master
```

- Volume Server manifests (please note the use of the `-port.public=8080 -publicUrl=127.0.0.1` flags):

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seaweedfs-volume
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: volume
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/component: volume
  serviceName: seaweedfs-volume-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seaweedfs
        app.kubernetes.io/component: volume
    spec:
      containers:
        - name: seaweedfs
          image: docker.io/chrislusf/seaweedfs:latest
          args:
            - -logtostderr=true
            - -v=1
            - volume
            - -dir=/data
            - -ip.bind=0.0.0.0
            - -ip=$(POD_NAME).seaweedfs-volume-headless.$(NAMESPACE).svc.cluster.local
            - -port=8080
            - -port.grpc=18080
            - -port.public=8080
            - -publicUrl=127.0.0.1
            - -mserver=seaweedfs-master-0.seaweedfs-master-headless.$(NAMESPACE).svc.cluster.local:9333
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 18080
          volumeMounts:
            - name: data
              mountPath: /data
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-volume-headless
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: volume
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: grpc
      port: 18080
      protocol: TCP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: volume
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-volume
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: volume
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
    - name: grpc
      port: 18080
      protocol: TCP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: volume
```

Once both Master & Volume servers were ready, I forwarded the services' ports so I could access both Master & Volume servers though localhost:

```bash
kubectl port-forward svc/seaweedfs-master 9333:9333
kubectl port-forward svc/seaweedfs-master 19333:19333
kubectl port-forward svc/seaweedfs-volume 8080:8080
kubectl port-forward svc/seaweedfs-volume 18080:18080
```

Then, I tried to upload a file:

```console
$ weed upload -master=localhost:9333 testing.txt
W0404 16:45:27.270738 upload_content.go:170 uploading 0 to http://seaweedfs-volume-0.seaweedfs-volume-headless.default.svc.cluster.local:8080/5,0119607dbf?ts=1708938887: upload testing.txt 10228 bytes to http://seaweedfs-volume-0.seaweedfs-volume-headless.default.svc.cluster.local:8080/5,0119607dbf?ts=1708938887: Post "http://seaweedfs-volume-0.seaweedfs-volume-headless.default.svc.cluster.local:8080/5,0119607dbf?ts=1708938887": dial tcp: lookup seaweedfs-volume-0.seaweedfs-volume-headless.default.svc.cluster.local: no such host
```

As you can see, the CLI is trying to upload the file to Volume Server using the K8s internal hostname which cannot be resolved outside the K8s cluster.

**Expected behavior**

The advertised URL to access the Volume Server should be the one specified using `port.public` and `publicUrl` flags.
