### ISSUE TITLE
helm chart: resources should be a map

### ISSUE THREAD

**Issue by jessebot** [seaweedfs/seaweedfs#5681]
**Describe the bug**
`resources` should be maps, and not strings for the helm chart. You can verify this is the default and recommended by creating a default chart:

```console
$ helm create testing123
Creating testing123
$ cd testing123
$ grep -A 7 resources values.yaml
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
```

Here's an example in the values.yaml:
https://github.com/seaweedfs/seaweedfs/blob/d87f88418696f72a752779b6ce776d216f5e61d1/k8s/charts/seaweedfs/values.yaml#L596

And here's the corresponding template:
https://github.com/seaweedfs/seaweedfs/blob/d87f88418696f72a752779b6ce776d216f5e61d1/k8s/charts/seaweedfs/templates/filer-statefulset.yaml#L272-L275

But this is present for all of the following templates:

- templates/filer-statefulset.yaml
- templates/master-statefulset.yaml
- templates/s3-deployment.yaml
- templates/volume-statefulset.yaml

We need to fix this, and I'll submit a PR to fix that to be consistent, but also because it breaks syntax highlighting to have them be strings. See example when using the string vs a map:

```yaml
resources: |-
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

**System Setup**
This is the helm chart version pushed out with this release:
https://github.com/seaweedfs/seaweedfs/releases/tag/3.68

**Expected behavior**
Resources should be declared as mentioned above as maps `{}` instead of strings `""` or null.

```yaml
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
```
