### ISSUE TITLE
Helm: image registry handling is inconsistent

### ISSUE THREAD

**Issue by gtudan** [seaweedfs/seaweedfs#5694]
**Describe the bug**
The helm chart uses helpers to resolve the image names. They contain several mechanisms to override registry, repository, image and tags. We tried overriding the registry and stumbles inconsistencies between the different images for master/filer and volume.

**System Setup**
- Helm Chart 3.68 

**Expected behavior**
We can cleanly override the registry using the values.

**Actual behavior**

We had to override several properties (some of them undocumented) to get this working:

```yaml
  image:
    repository: /

  global:
    repository: /
    registry: myRegistry.org
    localRegistry: myRegistry.org
```

It is also not clear why there is an image and a global section. The convention is to use the global section to set values across the whole chart.
