### ISSUE TITLE
Not fetching files from S3 if not present in Volume

### ISSUE THREAD

**Issue by ankitguptag18** [seaweedfs/seaweedfs#5747]
**Describe the bug**
I have a single Master, Single Filer and a single Volume. I had setup Remote mount and was uploading the files in s3. The server having the volume crashed beyond recovery. Since I had the Gateway to Remote Object Storage setup, my assumption is that Local FS is a cache to the S3. and since cache can be volatile there should be no issue if the cache is cleared, With Actual files stored safely in S3. However to my surprise. I cannot access the files uploaded to s3 via seaweed. I am getting an error `operation LookupFileId 3,0da488208f failed, err: urls not found`. 

The file is present in both Filer UI and S3 Bucket. 

**System Setup**

Start the master, Volume and filer with below docker-compose file.
```
version: '3.9'
services:
  master:
    container_name: seaweedfs_master
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -volumeSizeLimitMB 100 -resumeState=false -ip=${systemIP} -ip.bind=0.0.0.0 -port=9333"
  volume:
    container_name: seaweedfs_volume
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="${systemIP}:9333" -ip=${systemIP} -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325'
    volumes:
      - ./volumedata:/data
    depends_on:
      - master
filer:
    container_name: seaweedfs_filer
    image: chrislusf/seaweedfs
    ports:
      - 8888:8888
      - 8333:8333
      - 18888:18888
      - 9331:9331
    command: 'filer -s3 -master="${systemIP}:9333" -ip=${systemIP} -ip.bind=0.0.0.0 -port=8888 -metricsPort=9331'
    volumes:
      - ./filerdata:/data
    depends_on:
      - master
      - volume
```
**Steps to reproduce**

1. run the following commands to enable in weed shell to Configure and mount the s3 Gateway.

```
remote.configure -name=aws -type=s3 -s3.access_key=<AWS_ACCESS_KEY> -s3.secret_key=<AWS_SECRET_KEY> -s3.region=ap-south-1 -s3.storage_class="STANDARD"
remote.mount -dir=/ -remote=aws/<BucketName>/ -nonempty
```

2. Start remote sync with following command.

```
weed filer.remote.sync -filer="${systemIP}:8888" -dir=/
```

3. Upload a file to filer.

```
curl -s -L -X POST '0.0.0.0:8888/3,0c41292627.png' \-F 'file=@"/path/to/file"'
```

4. Verify on S3 Bucket the file is getting uploaded.

5. Stop VOlume.

6. Simulate Volume Crash by clearing the volumedata in local.
```
rm -rf volumedata
```
7. Restart Volume.

8. Try to fetch the previously uploaded file.
```
curl -s -L -X GET '0.0.0.0:8888/3,0c41292627.png'
```

9. You get an 500 error. 
```
operation LookupFileId 3,0da488208f failed, err: urls not found
```
**Expected behavior**
If the file is not present in Volume, It should try and fetch the file from S3 and cache it for subsequent requests.

**Ref**

- Configure S3 as per instructions https://github.com/seaweedfs/seaweedfs/wiki/Configure-Remote-Storage
- Mount Remove Bucker as per instructions https://github.com/seaweedfs/seaweedfs/wiki/Mount-Remote-Storage

** Screenshot **

![SeaweedFiler](https://github.com/seaweedfs/seaweedfs/assets/6930289/cbded290-c5d2-4fd4-b09c-7fbe89c319e5)
![S3-Screenshot](https://github.com/seaweedfs/seaweedfs/assets/6930289/f775f197-a0a9-48a2-b9e8-c9ff3420b4de)
