### ISSUE TITLE
TLS for seaweed master and s3

### ISSUE THREAD

**Issue by Samy060** [seaweedfs/seaweedfs#5970]
We are using an OpenShift cluster to deploy SeaweedFS, and we are using HashiCorp Vault as a Certificate Authority. The Vault-Agent-Injector  is injecting the certificates into the Seaweed pods, and the Seaweed Helm chart configuration is set up accordingly. We are currently trying to inject the certificate and key at the paths specified below. I need to know the exact path where the Vault-Agent-Injector should inject these, so that SeaweedFS can utilize the certificates for TLS connections.

Values.yaml
tls:
enabled: true 
certPath: "/etc/seaweedfs/tls/server.crt" 
keyPath: "/etc/seaweedfs/tls/server.key"

This is referenced in statefulset.yaml of master and s3 as environmental variables by the name
TLS_CERT and TLS_KEY

**Comment by Material-Scientist** [comment]
[security.toml](https://github.com/seaweedfs/seaweedfs/wiki/Security-Configuration):

```
# Put this file to one of the location, with descending priority
#    ./security.toml
#    $HOME/.seaweedfs/security.toml
#    /etc/seaweedfs/security.toml

[jwt.signing]
key = "blahblahblahblah"

[jwt.filer_signing]
key = "blahblahblahblah"

# all grpc tls authentications are mutual 
[grpc]
ca = "/Users/chris/.seaweedfs/out/SeaweedFS_CA.crt"

[grpc.volume]
cert = "/Users/chris/.seaweedfs/out/volume01.crt"
key  = "/Users/chris/.seaweedfs/out/volume01.key"

[grpc.master]
cert = "/Users/chris/.seaweedfs/out/master01.crt"
key  = "/Users/chris/.seaweedfs/out/master01.key"

[grpc.filer]
cert = "/Users/chris/.seaweedfs/out/filer01.crt"
key  = "/Users/chris/.seaweedfs/out/filer01.key"

[grpc.client]
cert = "/Users/chris/.seaweedfs/out/client01.crt"
key  = "/Users/chris/.seaweedfs/out/client01.key"
```

S3 can be secured by setting a jwt token to communicate with the filer. Volume, master, filer, and client can use tls-enabled grpc.

**Comment by Samy060** [comment]
Hello
@chrislusf
@skurfuerst
@Material-Scientist
Sorry to poke you, tagging you so that may be one of you could understand the context and help me.

currently `vault-agent-injector` is injecting the certificate, key and ca.crt to path: `/etc/seaweedfs/` inside the container of master and filer.
and also, `security.toml` is injected to same path which is `/etc/seaweedfs/`

currently `security.toml` configured as below:
```
[grpc]
ca = "/etc/seaweedfs/ca.crt"

[grpc.volume]
cert = "/etc/seaweedfs/server.crt"
key = "/etc/seaweedfs/server.key"

[grpc.master]
cert = "/etc/seaweedfs/server.crt"
key = "/etc/seaweedfs/server.key"

[grpc.filer]
cert = "/etc/seaweedfs/server.crt"
key = "/etc/seaweedfs/server.key"

[grpc.client]
cert = "/etc/seaweedfs/server.crt"
key = "/etc/seaweedfs/server.key"
```
Just wanted to know, how we can validate that if the seaweedfs is using this `security.toml` configuration file for TLS.
Also please let me know if the `security.toml` configuration that I mentioned above is configured properly or not.

For your reference, this below is our master `statefulset.yaml` content
```
{{- if .Values.master.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seaweedfs-master
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: seaweedfs-master
  replicas: {{ .Values.master.replicas }}
  selector:
    matchLabels:
      app: seaweedfs-master
  template:
    metadata:
      labels:
        app: seaweedfs-master
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: "seaweedfs-role"

        # Inject security.toml without pulling from seaweedfs-secrets
        vault.hashicorp.com/agent-inject-template-security.toml: |
          [grpc]
          ca = "/etc/seaweedfs/ca.crt"

          [grpc.volume]
          cert = "/etc/seaweedfs/server.crt"
          key  = "/etc/seaweedfs/server.key"

          [grpc.master]
          cert = "/etc/seaweedfs/server.crt"
          key  = "/etc/seaweedfs/server.key"

          [grpc.filer]
          cert = "/etc/seaweedfs/server.crt"
          key  = "/etc/seaweedfs/server.key"

          [grpc.client]
          cert = "/etc/seaweedfs/server.crt"
          key  = "/etc/seaweedfs/server.key"
        vault.hashicorp.com/agent-inject-path-security.toml: "/etc/seaweedfs/security.toml"

        # Server Key Injection
        vault.hashicorp.com/agent-inject-secret-server.key: "pki/issue/vault-local"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{`{{- with secret "pki/issue/vault-local" "common_name=master.seaweedfs-system.svc.cluster.local" -}}
          {{ .Data.private_key }}
          {{- end }}`}}
        vault.hashicorp.com/agent-inject-path-server.key: "/etc/seaweedfs/server.key"

        # Server Certificate Injection
        vault.hashicorp.com/agent-inject-secret-server.crt: "pki/issue/vault-local"
        vault.hashicorp.com/agent-inject-template-server.crt: |
          {{`{{- with secret "pki/issue/vault-local" "common_name=master.seaweedfs-system.svc.cluster.local" -}}
          {{ .Data.certificate }}
          {{- end }}`}}
        vault.hashicorp.com/agent-inject-path-server.crt: "/etc/seaweedfs/server.crt"

        # CA Certificate Injection
        vault.hashicorp.com/agent-inject-secret-ca.crt: "pki/issue/vault-local"
        vault.hashicorp.com/agent-inject-template-ca.crt: |
          {{`{{- with secret "pki/issue/vault-local" "common_name=master.seaweedfs-system.svc.cluster.local" -}}
          {{ .Data.issuing_ca }}
          {{- end }}`}}
        vault.hashicorp.com/agent-inject-path-ca.crt: "/etc/seaweedfs/ca.crt"

        # Set the injection path for all secrets
        vault.hashicorp.com/secret-volume-path: "/etc/seaweedfs/"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: seaweedfs-master
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        args:
          - "master"
          - "-ip"
          - "$(POD_IP)"
          - "-mdir"
          - "/data"
          - "-volumeSizeLimitMB"
          - "100"
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TLS_CERT
          value: {{ .Values.tls.certPath }}   #/etc/seaweedfs/server.crt
        - name: TLS_KEY
          value: {{ .Values.tls.keyPath }}   #/etc/seaweedfs/server.key
        - name: TLS_CA
          value: {{ .Values.tls.caPath }}    #/etc/seaweedfs/ca.crt
        volumeMounts:
        - name: master-storage
          mountPath: /data
        ports:
        - containerPort: 9333
  volumeClaimTemplates:
  - metadata:
      name: master-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.master.storage }}
      storageClassName: {{ .Values.storageClassName }}
{{- end }}
```
