### ISSUE TITLE
Error copying files using rsync, failed to write to local disk: Volume Size Exceeded 

### ISSUE THREAD

**Issue by rensongqi** [seaweedfs/seaweedfs#6096]
**Describe the bug**
An error occurred when copying files using rsync, this error occurs very frequently when copying. The rsync process is interrupted.
copy cmd: `rsync -azuhP /disk1/AIStudiodata/dcenter/DriveData/ /mnt/AIStudiodata/dcenter/DriveData/`

`/disk1/AIStudiodata/dcenter/DriveData/` :
- file nums: `395669`
- single file size: `500MB ~ 2G`

rsync log:
![image](https://github.com/user-attachments/assets/dd3d4e89-830c-465e-bd35-cfa4e2dbc539)

Client log:
![image](https://github.com/user-attachments/assets/f0c5faeb-1f27-47e5-a909-d41448324939)

Volume log:
![image](https://github.com/user-attachments/assets/fc0b6e51-812c-4724-93ad-19a33f2c436b)

Filer log:
![image](https://github.com/user-attachments/assets/b3852c14-d8c0-4f91-8f27-294cf63d4f90)

**System Setup**

Env:
| IP| OS | Remarks |
| ---- |---- |---- |
| 172.16.90.172|Ubuntu 22.04.4 LTS | Master、Volume、Filer、S3 |
| 172.16.90.173|Ubuntu 22.04.4 LTS | Master |
| 172.16.90.174|Ubuntu 22.04.4 LTS | Master (leader now)|

Version: `3.73`

![image](https://github.com/user-attachments/assets/8417f06e-1d5c-4ded-af70-a2df2e3bdfdc)

Deployment:

- 172.16.90.172:
```yaml
version: '3.8'
services:
  seaweedfs-master:
    image: harbor.test.cn/docker.io/chrislusf/seaweedfs:latest
    container_name: seaweedfs-master
    network_mode: host
    restart: always
    volumes:
      - /data/seaweedfs/metadata:/weed/metadata:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      master 
      -mdir=/weed/metadata
      -peers=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=9333
      -metricsPort=9999
      -volumePreallocate

  seaweedfs-volume:
    image: harbor.test.cn/docker.io/chrislusf/seaweedfs:latest
    deploy:
      resources:
        limits:
          memory: 96G
    container_name: seaweedfs-volume
    network_mode: host
    restart: always
    volumes:
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /disk/local_disk1:/disk/local_disk1:rw
      - /disk/local_disk2:/disk/local_disk2:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      volume 
      -mserver=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=8080
      -dir=/disk/local_disk1,/disk/local_disk2
      -dir.idx=/weed/metadata
      -max=0,0
      -index=leveldbMedium
      -minFreeSpacePercent=5
      -metricsPort=9998
      -readBufferSizeMB=64

  seaweedfs-filer:
    image: harbor.test.cn/docker.io/chrislusf/seaweedfs:latest
    container_name: seaweedfs-filer
    network_mode: host
    restart: always
    volumes:
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /data/seaweedfs/config:/etc/seaweedfs:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      filer
      -master=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=8888
      -port.grpc=18888
      -port.readonly=28888
      -metricsPort=9997

  seaweedfs-s3:
    image: harbor.test.cn/docker.io/chrislusf/seaweedfs:latest
    container_name: seaweedfs-s3
    network_mode: host
    restart: always
    entrypoint: /usr/bin/weed
    volumes:
      - /data/seaweedfs/config:/etc/seaweedfs
    command: >
      -logtostderr=true
      s3
      -filer=172.16.90.172:8888
      -ip.bind=0.0.0.0
      -metricsPort=9996
      -config=/etc/seaweedfs/s3.json
```

- 172.16.90.173
```yaml
version: '3.8'
services:
  seaweedfs-master:
    image: harbor.test.cn/docker.io/chrislusf/seaweedfs:latest
    container_name: seaweedfs-master
    network_mode: host
    restart: always
    volumes:
      - /data/seaweedfs/metadata:/weed/metadata:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      master 
      -mdir=/weed/metadata
      -peers=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.173
      -port=9333
      -metricsPort=9999
      -volumePreallocate
```

- 172.16.90.174

```yaml
version: '3.8'
services:
  seaweedfs-master:
    image: harbor.test.cn/docker.io/chrislusf/seaweedfs:latest
    container_name: seaweedfs-master
    network_mode: host
    restart: always
    volumes:
      - /data/seaweedfs/metadata:/weed/metadata:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      master 
      -mdir=/weed/metadata
      -peers=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.174
      -port=9333
      -metricsPort=9999
      -volumePreallocate
```

Redis:
```yaml
version: '3.8'
services:
  redis:
    image: harbor.cowarobot.cn/docker.io/redis:7.4.0-alpine
    container_name: seaweedfs-redis
    ports:
      - "6379:6379"
    volumes:
      - /data/redis/data:/data
    command: redis-server --appendonly yes --requirepass xxxxxxxx
    restart: always
```

weed mount:
```bash
/usr/sbin/weed mount -filer=172.16.90.172:8888 -filer.path=/buckets/aistudiodata -dir=/mnt/AIStudiodata -cacheCapacityMB=4000 -cacheDir=/tmp -chunkSizeLimitMB=4 -volumeServerAccess=direct
```

**Expected behavior**
The file was copied successfully using rsync

**Screenshots**
![image](https://github.com/user-attachments/assets/3644d2e5-d351-4452-ace9-665ab732659b)

![image](https://github.com/user-attachments/assets/686f1acf-81a6-4a8b-b5d8-a6a715f113b7)

Master1 log:
![image](https://github.com/user-attachments/assets/943b797e-8a62-4107-a704-ac41035285dc)

Master2 log:
![image](https://github.com/user-attachments/assets/57600831-da14-407e-bc44-758d206b74b6)

Master3 log:
![image](https://github.com/user-attachments/assets/9d41100d-c9ce-4176-9401-cd6b18ccaa86)

**Additional context**
