### ISSUE TITLE
Error with Helm chart - volume's maxVolumes default value not being filled in

### ISSUE THREAD

**Issue by rschnei87** [seaweedfs/seaweedfs#6106]
According to the Helm chart, when providing a data disk for the volume component, the maxVolume line contains this comment:

"maxVolumes: 0  # If set to zero on non-windows OS, the limit will be auto configured. (**default "7"**)"

In chart version 4.0.375 this default value was filled in correctly, but with the new release 4.0.376 the default value is not filled in, causing the seaweedfs-volume-0 pod to fail because the "max" argument is filled in by the next line (-ip.bind=0.0.0.0).

**System Setup**
- Local KinD cluster
- Deploying SeaweedFS via the Helm chart, version 4.0.376

**Expected behavior**
According to the comment, if maxVolumes is not provided in your custom values.yaml file, the default should be 7.

**Failing pod information**

```
Containers:
  seaweedfs:
    Container ID:  containerd://b18c37304840b9d7db7cb653c4bd2ca62b99ec7a7c59a38ab069f7793377be5b
    Image:         chrislusf/seaweedfs:3.76
    Image ID:      docker.io/chrislusf/seaweedfs@sha256:bcfbc67c475f7acbcb028c38dc7a4b58fc2fff282a142ba043e3e3398ef39b5d
    Ports:         8080/TCP, 9327/TCP, 18080/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/sh
      -ec
      exec /usr/bin/weed \
        -logtostderr=true \
        -v=1 \
        volume \
        -port=8080 \
        -metricsPort=9327 \
        -dir /data \
        -max  \ <-------- error here, default value not filled in
        -ip.bind=0.0.0.0 \
        -readMode=proxy \
        -minFreeSpacePercent=7 \
        -ip=${POD_NAME}.${SEAWEEDFS_FULLNAME}-volume.seaweedfs \
        -compactionMBps=50 \
        -mserver=${SEAWEEDFS_FULLNAME}-master-0.${SEAWEEDFS_FULLNAME}-master.seaweedfs:9333
```

**values.yaml file snippet:**

```
volume:
  dataDirs:
   - name: data
     type: "persistentVolumeClaim"
     size: "10Gi"
     storageClass: test
```

**Additional context**
I fixed this issue by amending my values.yaml file to:

```
volume:
  dataDirs:
   - name: data
     type: "persistentVolumeClaim"
     size: "10Gi"
     storageClass: test
     maxVolumes: 4

```
Redeploying the Helm chart caused the volume pod to come up successfully.
