### ISSUE TITLE
Freed volumes are lost after restart and recurrent inconsistent state of volume services (LookupFileId)

### ISSUE THREAD

**Issue by leandroleal** [seaweedfs/seaweedfs#6121]
We are running an instance of SeaweedFS on 15 storage nodes (```g1–g15```). Almost all of them have about 200 TB of storage space (derived from 14 disks of 20 TB in RAID 5). In our setup we have 2 TB of volume size for a total 1572 volumes. We have a single master and single FilerStore (```postgres2```) running in the first node (```g1```), and all nodes have their own filer (accessing the shared ```postgres2``` FilerStore) and s3 services. To give more details about the setup files for one of the nodes (the master):

<details>
<summary>docker-compose.yml</summary>

```yaml
version: '3.3'

services:
  
  # Only g1
  master:
    image: 192.168.49.30:5000/seaweedfs-mlx-497:3.45_large_disk # use a remote image
    privileged: true
    network_mode: "host"
    cap_add:
      - IPC_LOCK
    devices:
      - "/dev/infiniband:/dev/infiniband"
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    command: "master -mdir=/master -peers=${MPEERS} -ip=${PEER} -ip.bind=0.0.0.0 -metricsPort=9324 -volumeSizeLimitMB=2000000"
    volumes:
      - /mnt/${HOSTNAME}/seaweedfs/master:/master

  # All nodes
  volume:
    image: 192.168.49.30:5000/seaweedfs-mlx-497:3.45_large_disk # use a remote image
    privileged: true
    network_mode: "host" 
    devices:
      - "/dev/infiniband:/dev/infiniband"
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    command: 'volume -rack gaia -dataCenter ${HOSTNAME} -ip ${PEER} -minFreeSpace 1 -index=leveldbLarge -max ${MAX_NVOLUMES} -mserver="${MPEERS}" -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325 -dir="/data" -dir.idx="/mdata" -readBufferSizeMB=100000 -concurrentDownloadLimitMB=30000 -concurrentUploadLimitMB=30000 -hasSlowRead=false'
    volumes:
      - /mnt/${HOSTNAME}/data:/data
      - /mnt/${HOSTNAME}/seaweedfs/mdata:/mdata
    depends_on:
      - master

  # All nodes
  filer:
    image: 192.168.49.30:5000/seaweedfs-mlx-497:3.45_large_disk # use a remote image
    privileged: true
    network_mode: "host" 
    cap_add:
      - IPC_LOCK
    devices:
      - "/dev/infiniband:/dev/infiniband"
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: 'filer -master="${MPEERS}" -filerGroup="gaia" -ip ${PEER} -ip.bind=0.0.0.0 -metricsPort=9326 -downloadMaxMBps=2000 -concurrentUploadLimitMB=30000'
    tty: true
    stdin_open: true
    volumes:
      - /mnt/${HOSTNAME}/seaweedfs/fdata:/data
      - ./conf/filer.toml:/etc/seaweedfs/filer.toml
    depends_on:
      - master
      - volume

  # Only g1
  db:
    image: postgres:14.1-alpine
    privileged: true
    network_mode: "host" 
    cap_add:
      - IPC_LOCK
    devices:
      - "/dev/infiniband:/dev/infiniband"
    restart: always
    entrypoint: docker-entrypoint.sh -c shared_buffers=8GB -c max_connections=1500 -c work_mem=16MB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<PWD>
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    shm_size: 8gb

  # All nodes
  s3:
    image: 192.168.49.30:5000/seaweedfs-mlx-497:3.45_large_disk # use a remote image
    privileged: true
    network_mode: "host"
    cap_add:
      - IPC_LOCK
    devices:
      - "/dev/infiniband:/dev/infiniband"
    ports:
      - 8333:8333
      - 9327:9327
    command: 's3 -filer="${PEER}:8888" -config=/s3.json -ip.bind=0.0.0.0 -metricsPort=9327'
    volumes:
      - ./conf/s3.json:/s3.json
    depends_on:
      - master
      - volume
      - filer

  # Only g1
  prometheus:
    image: prom/prometheus:v2.21.0
    privileged: true
    network_mode: "host"
    cap_add:
      - IPC_LOCK
    devices:
      - "/dev/infiniband:/dev/infiniband"
    ports:
      - 9000:9090
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - s3


volumes:
  db:
    driver: local

```
</details>

<details>
<summary>.env</summary>

``` bash
HOSTNAME=g1
MPEERS=192.168.49.30:9333
PEER=192.168.49.30
MAX_NVOLUMES=118
```
</details>

<details>
<summary>conf/filer.toml</summary>

```toml
[leveldb2]
enabled = false
dir = "/data/filerldb2"

[postgres2]
enabled = true
createTable = """
  CREATE TABLE IF NOT EXISTS "%s" (
    dirhash   BIGINT,
    name      VARCHAR(65535),
    directory VARCHAR(65535),
    meta      bytea,
    PRIMARY KEY (dirhash, name)
  );
"""
hostname = "192.168.49.30"
port = 5432
username = "postgres"
password = "<PWD>"
database = "postgres"          # create or use an existing database
schema = ""
sslmode = "disable"
connection_max_idle = 100
connection_max_open = 100
connection_max_lifetime_seconds = 0
enableUpsert = true
upsertQuery = """INSERT INTO "%[1]s" (dirhash,name,directory,meta) VALUES($1,$2,$3,$4) ON CONFLICT (dirhash,name) DO UPDATE SET meta = EXCLUDED.meta WHERE "%[1]s".meta != EXCLUDED.meta"""
```
</details>

We are encountering some issues that we believe are related to each other, but we do not fully understand the source of them. Summarizing:

**1)** When we delete files from any collection, we notice that the vacuum automatically starts running and some volumes are freed. However, if we restart the volume services the freed volumes are lost until the vacuum frees them again. Screenshot attached: (top) before restarting, (down) after restarting. The only way to really free storage space is apparently to delete an entire collection (which is actually pretty fast because we are using **Fast Bucket Deletion** in `postgres2`), but this is limiting and we were wondering if there is a command to actually free the space. 
- Why exactly are we losing this information when we restart the volume services? 
- Where the information of free volumes is saved?

![image](https://github.com/user-attachments/assets/27398ef1-7c96-4a64-bc74-ff05e9d6566b)

**2)** If we end up moving and/or overwriting some files, SeaweedFS gets into an inconsistent state and we can not access several files (`operation LookupFileId 8110, 4838102bbf0f5c72 failed, err: urls not found`). Check the following log saved after noticing the `LookupFileId error`. After that the only solution to get back to a consistent state is to restart all services (including volume services), but then we get to the previously mentioned issue. 
 - How should we manage file overwriting and renaming without have this `LookupFileId error`?

<details>
<summary>LookupFileId log</summary>

```
volume_1  | I1117 10:56:28.608438 store.go:170 add volume 8110
volume_1  | I1117 10:56:28.608530 volume_grpc_client_to_master.go:179 volume server 192.168.49.42:8080 adds volume 8110
volume_1  | I1117 11:11:52.689364 needle_map_leveldb.go:338 loading idx to leveldb from offset 0 for file: /mdata/tmp-icesat-ard_8104.cpx
volume_1  | I1117 11:11:52.792756 volume_vacuum.go:106 Committing volume 8104 vacuuming...
volume_1  | I1117 11:11:52.793229 needle_map_leveldb.go:338 loading idx to leveldb from offset 830 for file: /mdata/tmp-icesat-ard_8104.cpx
volume_1  | I1117 11:11:52.846522 volume_loading.go:91 readSuperBlock volume 8104 version 3
volume_1  | I1117 11:11:52.846579 volume_loading.go:184 updating leveldb large index /mdata/tmp-icesat-ard_8104.ldb
volume_1  | E1117 11:11:52.847125 volume_grpc_vacuum.go:87 failed commit volume 8104: rename /mdata/tmp-icesat-ard_8104.ldb: rename /data/tmp-icesat-ard_8104.cpldb /mdata/tmp-icesat-ard_8104.ldb: invalid cross-device link
volume_1  | I1117 11:11:53.463526 needle_map_leveldb.go:338 loading idx to leveldb from offset 0 for file: /mdata/tmp-icesat-ard_8110.cpx
volume_1  | I1117 11:11:53.547603 volume_vacuum.go:106 Committing volume 8110 vacuuming...
volume_1  | I1117 11:11:53.583763 volume_loading.go:91 readSuperBlock volume 8110 version 3
volume_1  | I1117 11:11:53.583824 volume_loading.go:184 updating leveldb large index /mdata/tmp-icesat-ard_8110.ldb
volume_1  | E1117 11:11:53.584501 volume_grpc_vacuum.go:87 failed commit volume 8110: rename /mdata/tmp-icesat-ard_8110.ldb: rename /data/tmp-icesat-ard_8110.cpldb /mdata/tmp-icesat-ard_8110.ldb: invalid cross-device link
volume_1  | panic: runtime error: invalid memory address or nil pointer dereference
volume_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1011d46]
volume_1  | 
volume_1  | goroutine 1490163 [running]:
volume_1  | github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).syncDelete(0xc000b47cc0, 0xc00011a0a8?)
volume_1  |     /github/workspace/weed/storage/volume_write.go:184 +0xc6
volume_1  | github.com/seaweedfs/seaweedfs/weed/storage.(*Volume).deleteNeedle2(0xd0?, 0x1fae?)
volume_1  |     /github/workspace/weed/storage/volume_write.go:197 +0x19
volume_1  | github.com/seaweedfs/seaweedfs/weed/storage.(*Store).DeleteVolumeNeedle(0xc0005209c0, 0x15?, 0xc0169a6000?)
volume_1  |     /github/workspace/weed/storage/store.go:405 +0x93
volume_1  | github.com/seaweedfs/seaweedfs/weed/server.(*VolumeServer).BatchDelete(0xc000427c20, {0xc000efe7d0?, 0x543a26?}, 0xc000efe7d0)
volume_1  |     /github/workspace/weed/server/volume_grpc_batch_delete.go:84 +0x8cb
volume_1  | github.com/seaweedfs/seaweedfs/weed/pb/volume_server_pb._VolumeServer_BatchDelete_Handler({0x23f0140?, 0xc000427c20}, {0x2a33910, 0xc0167c96e0}, 0xc0277eea10, 0x0)
volume_1  |     /github/workspace/weed/pb/volume_server_pb/volume_server_grpc.pb.go:895 +0x170
volume_1  | google.golang.org/grpc.(*Server).processUnaryRPC(0xc00097e1e0, {0x2a416e0, 0xc016d21520}, 0xc0003eca20, 0xc00167ac90, 0x3c5c2e0, 0x0)
volume_1  |     /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
volume_1  | google.golang.org/grpc.(*Server).handleStream(0xc00097e1e0, {0x2a416e0, 0xc016d21520}, 0xc0003eca20, 0x0)
volume_1  |     /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
volume_1  | google.golang.org/grpc.(*Server).serveStreams.func1.2()
volume_1  |     /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x98
volume_1  | created by google.golang.org/grpc.(*Server).serveStreams.func1
volume_1  |     /go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
seaweedfs_volume_1 exited with code 2
```
</details>
