### ISSUE TITLE
Using `s3.configure` to create an anonymous user breaks all other authentication, adding an anonymous user via config secret is also ignored

### ISSUE THREAD

**Issue by cloudymax** [seaweedfs/seaweedfs#6130]
**Describe the bug**
Attempting to create an anonymous user via the `s3.configure` option of `weed shell` does not work. Additionally, it causes all other access keys to become unusable until the server is restarted.

This affects both the helm-install hook in the helm chart as well as usage of `weed shell` from inside the master pod and externally. The example below shows the usage of the `weed shell` since it is easier to document than the helm job.

Adding the anonymous user via the configuration secret is also ignored:
```json
{"name":"anonymous","credentials":[{"accessKey":"","secretKey":""}],"actions":["Read:bucket-b"]}
```

# System Setup
Helm Chart Version:  4.0.377
App Version: 3.77
output of weed version: `version 30GB 3.77 b28b1a340 linux amd64`

Helm Values:
```yaml
master:
  enabled: true
  data:
    type: "persistentVolumeClaim"
    size: "10G"
    storageClass: "local-path"
    annotations:
      "k8up.io/backup": "true"
  logs:
    type: "hostPath"
    size: ""
    storageClass: ""
    hostPathPrefix: /storage
  livenessProbe:
    periodSeconds: 5
  readinessProbe:
    periodSeconds: 5

volume:
  enabled: true
  readMode: proxy
  dataDirs:
    - name: data
      type: "persistentVolumeClaim"
      size: "10G"
      storageClass: "local-path"
      annotations:
        "k8up.io/backup": "true"
      maxVolumes: 0
  idx: {}
  livenessProbe:
    periodSeconds: 5
  readinessProbe:
    periodSeconds: 5

filer:
  enabled: true
  livenessProbe:
    periodSeconds: 5
  readinessProbe:
    periodSeconds: 5
  s3:
    enabled: true
    enableAuth: true
    existingConfigSecret: my-s3-secret
    createBuckets:
      - name: bucket-a
        anonymousRead: false
      - name: bucket-b
        anonymousRead: false
  data:
    type: "persistentVolumeClaim"
    size: "10G"
    storageClass: "local-path"
    annotations:
      "k8up.io/backup": "true"

s3:
  enabled: false
cosi:
  enabled: false
```

Example Secret (tested both with and without the anonymous user)
```yaml
# Source: seaweedfs/templates/seaweedfs-s3-secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-s3-secret
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
stringData:
  # this key must be an inline json config file
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"snu8yoP6QAlY0ne4","secretKey":"PNzBcmeLNEdR0oviwm04NQAicOrDH1Km"}],"actions":["Admin","Read","Write"]},{"name":"anvReadOnly","credentials":[{"accessKey":"SCigFee6c5lbi04A","secretKey":"kgFhbT38R8WUYVtiFQ1OiSVOrYr3NKku"}],"actions":["Read"]},{"name":"anonymous","credentials":[{"accessKey":"","secretKey":""}],"actions":["Read:bucket-b"]}]}'
```

## Expected behavior
Running the following should result in `bucket-b` being public

  ```console
  s3.configure --user anonymous --buckets bucket-b --actions Read --apply true
  ```

## Observed Behavior

1. After creating the SWFS cluster with two private buckets, i am able to authenticate via AWS cli as expected using credentials from the `seaweedfs_s3_config` secret, and list files in `bucket-b`

  ```console
  kgs my-s3-secret
  AWS Access Key ID [****************""]: XXXXXXXXXXXXXXXXXXXXX
  AWS Secret Access Key [****************""]: XXXXXXXXXXXXXXXXX
  Default region name [us-east-1]:
  Default output format [json]:
  ```

  ```console
  aws --endpoint-url http://10.45.32.35:8333 s3 ls s3://bucket-b/
  2024-10-15 10:38:23     181299 rancher-suse-logo-stacked-color.png
  ```

2. After attempting to add a anonymous user with Read access to bucket-b, all authentication breaks

Adding the user:
  ```console
  > s3.configure --user anonymous --buckets bucket-b --actions Read --apply true
  {
    "identities":  [
      {
        "name":  "anonymous",
        "credentials":  [],
        "actions":  [
          "Read:bucket-b"
        ],
        "account":  null
      }
    ],
    "accounts":  []
  }
  >
  ```

No longer able to access buckets using the previously working credentials:
  ```console
  aws --endpoint-url http://10.45.32.35:8333 s3 ls s3://bucket-b/

  An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The access key ID you provided does not exist in our   records.
  ```

Filer Logs:
  ```console
  I1015 08:52:44.027900 filer_grpc_server_sub_meta.go:156 read in memory filer:10.42.0.167:8888@10.42.0.167:58028 local subscribe /   from 2024-10-15 08:52:44.026067487 +0000 UTC
  I1015 08:52:44.028190 meta_aggregator.go:82 stop subscribing peer 10.42.0.167:8888 meta change
  I1015 08:54:29.308688 auth_credentials_subscribe.go:63 updated /etc/iam/identity.json
  I1015 08:54:58.711240 auth_credentials.go:281 could not find accessKey snu8yoP6QAlY0ne4
  ```

Master Logs:
  ```console
  I1015 08:52:44.025631 master_grpc_server.go:365 + client .filer@10.42.0.167:8888
  I1015 08:52:44.025928 masterclient.go:265 + master@seaweedfs-master-0.seaweedfs-master.default:9333 noticed .filer 10.42.0.167:8888
  I1015 08:54:26.538325 master_grpc_server.go:365 + client .adminShell@d6d659f0-7528-4d57-8078-2ed637a419af
  I1015 08:54:26.541202 master_grpc_server.go:380 - client .adminShell@d6d659f0-7528-4d57-8078-2ed637a419af
  I1015 08:54:26.545033 master_grpc_server.go:365 + client .adminShell@f65c303c-3278-4e2b-943a-9a634c9011e4
  I1015 08:55:52.739651 master_grpc_server.go:380 - client .adminShell@f65c303c-3278-4e2b-943a-9a634c9011e4
  ```

Bucket is also not public, returns the following:
  ```xml
  <Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied.</Message>
  <Resource>/buckets/bucket-b/</Resource>
  <RequestId>1728982644932407486</RequestId>
  <Key>bucket-b/</Key>
  <BucketName>buckets</BucketName>
  </Error>
  ```

Restarting the pods restores authentication, still no public access though
```console
k delete pod seaweedfs-filer-0
pod "seaweedfs-filer-0" deleted

k delete pod seaweedfs-master-0
pod "seaweedfs-master-0" deleted

k delete pod seaweedfs-volume-0
pod "seaweedfs-volume-0" deleted

aws --endpoint-url http://10.45.32.35:8333 s3 ls s3://bucket-b/
2024-10-15 10:38:23     181299 rancher-suse-logo-stacked-color.png
```

**Comment by chrislusf** [comment]
Use either static config file, or `s3.configure` in `weed shell`. 
Do not mix them up.

**Comment by cloudymax** [comment]
Thanks Chris, I will test and report back with results

**Comment by cloudymax** [comment]
Perhaps I am just misunderstanding how to properly use `weed shell` and `s3.configure` though,  Could you point me to an example of how to set a bucket with public access?

Below are the results of testing using commands as outlined in the helm-charts [post-install-bucket-hook.yaml](https://github.com/seaweedfs/seaweedfs/blob/e12b9ab7460aa635e32190e9f61f37fdc7b794f6/k8s/charts/seaweedfs/templates/post-install-bucket-hook.yaml#L64), and the [weed shell wiki](https://github.com/seaweedfs/seaweedfs/wiki/weed-shell). But only with the user creation, bucket creation works fine.

## Bucket

Command:

```yaml
spec:
  containers:
  - command:
    - /bin/sh
    - -ec
    - |
      exec /bin/echo \
      s3.bucket.create --name shared2" |\
      /usr/bin/weed shell
```

Output:
```console
master: seaweedfs-master.default:9333 filer: seaweedfs-filer-client.default:8888
I1015 16:41:40.945843 masterclient.go:228 master seaweedfs-master.default:9333 redirected to leader seaweedfs-master-0.seaweedfs-master.default:9333
.create bucket under /buckets
created bucket shared2
> >
```

Result:
```console
 mc ls swfs
[2024-10-15 16:24:51 UTC]     0B shared/
[2024-10-15 16:41:41 UTC]     0B shared2/
```

## User:

Command:
```yaml
spec:
  containers:
  - command:
    - /bin/sh
    - -ec
    - |
      exec /bin/echo \
      s3.configure --user anonymous --buckets shared --actions Read --apply true" |\
      /usr/bin/weed shell
```

Output:

```console
master: seaweedfs-master.default:9333 filer: seaweedfs-filer-client.default:8888
I1015 18:18:19.178844 masterclient.go:228 master seaweedfs-master.default:9333 redirected to leader seaweedfs-master-0.seaweedfs-master.default:9333
> {
  "identities":  [
    {
      "name":  "anonymous",
      "credentials":  [],
      "actions":  [
        "Read:shared"
      ],
      "account":  null
    }
  ],
  "accounts":  []
}
> .
```

Result:
```console
mc ls swfs/shared
mc: <ERROR> Unable to list folder. The access key ID you provided does not exist in our records.
```

## Logs

```console
I1015 16:25:23.178941 masterclient.go:316 updateVidMap(DefaultDataCenter) .filer: seaweedfs-volume-0.seaweedfs-volume.default:8080 volume add: 1, del: 0, add ec: 0 del ec: 0
I1015 16:41:41.082636 auth_credentials_subscribe.go:84 updated bucketMetadata /buckets/name:"shared2"  is_directory:true  attributes:{mtime:1729010501  file_mode:2147484159  crtime:1729010501}
I1015 18:18:19.325420 auth_credentials_subscribe.go:63 updated /etc/iam/identity.json
I1015 18:18:51.425286 auth_credentials.go:281 could not find accessKey AXUAThvxC41SOhTd
I1015 18:18:51.426286 auth_credentials.go:281 could not find accessKey AXUAThvxC41SOhTd
```

**Comment by cloudymax** [comment]
I guess i just missed it while reading but I was able to achieve the desired result by adding the anonymous user to the s3 secret as described in the [AWS S3 API wiki](https://github.com/seaweedfs/seaweedfs/wiki/Amazon-S3-API#public-access-with-anonymous-download) :

```yaml
# Source: seaweedfs/templates/seaweedfs-s3-secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: my-s3-secret
  labels:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/component: s3
stringData:
  # this key must be an inline json config file
  seaweedfs_s3_config: '{"identities":[{"name":"admin","credentials":[{"accessKey":"snu8yoP6QAlY0ne4","secretKey":"PNzBcmeLNEdR0oviwm04NQAicOrDH1Km"}],"actions":["Admin","Read","Write"]},{"name":"anonymous","actions":["Read:shared"]}]}'
```

Is there a way to achieve the same result with `weed shell` after startup? Or is the conifg secret the correct method to use?
