### ISSUE TITLE
[Helm chart] Ingress returning 404

### ISSUE THREAD

**Issue by pburgisser** [seaweedfs/seaweedfs#6131]
**Describe the bug**
Seaweed has been deployed on Kubernetes using the current helm chart through ArgoCD.
The chart has been configured to deploy seaweed the S3 filer with authEnabled and the ingress route to expose the service externally.

Using S3CMD, I noticed that the S3 service is returning a 404 to any queries, below my tests and results:

- I exposed the S3 service externally to the cluster by manually updating the kubernetes service by changing the type from `ClusterIP` to `LoadBalancer` in order to confirm that my s3cmd was correctly configured. **WORKING**
- I manually changed the S3 ingress path type from `ImplementationSpecific` to `Prefix` **WORKING**

I was wondering if there is specific need to keep using the `ImplementationSpecific` ? If not, I'll be happy to submit a PR.

Thanks !

**System Setup**
- Chart version: 4.0.377
- version 30GB 3.77 b28b1a340 linux amd64
- Container image: chrislusf/seaweedfs:3.77

helm values:
```yaml
s3:
  ingress:
    enabled: true
    host: objects.10-99-115-16.nip.io
filer:
  s3:
    enabled: true
    enableAuth: true
    createBuckets:
      - name: test1
         anonymousRead: false
```

**Comment by cloudymax** [comment]
Ran into same issue, IIRC deleting the line
```
 nginx.ingress.kubernetes.io/backend-protocol: GRPC
```

Got it working for me

**Comment by pburgisser** [comment]
oooh I didn't see all those annotations in the default values file.
But I'm using cilium as the ingress, so they won't work. I guess I could try to reproduce the same configuration with my ingress controller but I'm wondering if those configuration aren't too over-engineered

**Comment by cloudymax** [comment]
just tested this minimal version and verified it worked:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/component: filer
    app.kubernetes.io/instance: seaweedfs
    app.kubernetes.io/name: seaweedfs
  name: ingress-seaweedfs-filer
spec:
  ingressClassName: nginx
  rules:
  - host: s3.buildstars.online
    http:
      paths:
      - backend:
          service:
            name: seaweedfs-filer
            port:
              number: 8888
        path: /
        pathType: Prefix
```
