### ISSUE TITLE
Volume vacuum failed

### ISSUE THREAD

**Issue by rensongqi** [seaweedfs/seaweedfs#6190]
I found an error on the Volume node: failed compact volume

Volume log:
![image](https://github.com/user-attachments/assets/de8e271e-3fe2-474c-9d10-f7405ea7e7b6)

Master log:
![image](https://github.com/user-attachments/assets/38db9d25-6eda-4c11-a17f-0138bf0f84af)

After the Master node configuration `-maxParallelVacuumPerServer=8` is still an error

![image](https://github.com/user-attachments/assets/df19474d-725d-4097-a371-29fec1db6048)

Version: `version 8000GB 3.75 117c3aebda7906433b4b83419af3acbc47f09f4d linux amd64`

docker-compose.yml
```yaml
version: '3.8'
services:
  seaweedfs-master:
    image: docker.io/chrislusf/seaweedfs:3.75_large_disk_full
    container_name: seaweedfs-master
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /data/seaweedfs/config:/etc/seaweedfs:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      master 
      -mdir=/weed/metadata
      -peers=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=9333
      -metricsPort=9999
      -volumeSizeLimitMB=1000000
      -maxParallelVacuumPerServer=8
      -volumePreallocate

  seaweedfs-volume:
    image: docker.io/chrislusf/seaweedfs:3.75_large_disk_full
    deploy:
      resources:
        limits:
          memory: 96G
    container_name: seaweedfs-volume
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /disk/local_disk1:/disk/local_disk1:rw
      - /disk/local_disk2:/disk/local_disk2:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      volume 
      -mserver=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=8080
      -dir=/disk/local_disk1,/disk/local_disk2
      -dir.idx=/weed/metadata
      -max=0,0
      -index=leveldbMedium
      -minFreeSpace=1
      -metricsPort=9998
      -readBufferSizeMB=64
      -dataCenter=SHJD
      -disk=hdd
      -rack=B07

  seaweedfs-filer:
    image: docker.io/chrislusf/seaweedfs:3.75_large_disk_full
    container_name: seaweedfs-filer
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /data/seaweedfs/config:/etc/seaweedfs:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      filer
      -master=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=8888
      -port.grpc=18888
      -port.readonly=28888
      -maxMB=64
      -ui.deleteDir=false
      -metricsPort=9997
```
