### ISSUE TITLE
Helm chart creates wrong match label selector for S3 ServiceMonitor

### ISSUE THREAD

**Issue by glycerine102** [seaweedfs/seaweedfs#6217]
**Describe the bug**
ServiceMonitor labels in the helm chart for the S3 service are created with the wrong `matchLabels`.

With S3 enabled, and the following global values set:

```yaml
global:
  monitoring:
    enabled: true
```

The helm chart sets the following selector for the S3 ServiceMonitor:

```yaml
spec:
  selector:
    matchLabels:
      app: seaweedfs
      component: s3
```

The following labels are applied to the S3 service created by the helm chart:

```yaml
  labels:
    app.kubernetes.io/component: s3
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: seaweedfs
    argocd.argoproj.io/instance: seaweedfs
    helm.sh/chart: seaweedfs-4.0.379
```

This results in the ServiceMonitor never picking up the target for metrics.

**System Setup**
- I tried the following chart versions and they were all affected
    - 4.0.377
    - 4.0.379

**Expected behavior**
The expected selector setting is below:

```yaml
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: s3
      app.kubernetes.io/name: seaweedfs
```

This would match the applied labels for the S3 service and pickup the endpoint with the name `seaweedfs`.

**Additional context**
Removing the non-fully-qualified version of the labels and adding in the fully qualified labels manually through a `kubectl edit` does allow the metrics endpoint to be picked up. I am using `IngoreDifferences` in ArgoCD to keep the manually applied labels for now.

Other servicemonitors from the helm chart are created with fully qualified labels for selectors. The following work fine:

- seaweedfs-filer
- seaweedfs-master
- seaweedfs-volume
