### ISSUE TITLE
[Helm Chart] post-install hook job exits sucessfully despite even if buckets were not created

### ISSUE THREAD

**Issue by ScribblerCoder** [seaweedfs/seaweedfs#6238]
**Describe the bug**
When `createBuckets` is specified in the values file. It triggers a helm post-install hook [post-install-bucket-hook.yaml](https://github.com/seaweedfs/seaweedfs/blob/master/k8s/charts/seaweedfs/templates/post-install-bucket-hook.yaml) that attempts to create a bucket using `weed shell`. The pod exists successfully and helm deletes the hook as specified in the manifest `"helm.sh/hook-delete-policy": hook-succeeded`. But the bucket does not get created. I suspect that the job gets executed well before master and filer pods are ready/live. Using `--wait` option with the helm install command seem to solve this issue. I'll try to debug this issue and hopefully submit a PR

**System Setup**
- Minikube v1.28.3
- Chart: v4.0.379
- AppVersion: v3.79
- values.yaml
```yaml
master:
  replicas: 1
  data:
    type: "persistentVolumeClaim"
    size: 5Gi
volume:
  replicas: 1
filer:
  replicas: 1
  enablePVC: true
  storage: 5Gi
  data:
    type: "persistentVolumeClaim"
    size: 5Gi
  s3:
    enabled: true
    enableAuth: false
    createBuckets:
      - name: hello-world
s3:
  enabled: true
  replicas: 1
  ingress:
    enabled: true
    host: seaweedfs.example.com
```

**Expected behavior**
To have the bucket appear when I run `s3.bucket.list` in weed shell.

**Screenshots**
![image](https://github.com/user-attachments/assets/313f3932-0ad4-474c-9bf0-109f2afd3217)

**Additional context**
Using `--wait` option with the helm install command seem to solve this issue. We have two issues here:
- The post-install hook does not wait for the master/filer pods to be ready
- The following command specified in the post-install hook exists successfully despite no bucket was created
``` bash
/bin/sh -ec exec /bin/echo "s3.bucket.create --name {{ $props.name }}" | /usr/bin/weed shell
```
