### ISSUE TITLE
Webdav folders creation problem.

### ISSUE THREAD

**Issue by fabiopierrisynclab** [seaweedfs/seaweedfs#6244]
**Describe the bug**
Hi,
I started the seaweedfs webdav stack with docker (docker compose is listed below) and I have problems managing folders.
My operating system is Linux Mint 22 with Cinnamon.
If I start a clean instance from docker compose and connect to the webdav server (dav://localhost:7333), I can create the first folder in the root (example: myfiles) but then it doesn't let me create any more folders. When I do "New Folder", the folder simply isn't created.

When I create the first folder, in the log I see:

```
eaweedfs-webdav  | I1117 00:42:06.350432 webdav_server.go:211 mkdir: directory:"/Cartella senza nome" entry:{is_directory:true attributes:{mtime:1731804126 file_mode:2147484159 crtime:1731804126}} signatures:-695424507
seaweedfs-webdav  | I1117 00:42:11.501645 filer_grpc_server_rename.go:17 AtomicRenameEntry old_directory:"/" old_name:"Cartella senza nome" new_directory:"/" new_name:"myfiles"
seaweedfs-webdav  | I1117 00:42:11.501680 filer_grpc_server_rename.go:157 moving entry /Cartella senza nome => /myfiles
seaweedfs-webdav  | I1117 00:42:11.501729 filer_grpc_server_rename.go:125 moving folder /Cartella senza nome => /myfiles
```

when i try to create more folders the logs say:
```
seaweedfs-webdav  | I1117 00:48:47.275704 webdav_server.go:211 mkdir: directory:"/Cartella senza nome" entry:{is_directory:true attributes:{mtime:1731804527 file_mode:2147484159 crtime:1731804527}} signatures:-695424507
```
but the folder is not created

the same happens if I try to create the folder from the terminal and not from the nemo graphical interface.

Note: after I created the first folder, a "topic" folder appears in the root

Am I doing something wrong in my webdav configuration?
Do I need to change anything in docker compose?

Thanks a lot for the support

**System Setup**
```
services:

  seaweedfs-master:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-master
    ports:
      - "9333:9333"
      - "19333:19333"
    command: "master -ip=seaweedfs-master -volumeSizeLimitMB=1024 -defaultReplication=000"
    volumes:
      - ./master_data:/data
    networks:
      - weed

  seaweedfs-volume:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-volume
    ports:
      - "8080:8080"
      - "18080:18080"
    volumes:
      - ./vol1:/data
    command: "volume -dir=/data -mserver=seaweedfs-master:9333 -port=8080 -ip=seaweedfs-volume -max=0 -preStopSeconds=1"
    networks:
      - weed
    depends_on:
      - seaweedfs-master

  seaweedfs-webdav:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-webdav
    ports:
      - "8888:8888"
      - "18888:18888"
      - "7333:7333"
    volumes:
      - ./filer_data:/data
    command: '-v 1 filer -master=seaweedfs-master:9333 -webdav'
    networks:
      - weed
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume

networks:
  weed:
    name: weed
    driver: bridge
```

**Expected behavior**
Seaweedfs allows you to create folders and subfolders from the root directory in webdav mode
