### ISSUE TITLE
elastic7 not work: failed to parse field [Entry.Inode]

### ISSUE THREAD

**Issue by rensongqi** [seaweedfs/seaweedfs#6265]
Hi, I have three Filer nodes and use redis store. Due to the large amount of data, redis takes up too much memory(100 million pieces of metadata, used 60GB memory), so I want to change the redis to elastic7. There are many error logs after the new filer node is started, and elastic7 does not automatically synchronize metadata from other filers. by the wey, which store is recommended in this case, thanks.

new filer logs:
![img_v3_02gr_8a9b7806-29d1-4886-b3fc-0693466243fg](https://github.com/user-attachments/assets/1692d5d4-566c-4b94-90a2-85da68512c8b)
```
E1121 14:56:53.130499 meta_aggregator.go:142 failed to reply metadata change from [172.16.90.174:8888](http://172.16.90.174:8888/): insert entry elastic: Error 400 (Bad Request): failed to parse field [Entry.Inode] of type [long] in document with id 'afe6f91cbff8f5bac0271c07c2645e78'. Preview of field's value: '12675092167246370946' [type=mapper_parsing_exception].
E1121 14:56:53.136077 elastic_store.go:126 insert entry(/buckets/deepdata/dataset/prediction/feature_mtr_manual_route_0308/feature/train/20240110155528/feature/bin/.feature_1704879300690056526_185.bin.HJIBUV) elastic: Error 400 (Bad Request): failed to parse field [Entry.Inode] of type [long] in document with id 'afe6f91cbff8f5bac0271c07c2645e78'. Preview of field's value: '12675092167246370946' [type=mapper_parsing_exception].
```

The `Inode` field type should be `unsigned_long`?
![img_v3_02gr_6a09ebfc-a92b-4f64-9032-17125bc064bg](https://github.com/user-attachments/assets/43bb38f0-549c-4abe-872a-95d97c44f9b3)

filer.toml
```
[elastic7]
enabled = false
servers = [
    "http://172.16.90.175:9200/",
]
sniff_enabled = false
healthcheck_enabled = false
index.max_result_window = 10000
```

weed version: `version 8000GB 3.80 7b3c0e937 linux amd64`
es version: `7.10.1`

deploy:
```yaml
version: '3.8'
services:
  es:
    image: elasticsearch:7.10.1
    container_name: seaweedfs-es
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms10000m -Xmx10000m"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./data:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
  seaweedfs-filer-new:
    image: docker.io/chrislusf/seaweedfs:3.80_large_disk_full
    container_name: seaweedfs-filer-new
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./filer.toml:/etc/seaweedfs/filer.toml
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      filer
      -master=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip.bind=0.0.0.0
      -port=8888
      -port.grpc=18888
      -port.readonly=28888
      -maxMB=64
      -ui.deleteDir=false
      -metricsPort=9995
```
