### ISSUE TITLE
Read dir err:  redis i/o timeout, Input/output error

### ISSUE THREAD

**Issue by rensongqi** [seaweedfs/seaweedfs#6301]
Hi, I used the weed shell to exec `fs.meta.save` and found an error accessing `redis i/o timeout`, after weed mount, exec `ls` to check the dir error: `Input/output error`. There are three Filer nodes, each of which corresponds to a separate redis node. 

![img_v3_02h3_a2496214-4c3c-45cf-949c-705df74c5b3g](https://github.com/user-attachments/assets/055241f3-69ce-4273-b0e6-45673523f230)

fs.du will timeout for about 12s.

![img_v3_02h3_f204de14-69c6-427c-8f95-b80537f9c8ag](https://github.com/user-attachments/assets/e1afe0c7-930d-4c7c-bd45-c63537c3d00e)

`/buckets/upload/archive_data/deepdata/code/tianzerong/tail_light/tail_recog_data_online/extract/preview_3` may have about 7 million files, does it have to do with the number of files?

client log
![img_v3_02h3_400441ac-876e-4edc-94b4-b9185fe5d93g](https://github.com/user-attachments/assets/120ddda7-2efd-4f87-ab42-1bc1ad83ef65)

Version: `version 8000GB 3.80 7b3c0e937 linux amd64'`

OS: `ubuntu22.04`

redis docker-compose.yml
```yaml
version: '3.8'
services:
  redis:
    image: docker.io/redis:7.4.0-alpine
    container_name: seaweedfs-redis
    ports:
      - "6379:6379"
    volumes:
      - /data/redis/data:/data
    command: redis-server --appendonly yes --requirepass xxxxx
    restart: always
```

seaweedfs docker-compose.yml
```yaml
version: '3.8'
services:
  seaweedfs-master:
    image: docker.io/chrislusf/seaweedfs:3.80_large_disk_full
    container_name: seaweedfs-master
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /data/seaweedfs/config:/etc/seaweedfs:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      master 
      -mdir=/weed/metadata
      -peers=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=9333
      -metricsPort=9999
      -volumeSizeLimitMB=1000000
      -maxParallelVacuumPerServer=8
      -volumePreallocate

  seaweedfs-volume:
    image: docker.io/chrislusf/seaweedfs:3.80_large_disk_full
    deploy:
      resources:
        limits:
          memory: 96G
    container_name: seaweedfs-volume
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /disk/local_disk1:/disk/local_disk1:rw
      - /disk/local_disk2:/disk/local_disk2:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      volume 
      -mserver=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=8080
      -dir=/disk/local_disk1,/disk/local_disk2
      -dir.idx=/weed/metadata
      -max=0,0
      -index=leveldbMedium
      -minFreeSpace=1
      -metricsPort=9998
      -readBufferSizeMB=64
      -dataCenter=SHJD
      -disk=hdd
      -rack=B07

  seaweedfs-filer:
    image: docker.io/chrislusf/seaweedfs:3.80_large_disk_full
    container_name: seaweedfs-filer
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /data/seaweedfs/config:/etc/seaweedfs:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      filer
      -master=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=8888
      -port.grpc=18888
      -port.readonly=28888
      -maxMB=64
      -ui.deleteDir=false
      -metricsPort=9997
```
