### ISSUE TITLE
volume generates a lot of trash

### ISSUE THREAD

**Issue by rensongqi** [seaweedfs/seaweedfs#6420]
Hi, I recently found that a lot of trash is generated when writing data to a newly created volume. What might this be related to?
Since there are too many volumes, manually executing the `weed compact` command does not seem to be a wise choice. Is there any other solution?

![image](https://github.com/user-attachments/assets/3160750b-ec49-4d23-8fe8-ac86f1b5a570)

volume log, failed compact volume.
![img_v3_02ib_2dd8065c-f455-4873-ae29-671b2098adbg](https://github.com/user-attachments/assets/ab0f1b70-e742-4b80-9b02-5d52b458d164)

Version: `version 8000GB 3.80 7b3c0e937 linux amd64'`

OS: `ubuntu22.04`

seaweedfs docker-compose.yml
```yaml
version: '3.8'
services:
  seaweedfs-master:
    image: docker.io/chrislusf/seaweedfs:3.80_large_disk_full
    container_name: seaweedfs-master
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /data/seaweedfs/config:/etc/seaweedfs:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      master 
      -mdir=/weed/metadata
      -peers=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=9333
      -metricsPort=9999
      -volumeSizeLimitMB=1000000
      -maxParallelVacuumPerServer=8
      -volumePreallocate

  seaweedfs-volume:
    image: docker.io/chrislusf/seaweedfs:3.80_large_disk_full
    deploy:
      resources:
        limits:
          memory: 96G
    container_name: seaweedfs-volume
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /disk/local_disk1:/disk/local_disk1:rw
      - /disk/local_disk2:/disk/local_disk2:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      volume 
      -mserver=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=8080
      -dir=/disk/local_disk1,/disk/local_disk2
      -dir.idx=/weed/metadata
      -max=0,0
      -index=leveldbMedium
      -minFreeSpace=1
      -metricsPort=9998
      -readBufferSizeMB=64
      -dataCenter=SHJD
      -disk=hdd
      -rack=B07

  seaweedfs-filer:
    image: docker.io/chrislusf/seaweedfs:3.80_large_disk_full
    container_name: seaweedfs-filer
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/seaweedfs/metadata:/weed/metadata:rw
      - /data/seaweedfs/config:/etc/seaweedfs:rw
    entrypoint: /usr/bin/weed
    command: >
      -logtostderr=true
      filer
      -master=172.16.90.172:9333,172.16.90.173:9333,172.16.90.174:9333
      -ip=172.16.90.172
      -port=8888
      -port.grpc=18888
      -port.readonly=28888
      -maxMB=64
      -ui.deleteDir=false
      -metricsPort=9997
```
