### ISSUE TITLE
The same volumeid in different  collection.

### ISSUE THREAD

**Issue by hereTac** [seaweedfs/seaweedfs#6431]
I start the seaweedfs in docker  compose.
```
[root@dc-coach-2 ~]# cat /opt/juicefsonseaweedfs/juicefs-seaweedfs-compose.yml 
services:
  master:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 9333:9333
      - 19333:19333
      - 9224:9224
    container_name: seaweedfs-master
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://0.0.0.0:9333 || exit 1"
      interval: 20s
      timeout: 20s
      retries: 1
    command: "master -ip=10.0.1.32 -ip.bind=0.0.0.0 -metricsPort=9224 -volumeSizeLimitMB=128 defaultReplication=001"
    restart: unless-stopped
  volume1:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8081:8081
      - 18081:18081
      - 9225:9225
    container_name: seaweedfs-volume1
    volumes:
      - /data1:/data1
    command: 'volume -dir=/data1 -mserver="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -port=8081 -metricsPort=9225'
    depends_on:
      master:
        condition: service_healthy
  volume2:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8082:8082
      - 18082:18082
      - 9226:9226
    container_name: seaweedfs-volume2
    volumes:
      - /data2:/data2
    command: 'volume -dir=/data2 -mserver="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -port=8082 -metricsPort=9226'
    depends_on:
      master:
        condition: service_healthy
  volume3:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8083:8083
      - 18083:18083
      - 9227:9227
    container_name: seaweedfs-volume3
    volumes:
      - /data3:/data3
    command: 'volume -dir=/data3 -mserver="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -port=8083 -metricsPort=9227'
    depends_on:
      master:
        condition: service_healthy
  volume4:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8084:8084
      - 18084:18084
      - 9228:9228
    container_name: seaweedfs-volume4
    volumes:
      - /data4:/data4
    command: 'volume -dir=/data4 -mserver="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -port=8084 -metricsPort=9228'
    depends_on:
      master:
        condition: service_healthy
  volume5:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8085:8085
      - 18085:18085
      - 9229:9229
    container_name: seaweedfs-volume5
    volumes:
      - /data5:/data5
    command: 'volume -dir=/data5 -mserver="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -port=8085 -metricsPort=9229'
    depends_on:
      master:
        condition: service_healthy
  volume6:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8086:8086
      - 18086:18086
      - 9230:9230
    container_name: seaweedfs-volume6
    volumes:
      - /data6:/data6
    command: 'volume -dir=/data6 -mserver="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -port=8086 -metricsPort=9230'
    depends_on:
      master:
        condition: service_healthy
  volume7:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8087:8087
      - 18087:18087
      - 9231:9231
    container_name: seaweedfs-volume7
    volumes:
      - /data7:/data7
    command: 'volume -dir=/data7 -mserver="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -port=8087 -metricsPort=9231'
    depends_on:
      master:
        condition: service_healthy
  volume8:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8088:8088
      - 18088:18088
      - 9232:9232
    container_name: seaweedfs-volume8
    volumes:
      - /data8:/data8
    command: 'volume -dir=/data8 -mserver="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -port=8088 -metricsPort=9232'
    depends_on:
      master:
        condition: service_healthy
  volume9:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8089:8089
      - 18089:18089
      - 9233:9233
    container_name: seaweedfs-volume9
    volumes:
      - /data9:/data9
    command: 'volume -dir=/data9 -mserver="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -port=8089 -metricsPort=9233'
    depends_on:
      master:
        condition: service_healthy
  volume10:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8090:8090
      - 18090:18090
      - 9234:9234
    container_name: seaweedfs-volume10
    volumes:
      - /data10:/data10
    command: 'volume -dir=/data10 -mserver="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -port=8090 -metricsPort=9234'
    depends_on:
      master:
        condition: service_healthy
  volume11:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8091:8091
      - 18091:18091
      - 9235:9235
    container_name: seaweedfs-volume11
    volumes:
      - /data11:/data11
    command: 'volume -dir=/data11 -mserver="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -port=8091 -metricsPort=9235'
    depends_on:
      master:
        condition: service_healthy

  filer:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8888:8888
      - 18888:18888
      - 9236:9236
    container_name: seaweedfs-filer
    command: 'filer -master="master:9333" -ip=10.0.1.32 -ip.bind=0.0.0.0 -metricsPort=9236 -disableDirListing'
    tty: true
    stdin_open: true
    volumes:
      - /opt/juicefsonseaweedfs/seaweedfs-leveldb:/data/filerldb2
    depends_on:
      - master
      - volume1
      - volume2
      - volume3
      - volume4
      - volume5
      - volume6
      - volume7
      - volume8
      - volume9
      - volume10
      - volume11
  s3:
    image: mirrorhub.swdcmg.com/library/chrislusf/seaweedfs:3.80 
    ports:
      - 8333:8333
      - 9237:9237
    container_name: seaweedfs-s3
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9237'
    depends_on:
      - filer
  prometheus:
    image: mirrorhub.swdcmg.com/library/prom/prometheus:v3.0.1
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
    container_name: seaweedfs-prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - s3
  redis:
    image: mirrorhub.swdcmg.com/library/redis:8.0-M01-bookworm
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf/redis.conf:/etc/redis.conf
      - ./redis/db:/data
    container_name: juicefs-redis
    command: '/bin/sh -c "redis-server /etc/redis.conf"'
    privileged: true
```
The volumeid 1 belong two different collections, I do not know how to reproduce, it just exist. 
```
[root@dc-coach-2 ~]# /opt/juicefsonseaweedfs/bin/weed shell -master=10.0.1.32:9333
master: 10.0.1.32:9333 filer: 
...master: 10.0.1.32:9333 filers: [10.0.1.32:8888]
> volume.list -volumeId 1
Topology volumeSizeLimit:128 MB hdd(volume:88459/287674 active:25810 free:199215 remote:0)
  DataCenter DefaultDataCenter hdd(volume:88459/287674 active:25810 free:199215 remote:0)
    Rack DefaultRack hdd(volume:88459/287674 active:25810 free:199215 remote:0)
      DataNode 10.0.1.32:8081 hdd(volume:8139/26158 active:2475 free:18019 remote:0)
        Disk hdd(volume:8139/26158 active:2475 free:18019 remote:0)
        Disk hdd total size:0 file_count:0 
      DataNode 10.0.1.32:8081 total size:0 file_count:0 
      DataNode 10.0.1.32:8082 hdd(volume:8021/26137 active:2357 free:18116 remote:0)
        Disk hdd(volume:8021/26137 active:2357 free:18116 remote:0)
          volume id:1  size:135098624  collection:"s3jfs"  file_count:166  delete_count:8  deleted_byte_count:17984671  replica_placement:1  version:3  compact_revision:1  modified_at_second:1736719827 
        Disk hdd total size:135098624 file_count:166 deleted_file:8 deleted_bytes:17984671 
      DataNode 10.0.1.32:8082 total size:135098624 file_count:166 deleted_file:8 deleted_bytes:17984671 
      DataNode 10.0.1.32:8083 hdd(volume:8139/26219 active:2382 free:18080 remote:0)
        Disk hdd(volume:8139/26219 active:2382 free:18080 remote:0)
        Disk hdd total size:0 file_count:0 
      DataNode 10.0.1.32:8083 total size:0 file_count:0 
      DataNode 10.0.1.32:8084 hdd(volume:8072/26138 active:2340 free:18066 remote:0)
        Disk hdd(volume:8072/26138 active:2340 free:18066 remote:0)
        Disk hdd total size:0 file_count:0 
      DataNode 10.0.1.32:8084 total size:0 file_count:0 
      DataNode 10.0.1.32:8085 hdd(volume:8240/26303 active:2455 free:18063 remote:0)
        Disk hdd(volume:8240/26303 active:2455 free:18063 remote:0)
        Disk hdd total size:0 file_count:0 
      DataNode 10.0.1.32:8085 total size:0 file_count:0 
      DataNode 10.0.1.32:8086 hdd(volume:8107/26315 active:2367 free:18208 remote:0)
        Disk hdd(volume:8107/26315 active:2367 free:18208 remote:0)
          volume id:1  size:119658040  collection:"s3jfs"  file_count:156  delete_count:6  deleted_byte_count:15608328  replica_placement:1  version:3  compact_revision:1  modified_at_second:1736669039 
        Disk hdd total size:119658040 file_count:156 deleted_file:6 deleted_bytes:15608328 
      DataNode 10.0.1.32:8086 total size:119658040 file_count:156 deleted_file:6 deleted_bytes:15608328 
      DataNode 10.0.1.32:8087 hdd(volume:8002/26141 active:2382 free:18139 remote:0)
        Disk hdd(volume:8002/26141 active:2382 free:18139 remote:0)
        Disk hdd total size:0 file_count:0 
      DataNode 10.0.1.32:8087 total size:0 file_count:0 
      DataNode 10.0.1.32:8088 hdd(volume:8159/26264 active:2302 free:18105 remote:0)
        Disk hdd(volume:8159/26264 active:2302 free:18105 remote:0)
          volume id:1  size:166023728  file_count:82  delete_count:6  deleted_byte_count:15090442  replica_placement:1  version:3  modified_at_second:1736719828 
        Disk hdd total size:166023728 file_count:82 deleted_file:6 deleted_bytes:15090442 
      DataNode 10.0.1.32:8088 total size:166023728 file_count:82 deleted_file:6 deleted_bytes:15090442 
      DataNode 10.0.1.32:8089 hdd(volume:8109/26294 active:2270 free:18185 remote:0)
        Disk hdd(volume:8109/26294 active:2270 free:18185 remote:0)
        Disk hdd total size:0 file_count:0 
      DataNode 10.0.1.32:8089 total size:0 file_count:0 
      DataNode 10.0.1.32:8090 hdd(volume:8063/26018 active:2556 free:17955 remote:0)
        Disk hdd(volume:8063/26018 active:2556 free:17955 remote:0)
        Disk hdd total size:0 file_count:0 
      DataNode 10.0.1.32:8090 total size:0 file_count:0 
      DataNode 10.0.1.32:8091 hdd(volume:7408/25687 active:1924 free:18279 remote:0)
        Disk hdd(volume:7408/25687 active:1924 free:18279 remote:0)
          volume id:1  size:166023728  file_count:82  delete_count:6  deleted_byte_count:15090442  replica_placement:1  version:3  modified_at_second:1736719829 
        Disk hdd total size:166023728 file_count:82 deleted_file:6 deleted_bytes:15090442 
      DataNode 10.0.1.32:8091 total size:166023728 file_count:82 deleted_file:6 deleted_bytes:15090442 
    Rack DefaultRack total size:586804120 file_count:486 deleted_file:26 deleted_bytes:63773883 
  DataCenter DefaultDataCenter total size:586804120 file_count:486 deleted_file:26 deleted_bytes:63773883 
total size:586804120 file_count:486 deleted_file:26 deleted_bytes:63773883 
>  volume.check.disk -volumeId 1
Running in simulation mode. Use "-force" option to apply the changes.
volume 1 10.0.1.32:8086 has 164 entries, 10.0.1.32:8082 missed 0 and partially deleted 0 entries
volume 1 10.0.1.32:8082 has 166 entries, 10.0.1.32:8086 missed 0 and partially deleted 0 entries
volume 1 10.0.1.32:8088 has 82 entries, 10.0.1.32:8082 missed 63 and partially deleted 0 entries
volume 1 10.0.1.32:8082 has 166 entries, 10.0.1.32:8088 missed 145 and partially deleted 0 entries
sync volume 1 on 10.0.1.32:8082 and 10.0.1.32:8088: doVolumeCheckDisk source:10.0.1.32:8088 target:10.0.1.32:8082 volume 1: failed to start repair volume 1, percentage of missing keys is greater than the threshold: 0.77 > 0.30
volume 1 10.0.1.32:8091 has 82 entries, 10.0.1.32:8082 missed 63 and partially deleted 0 entries
volume 1 10.0.1.32:8082 has 166 entries, 10.0.1.32:8091 missed 145 and partially deleted 0 entries
sync volume 1 on 10.0.1.32:8082 and 10.0.1.32:8091: doVolumeCheckDisk source:10.0.1.32:8091 target:10.0.1.32:8082 volume 1: failed to start repair volume 1, percentage of missing keys is greater than the threshold: 0.77 > 0.30
```
How to fix this volume? Any solution? Maybe same as https://github.com/seaweedfs/seaweedfs/issues/6232 https://github.com/seaweedfs/seaweedfs/issues/2823 https://github.com/seaweedfs/seaweedfs/issues/2754
