### ISSUE TITLE
S3 signing does not work behind proxy

### ISSUE THREAD

**Issue by tcrasset** [seaweedfs/seaweedfs#6511]
~~When using `aws s3 cp`, it all works fine.~~

But when using Python's `boto3` (specifically `fsspec`, which uses `s3fs`, which in turn uses `aiobotocore`), I get

```
PermissionError: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

This is due to the host not being the same on the client side vs the server side (behind the proxy).

Looking at the `extractedSignedHeaders` from https://github.com/seaweedfs/seaweedfs/blob/68f547bdf2bbb4f96d3a74e6b7038de728262afb/weed/s3api/auth_signature_v4.go#L685,

We have the following headers when NOT behind proxy (it works)

```
s3-1     | I0205 16:10:34.001302 auth_signature_v4.go:127 extractedSignedHeaders map[Host:[localhost:8333] X-Amz-Checksum-Crc32:[KjmyoQ==] X-Amz-Content-Sha256:[19e37ffdce0dfc9f2496ece0c0cee3b48f9a3217460921e15f8920e53e1047d4] X-Amz-Date:[20250205T161033Z] X-Amz-Sdk-Checksum-Algorithm:[CRC32]]
```

and the following when in front of the Proxy (does NOT work):

```
s3-1     | I0205 16:10:18.602920 auth_signature_v4.go:127 extractedSignedHeaders map[Host:[localhost] X-Amz-Checksum-Crc32:[KjmyoQ==] X-Amz-Content-Sha256:[19e37ffdce0dfc9f2496ece0c0cee3b48f9a3217460921e15f8920e53e1047d4] X-Amz-Date:[20250205T161018Z] X-Amz-Sdk-Checksum-Algorithm:[CRC32]]

```

See `localhost:8333` vs `localhost`.

More logs when it does not work:

```
s3-1     | I0205 16:10:18.602827 auth_signature_v4.go:45 reqSignatureV4Verify &{PUT /93d66fe4-4043-4c04-81be-8692bf13eea5/bfdfca91-2e61-4c23-87fa-15e987c9002e/93d66fe4-4043-4c04-81be-8692bf13eea5/input/iris.csv HTTP/1.0 1 0 map[Accept:[*/*] Accept-Encoding:[identity] Amz-Sdk-Invocation-Id:[4d35265d-fd39-4469-954f-a1a2061ddabd] Amz-Sdk-Request:[attempt=1] Authorization:[AWS4-HMAC-SHA256 Credential=power_user_key/20250205/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-checksum-crc32;x-amz-content-sha256;x-amz-date;x-amz-sdk-checksum-algorithm, Signature=db63e18f1bffb8a256d3a6256ab862bf238fac7e8bd8b885c6a9ba4cdb642e18] Connection:[close] Content-Length:[3976] User-Agent:[aiobotocore/2.19.0 md/Botocore#1.36.3 ua/2.0 os/linux#6.8.0-51-generic md/arch#x86_64 lang/python#3.12.7 md/pyimpl#CPython cfg/retry-mode#legacy botocore/1.36.3] X-Amz-Checksum-Crc32:[KjmyoQ==] X-Amz-Content-Sha256:[19e37ffdce0dfc9f2496ece0c0cee3b48f9a3217460921e15f8920e53e1047d4] X-Amz-Date:[20250205T161018Z] X-Amz-Sdk-Checksum-Algorithm:[CRC32] X-Forwarded-For:[172.28.0.1] X-Forwarded-Proto:[http] X-Real-Ip:[172.28.0.1]] 0xc000918680 <nil> 3976 [] true localhost map[] map[] <nil> map[] 172.28.0.11:55748 /93d66fe4-4043-4c04-81be-8692bf13eea5/bfdfca91-2e61-4c23-87fa-15e987c9002e/93d66fe4-4043-4c04-81be-8692bf13eea5/input/iris.csv <nil> <nil> <nil>  0xc000a0d620 <nil> [] map[]}+
s3-1     | I0205 16:10:18.602865 auth_signature_v4.go:47 sha256sum 19e37ffdce0dfc9f2496ece0c0cee3b48f9a3217460921e15f8920e53e1047d4
s3-1     | I0205 16:10:18.602870 auth_signature_v4.go:48 reqSignatureV4Verify /93d66fe4-4043-4c04-81be-8692bf13eea5/bfdfca91-2e61-4c23-87fa-15e987c9002e/93d66fe4-4043-4c04-81be-8692bf13eea5/input/iris.csv
s3-1     | I0205 16:10:18.602874 auth_signature_v4.go:50 prefix /
s3-1     | I0205 16:10:18.602876 auth_signature_v4.go:52 headers auth AWS4-HMAC-SHA256 Credential=power_user_key/20250205/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-checksum-crc32;x-amz-content-sha256;x-amz-date;x-amz-sdk-checksum-algorithm, Signature=db63e18f1bffb8a256d3a6256ab862bf238fac7e8bd8b885c6a9ba4cdb642e18
s3-1     | I0205 16:10:18.602881 auth_signature_v4.go:53 headers map[Accept:[*/*] Accept-Encoding:[identity] Amz-Sdk-Invocation-Id:[4d35265d-fd39-4469-954f-a1a2061ddabd] Amz-Sdk-Request:[attempt=1] Authorization:[AWS4-HMAC-SHA256 Credential=power_user_key/20250205/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-checksum-crc32;x-amz-content-sha256;x-amz-date;x-amz-sdk-checksum-algorithm, Signature=db63e18f1bffb8a256d3a6256ab862bf238fac7e8bd8b885c6a9ba4cdb642e18] Connection:[close] Content-Length:[3976] User-Agent:[aiobotocore/2.19.0 md/Botocore#1.36.3 ua/2.0 os/linux#6.8.0-51-generic md/arch#x86_64 lang/python#3.12.7 md/pyimpl#CPython cfg/retry-mode#legacy botocore/1.36.3] X-Amz-Checksum-Crc32:[KjmyoQ==] X-Amz-Content-Sha256:[19e37ffdce0dfc9f2496ece0c0cee3b48f9a3217460921e15f8920e53e1047d4] X-Amz-Date:[20250205T161018Z] X-Amz-Sdk-Checksum-Algorithm:[CRC32] X-Forwarded-For:[172.28.0.1] X-Forwarded-Proto:[http] X-Real-Ip:[172.28.0.1]]
s3-1     | I0205 16:10:18.602895 auth_signature_v4.go:54 isRequestSignatureV4(r) true
s3-1     | I0205 16:10:18.602905 auth_signature_v4.go:119 parseSignV4(v4Auth) {{power_user_key {{0 63874310400 <nil>} us-east-1 s3 aws4_request}} [host x-amz-checksum-crc32 x-amz-content-sha256 x-amz-date x-amz-sdk-checksum-algorithm] db63e18f1bffb8a256d3a6256ab862bf238fac7e8bd8b885c6a9ba4cdb642e18}
s3-1     | I0205 16:10:18.602920 auth_signature_v4.go:127 extractedSignedHeaders map[Host:[localhost] X-Amz-Checksum-Crc32:[KjmyoQ==] X-Amz-Content-Sha256:[19e37ffdce0dfc9f2496ece0c0cee3b48f9a3217460921e15f8920e53e1047d4] X-Amz-Date:[20250205T161018Z] X-Amz-Sdk-Checksum-Algorithm:[CRC32]]
s3-1     | I0205 16:10:18.602931 auth_signature_v4.go:166 hashedPayload 19e37ffdce0dfc9f2496ece0c0cee3b48f9a3217460921e15f8920e53e1047d4
s3-1     | I0205 16:10:18.602958 auth_signature_v4.go:197 stringToSign AWS4-HMAC-SHA256
s3-1     | 20250205T161018Z
s3-1     | 20250205/us-east-1/s3/aws4_request
s3-1     | 34b35e31847a44a125b03daafe3a0b3f61e33ccde0759771d9ff2e5be1aecf6a
s3-1     | I0205 16:10:18.602973 auth_signature_v4.go:208 newSignature d8a1bb7fec58e9e1018c9278b5a70af8ac164b1009206764ec88fa611fb79f41
s3-1     | I0205 16:10:18.602977 auth_signature_v4.go:209 signV4Values.Signature db63e18f1bffb8a256d3a6256ab862bf238fac7e8bd8b885c6a9ba4cdb642e18
s3-1     | I0205 16:10:18.602982 auth_credentials.go:327 auth error: 48
s3-1     | I0205 16:10:18.603013 error_handler.go:96 status 403 application/xml: <?xml version="1.0" encoding="UTF-8"?>
s3-1     | <Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Resource>/93d66fe4-4043-4c04-81be-8692bf13eea5/bfdfca91-2e61-4c23-87fa-15e987c9002e/93d66fe4-4043-4c04-81be-8692bf13eea5/input/iris.csv</Resource><RequestId>1738771818602986934</RequestId><Key>bfdfca91-2e61-4c23-87fa-15e987c9002e/93d66fe4-4043-4c04-81be-8692bf13eea5/input/iris.csv</Key><BucketName>93d66fe4-4043-4c04-81be-8692bf13eea5</BucketName></Error>
```

## To reproduce

Could reproduce a prod setup with a very basic `nginx` conf:

In `docker-compose.yml`:
```
  nginx:
    image: nginx:1.27.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
```

My `nginx.conf`:

```
events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://s3:8333;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

```

Python code used:

```
    fsspec_fs = get_filesystem(
        dataset_input_url,
        aws_access_key_id="power_user_key",
        aws_secret_access_key="power_user_secret",
        storage_endpoint_url=storage_endpoint_url,
    )

    print(f"Uploading dataset to {dataset_input_url}")
    with open(filepath, "rb") as input_f:
        with fsspec_fs.open(dataset_input_url, "wb") as output_f:
            output_f.write(input_f.read())


def get_filesystem(
    filesystem_url: str,
    aws_access_key_id: str,
    aws_secret_access_key: str,
    storage_endpoint_url: str,
):

    s3_fs_kwargs = {
        "client_kwargs": {
            "aws_access_key_id": aws_access_key_id,
            "aws_secret_access_key": aws_secret_access_key,
            "endpoint_url": storage_endpoint_url,
            "region_name": 'us-east-1',
        }

    }
    fsspec_fs, _ = fsspec.url_to_fs(filesystem_url, **s3_fs_kwargs)
    return fsspec_fs
```

Here is the complete `docker-compose`:

```

  master:
    image: chrislusf/seaweedfs:local
    networks:
      - default
    ports:
      - 9333:9333
      - 19333:19333
    command: "-v=4 master -ip=master -volumeSizeLimitMB=10"
    healthcheck:
      test:
        ["CMD", "curl", "--fail", "-I", "http://localhost:9333/cluster/healthz"]
      interval: 1s
      timeout: 60s
    volumes:
      - ./tls:/etc/seaweedfs/tls
  volume:
    image: chrislusf/seaweedfs:local
    networks:
      - default
    ports:
      - 8080:8080
      - 18080:18080
    command: "-v=4 volume -mserver=master:9333 -port=8080 -ip=volume -preStopSeconds=1 -max=10000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "-I", "http://volume:8080/status"]
      interval: 1s
      timeout: 30s
    depends_on:
      master:
        condition: service_healthy
    volumes:
      - ./tls:/etc/seaweedfs/tls
  filer:
    image: chrislusf/seaweedfs:local
    networks:
      - default
    ports:
      - 8888:8888
      - 18888:18888
    command: '-v=4 filer -ip.bind=0.0.0.0 -master="master:9333"'
    healthcheck:
      test: ["CMD", "curl", "--fail", "-I", "http://localhost:8888"]
      interval: 1s
      timeout: 30s
    depends_on:
      master:
        condition: service_healthy
      volume:
        condition: service_healthy

    volumes:
      - ./tls:/etc/seaweedfs/tls

  iam:
    image: chrislusf/seaweedfs:local
    networks:
      - default

    ports:
      - 8111:8111
    command: '-v=4 iam -filer="filer:8888" -master="master:9333"'
    depends_on:
      master:
        condition: service_healthy
      volume:
        condition: service_healthy
      filer:
        condition: service_healthy

    volumes:
      - ./tls:/etc/seaweedfs/tls

  s3:
    image: chrislusf/seaweedfs:local
    networks:
      - default

    ports:
      - 8333:8333
    command: '-v=4 s3 -filer="filer:8888" -ip.bind=s3'
    healthcheck:
      test: ["CMD", "curl", "--fail", "--get", "http://localhost:8333/healthz"]
      interval: 1s
      timeout: 30s
    depends_on:
      master:
        condition: service_healthy
      volume:
        condition: service_healthy
      filer:
        condition: service_healthy
    volumes:
      - ./tls:/etc/seaweedfs/tls

```
