### ISSUE TITLE
SignatureDoesNotMatch with NodeJS and S3

### ISSUE THREAD

**Issue by martinikolaev** [seaweedfs/seaweedfs#6598]
Hello, I am building an backend for a small application i am working on. I need some file storage for images, videos etc.

I am evaluating SeaweedFS, but seems to have some issues with S3 and presigned URLs.

Currently I am hosting SeaweedFS on a Raspberry Pi via docker container.

```

services:
  master:
    image: chrislusf/seaweedfs
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    command: "master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324"
    volumes:
      - /docker/data/application-dev-seaweed/master:/data
    networks:
      - application-db
  volume:
    image: chrislusf/seaweedfs
    ports:
      - 8080:8080
      - 18080:18080
      - 9325:9325
    command: 'volume -mserver="master:9333" -ip.bind=0.0.0.0 -port=8080  -metricsPort=9325'
    volumes:
      - /docker/data/application-dev-seaweed/volume:/data
    networks:
      - application-db
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs
    ports:
      - 8888:8888
      - 8333:8333
      - 18888:18888
      - 9326:9326
    command: 'filer -master="master:9333" -s3 -s3.config=/etc/seaweedfs/s3.json -ip.bind=0.0.0.0'
    volumes:
      - ./s3.json:/etc/seaweedfs/s3.json
      - /docker/data/application-dev-seaweed/filer:/data/filer
    networks:
      - application-db
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume


networks:
  application-db:
    external: true

```

s3.json

```

{
    "identities": [
      {
        "name": "me",
        "credentials": [
          {
            "accessKey": "any",
            "secretKey": "any"
          }
        ],
        "actions": [
          "Read",
          "Write",
          "List",
          "Tagging",
          "Admin"
        ]
      }
    ]
  }

```

TypeScript:

```
// Configure S3 client for SeaweedFS
const s3Client = new S3Client({
  
  region: "us-east-1", // SeaweedFS doesn't use regions but AWS SDK requires it
  endpoint: "http://10.2.20.17:8333",
  //endpoint: `http${process.env.SEAWEED_USE_SSL === 'true' ? 's' : ''}://${process.env.SEAWEED_ENDPOINT}:${process.env.SEAWEED_PORT}`,
  credentials: {
    accessKeyId: "any",
    secretAccessKey: "any",
  },
  forcePathStyle: true, // Required for SeaweedFS S3 compatibility
});

```

UploadImages:

```

export async function uploadImage(request, reply, pictureType: string) {
  try {
    // Authentication check remains the same
    const user = request.user;
    if (!user) {
      reply.code(401).send({ error: 'Unauthorized' });
      return;
    }

    // Picture type validation remains the same
    if (!(pictureType.toUpperCase() as keyof typeof PictureType in PictureType)) {
      return reply.code(400).send({ error: `Invalid pictureType: ${pictureType}` });
    }

    // File handling remains the same
    let mimetype: string;
    let fileData: any;
    const contentType = request.headers['content-type'];

    if (contentType && contentType.startsWith('image/jpeg')) {
      mimetype = contentType;
      fileData = request.body;
    } else if (contentType && contentType.startsWith('multipart/form-data')) {
      const data = await request.file();
      if (!data) {
        reply.code(400).send({ error: 'No file provided' });
        return;
      }
      ({ mimetype, file: fileData } = data);
    } else {
      reply.code(415).send({ error: 'Unsupported Content-Type' });
      return;
    }

    const timestamp = new Date().toISOString();
    const randomSuffix = crypto.randomBytes(4).toString('hex');
    const fileKey = `${user.id}/profile/${timestamp}_${randomSuffix}_original.jpg`;

    console.log("fileKey: ", fileKey);

    // Upload to SeaweedFS S3
    await s3Client.send(new PutObjectCommand({
      Bucket: process.env.SEAWEED_BUCKET_PROFILE,
      Key: fileKey,
      Body: fileData,
      ContentType: mimetype,
    }));

    // Database storage remains the same
    const imageRecord = await prisma.userImage.create({
      data: {
        fileKey,
        contentType: mimetype,
        pictureType: pictureType.toUpperCase() as PictureType,
        userId: user.id,
      },
      select: {
        id: true,
        fileKey: true,
        contentType: true,
        pictureType: true,
        userId: true,
        createdAt: true,
        updatedAt: true,
      },
    });

    reply.code(200).send({ success: true, image: imageRecord });
  } catch (err) {
    console.error('Upload error:', err);
    reply.code(500).send({ error: 'Upload failed', details: err.message });
  }
}



```

GetImages:

```

export async function getImages(
  request: FastifyRequest, 
  reply: FastifyReply, 
  pictureType: string
) {
  try {
    // Authentication and validation remains the same
    const user = request.user;
    if (!user) {
      return reply.code(401).send({ error: 'Unauthorized' });
    }

    if (!(pictureType.toUpperCase() as keyof typeof PictureType in PictureType)) {
      return reply.code(400).send({ error: `Invalid pictureType: ${pictureType}` });
    }

    // Database query remains the same
    const images = await prisma.userImage.findMany({
      where: {
        userId: user.id,
        pictureType: pictureType.toUpperCase() as PictureType,
      },
      orderBy: { createdAt: 'desc' },
      take: 5,
    });

    if (!images || images.length === 0) {
      return reply.code(404).send({ error: `No images found for type: ${pictureType}` });
    }

    // Generate presigned URLs using S3 method
    const imagesWithUrls = await Promise.all(
      images.map(async (image) => {
        const url = await getSignedUrl(s3Client, new GetObjectCommand({
          Bucket: process.env.SEAWEED_BUCKET_PROFILE,
          Key: image.fileKey,

        }), { expiresIn: 10600, unsignableHeaders: new Set(['content-disposition' ]) }); // 10 minutes

        return {
          ...image,
          url,
        };
      })
    );

    return reply.code(200).send({ images: imagesWithUrls });
  } catch (err) {
    console.error('Error retrieving images:', err);
    return reply
      .code(500)
      .send({ error: 'Failed to retrieve images', details: err.message });
  }
}
```

So my requests to upload a file are successful:
Headers:
Content-Type: image/jpeg

```

{
	"success": true,
	"image": {
		"id": "dcb9c4f1-aaec-401b-8e89-c58d5430bc33",
		"fileKey": "343b8dfe-121b-4056-a926-99faececd347/profile/2025-03-04T00:05:03.740Z_259dd025_original.jpg",
		"contentType": "image/jpeg",
		"pictureType": "PROFILE",
		"userId": "343b8dfe-121b-4056-a926-99faececd347",
		"createdAt": "2025-03-04T00:05:03.766Z",
		"updatedAt": "2025-03-04T00:05:03.766Z"
	}
}
```

To get presigned url as well:
```

{
	"images": [
		{
			"id": "dcb9c4f1-aaec-401b-8e89-c58d5430bc33",
			"fileKey": "343b8dfe-121b-4056-a926-99faececd347/profile/2025-03-04T00:05:03.740Z_259dd025_original.jpg",
			"contentType": "image/jpeg",
			"pictureType": "PROFILE",
			"userId": "343b8dfe-121b-4056-a926-99faececd347",
			"createdAt": "2025-03-04T00:05:03.766Z",
			"updatedAt": "2025-03-04T00:05:03.766Z",
			"url": "http://10.2.20.17:8333/profile-images/343b8dfe-121b-4056-a926-99faececd347/profile/2025-03-04T00%3A05%3A03.740Z_259dd025_original.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=any%2F20250304%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250304T000858Z&X-Amz-Expires=10600&X-Amz-Signature=43c66db1f19504480a61fbf86e33fbe57ce20326a6970fc8039fecc95ccdda2e&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject"
		}
	]
}




```

But when I try to open the link:

```
> GET /profile-images/343b8dfe-121b-4056-a926-99faececd347/profile/2025-03-04T00%3A05%3A03.740Z_259dd025_original.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=any%2F20250304%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250304T002813Z&X-Amz-Expires=10600&X-Amz-Signature=72fc93a3c36da2fb160c9dca9b683dd0832d356bb6082b4f8202a1d2ddee0ccb&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject HTTP/1.1
> Host: 10.2.20.17:8333
> User-Agent: insomnia/10.3.1
> Content-Type: image/jpeg
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM0M2I4ZGZlLTEyMWItNDA1Ni1hOTI2LTk5ZmFlY2VjZDM0NyIsImVtYWlsIjoiZGVtb0BvcGVuZml0Lnh5eiIsImlhdCI6MTc0MTA0ODA5MywiZXhwIjoxNzQxMDUxNjkzfQ.luhsFps-o_hMYvlbC0kGFtAqVMYAPaymhdWMgc3jfuBN4L0LNhu5SQcCOly1giIZRF72pNoR6qLpNxsfmeLhprJzTrDjAMpka2tkNG87bbjaBkqQK9AC6OqMbVKwL3hkTbP8_Ik6OKXRJzxDVx0jw86W3bk0TUlYkA6QbA9IojDpwCAPi1A5D524TCQ9_0KHjdotUUN7Fviv-ycRrg63rHqiskqEq6W6CmjKgSTZT2uvuRTAI0yjR2l5Jby_6waYpcM0JWv20hFte_SvnqDWPzBV2ykqPCa33O3zpOvWu4TzgbOuMoGLUa8pjM8T-Ery67qbHN-RtEGjLBTf8uq6fw
> Accept: */*

<?xml version="1.0" encoding="UTF-8"?>
<Error>
	<Code>SignatureDoesNotMatch</Code>
	<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
	<Resource>/profile-images/343b8dfe-121b-4056-a926-99faececd347/profile/2025-03-04T00:05:03.740Z_259dd025_original.jpg</Resource>
	<RequestId>1741048093942232890</RequestId>
	<Key>343b8dfe-121b-4056-a926-99faececd347/profile/2025-03-04T00:05:03.740Z_259dd025_original.jpg</Key>
	<BucketName>profile-images</BucketName>
</Error>
```

I am banging my head for days that I cannot understand where the issue is coming from. I really wanna make SFS work and use it in my project, but cannot overcome this issue.
Object Storage is new to me.
Tried passing different headers, changing credentials, but nothing worked.

```
    "@aws-crypto/sha256-js": "^5.2.0",
    "@aws-sdk/client-s3": "^3.758.0",
    "@aws-sdk/s3-request-presigner": "^3.758.0",
    "@aws-sdk/signature-v4": "^3.370.0",

weed version
version 30GB 3.85 7d7e06681 linux arm64
```

Can someone give me some pointers please!
