### ISSUE TITLE
MongoDB container with data on SeaweedFS mount hangs

### ISSUE THREAD

**Issue by gutleib** [seaweedfs/seaweedfs#6636]
### Describe the bug
I'm getting 
no particular errors, but MongoDB never deploys, and if I transfer database to SeaweedFS mount, it never listens to connections.

### System Setup
SeaweedFS 3.85 cluster is deployed on 3 VMs, each has Master+Volume+Filer daemons. Filer runs in S3 mode, and uses MariaDB+Galera cluster with daemons run on same 3 VMs. So, it's 3 identicaly configured VMs. Volumes are placed on BTRFS-formatted bcache devices, mounted with noatime and zstd:2 options.
MongoDB (official DockerHub image mongo:8) is deployed in Nomad (v1.9.3) cluster, which has SeaweedFS CSI controllers (chrislusf/seaweedfs-csi-driver:v1.2.7) installed and volumes placed directly on SeaweedFS.  
Other services use the same setup OK, not very fast IOPS, but OK. MongoDB refuses to work entirely. I'm moving from Kadalu CSI + GlusterFS setup, which proved unstable with our network. Seaweed works stable, with the exception of MongoDB mount. 
And one more strange detail: if I use upper folder for mount (e.g. /data instead of /data/db) inside container, data does not go to SeaweedFS. I see "db" folder in SeaweedFS via fs.ls in weed shell, but it's empty. And MongoDB works ephemerally then.

### Expected behavior
MongoDB container should run without any error.

Is this a SeaweedFS related problem? Can it be related to  #1398 ?

**Comment by chrislusf** [comment]
anyway to reproduce the workload? With some scripts, assuming a "weed mount" is running.
Or use docker compose?

**Comment by oleksandrvaluiev** [comment]
Yep, have the same issue with MongoDB in K8s
Readiness check/port never responses, pod cannot start properly

**Comment by oleksandrvaluiev** [comment]
@chrislusf 
you can check with this manifest

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: seaweedfs-database-init-configmap
  namespace: default
  labels:
    chart: release-name
    release: 1.0.0
data:
  mongo-init.js: |-
    // Creates user with read-write rights only for one DB
    // Root user can be used to handle any table in MongoDB
    db.createUser(
      {
        user: "user",
        pwd: "password",
        roles: [
          {
            role: "dbOwner",
            db: "test"
          }
        ]
      }
    );
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-database
  namespace: default
  labels:
    chart: release-name
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: seaweedfs-storage
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-database
  namespace: default
  labels:
    chart: release-name
    release: 1.0.0
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
  clusterIP: None
  type: ClusterIP
  selector:
    app: seaweedfs-database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seaweedfs-database
  namespace: default
  labels:
    chart: release-name
spec:
  replicas: 1
  serviceName: seaweedfs-database
  selector:
    matchLabels:
      app: seaweedfs-database
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      labels:
        app: seaweedfs-database
        chart: release-name
    spec:
      containers:
        - name: seaweedfs-database
          image: mongo:4
          imagePullPolicy: Always
          env:
            - name: MONGO_INITDB_DATABASE
              value: test
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - name: initial-data-volume
              mountPath: /docker-entrypoint-initdb.d/mongo-init.js
              subPath: mongo-init.js
            - name: data
              mountPath: /data/db
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          resources:
              requests:
                memory: 200Mi
                cpu: 100m
      volumes:
        - name: initial-data-volume
          configMap:
            name: seaweedfs-database-init-configmap
        - name: data
          persistentVolumeClaim:
            claimName: seaweedfs-database

```
getting events with
Message:             Readiness probe failed: dial tcp 172.16.19.2:27017: connect: connection refused

**Comment by oleksandrvaluiev** [comment]
@gutleib could you please confirm you had similar behavior

**Comment by chrislusf** [comment]
It would be good to see some logs.

I am testing this way: 
* use "weed mount" to mount a folder, and run `docker run -d -p 27017:27017 -v ~/tmp/mounted_directory:/data/db --name my-mongo mongo` 

It runs fine initially at least.

**Comment by gutleib** [comment]
@oleksandrvaluiev, I have got a confirmation that we use mongo as a queue, and made it ephemeral. Cannot reproduce on a short notice, sorry. 
My guess is that it needs some very specific lock to confirm ownership of files. It seems to start, but never quite starts to reply queries. There were no data in container logs.

Right now we're struggling with data corruption in Zeppelin notebooks, but it happens once a few weeks.

I will come back when make a lab with mongo.

**Comment by oleksandrvaluiev** [comment]
@chrislusf  we use a bit different setup in our testlab:

- 4 virtual machines with installed master/volume/filer servers running there as a SystemD services.
- the same 4 virtual machines are used as a kubernetes workers.
- seaweedfs-csi-driver is installed using helm chart.

SeaweedFS binary - linux_amd64_large_disk.tar.gz 8000GB 3.87 `e4e85052082e31c94cd133270afc9e8365641c8c` version.

weed master is installed as SystemD service only on THREE of these virtual machines (for quorum).
Virtual machines IPs:

10.2.130.23 - volume, filer
10.2.130.24 - master, volume, filer
10.2.130.25 - master, volume, filer
10.2.130.26 - master, volume, filer

Here are configurations for master, volume and filer SystemD services (example from the 10.2.130.24 node):


SeaweedFS Master Server
```
[Unit]
Description=SeaweedFS Master Server
After=network.target

[Service]
LimitNOFILE=65536
ExecStart=/usr/local/bin/weed \
  -logdir=/seaweedfs/master/logs master \
  -mdir=/seaweedfs/master/data \
  -peers=10.2.130.25:9333,10.2.130.26:9333 \
  -ip=10.2.130.24 \
  -port=9333 \
  -defaultReplication=001 \
  -metricsPort=1235

Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
```
SeaweedFS Volume Server
```
[Unit]
Description=SeaweedFS Volume Server
After=network.target

[Service]
LimitNOFILE=65536
ExecStart=/usr/local/bin/weed \
  -logdir=/seaweedfs/volume/logs volume \
  -dir=/seaweedfs/volume/data \
  -mserver=10.2.130.24:9333,10.2.130.25:9333,10.2.130.26:9333 \
  -port=8090 \
  -ip=10.2.130.24 \
  -max=256 \
  -metricsPort=1236

Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
```
SeaweedFS Filer Server
```
[Unit]
Description=SeaweedFS Filer Server
After=network.target

[Service]
LimitNOFILE=65536
ExecStart=/usr/local/bin/weed \
  -logdir=/seaweedfs/filer/logs filer \
  -master=10.2.130.24:9333,10.2.130.25:9333,10.2.130.26:9333 \
  -ip=10.2.130.24 \
  -port=8888 \
  -defaultStoreDir=/seaweedfs/filer/data \
  -metricsPort=1237

Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target
```


SeaweedFS CSI Driver installed as Kubernetes DaemonSet/Deployment using Helm Chart (via FluxCD)
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: seaweedfs-csi-driver
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: seaweedfs-csi-driver
  namespace: flux-system
spec:
  url: https://seaweedfs.github.io/seaweedfs-csi-driver/helm
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs-csi-driver
  namespace: seaweedfs-csi-driver
spec:
  interval: 5m
  chart:
    spec:
      chart: seaweedfs-csi-driver
      version: "0.2.2" # latest version as of May 2025
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-csi-driver
        namespace: flux-system
  install:
    createNamespace: true
  values:
    seaweedfsFiler: "10.2.130.23:8888,10.2.130.24:8888,10.2.130.25:8888,10.2.130.26:8888"
    csiDriver:
      enabled: true

```

Or the same result using helm install command:
```
helm repo add seaweedfs-csi-driver https://seaweedfs.github.io/seaweedfs-csi-driver/helm
helm repo update
helm upgrade --install seaweedfs-csi-driver seaweedfs-csi-driver/seaweedfs-csi-driver \
--namespace seaweedfs-csi-driver \
--create-namespace \
--set seaweedfsFiler="10.2.130.23:8888\,10.2.130.24:8888\,10.2.130.25:8888\,10.2.130.26:8888" \
--set csiDriver.enabled=true
```

We are using basic approach for PV/PVC creation, without any additional/specific parameters, as you may see above in MongoDB manifest.
