### ISSUE TITLE
Metadata backups not removing old files and filling entire storage

### ISSUE THREAD

**Issue by facorazza** [seaweedfs/seaweedfs#6723]
Hi,

I'm currently running incremental backups of the metadata using the following command:

```shell
weed filer.backup -disableErrorRetry -doDeleteFiles -retentionDays 20 -filer 'seaweedfs-filer:8888'
```
The replication.toml looks like this:

```toml
    [sink.local]
    enabled = true
    directory = "/backups"
    # all replicated files are under modified time as yyyy-mm-dd directories
    # so each date directory contains all new and updated files.
    is_incremental = true
```

Unfortunately, the storage used by the metadata backups exceeds the one used by the actual data by orders of magnitude (/data vs /backups). 

```shell
df -h

Filesystem             Size  Used Avail Use% Mounted on
devtmpfs               4.0M     0  4.0M   0% /dev
tmpfs                   12G     0   12G   0% /dev/shm
tmpfs                  4.7G  482M  4.2G  11% /run
/dev/mapper/vg00-root   25G  2.8G   23G  12% /
/dev/sdb1             1013M  392M  622M  39% /boot
/dev/mapper/vg02-bck   500G  500G   20K 100% /backups
/dev/mapper/vg01-data  500G   41G  459G   9% /data
/dev/mapper/vg00-home   10G  2.7G  7.4G  27% /home
/dev/mapper/vg00-var    50G   42G  8.1G  84% /var
```

How can I keep the metadata to a reasonable size? Is there anything I can remove manually to restore a bit of space without compromising my ability to recover the backups?
