### ISSUE TITLE
Using filer with ScyllaDB - kv insert: Cannot execute this query as it might involve data filterin

### ISSUE THREAD

**Issue by bengivre** [seaweedfs/seaweedfs#6888]
I'm trying to put together a SeaweedFS cluster with filers and ScyllaDB (using Casandra)  

I'm able to run the ScyllaDB , create the namespace and the table filemeta .  
But I get the following error when the filers bootstrap : 

`
F0617 06:29:16.049512 filer.go:153 set filer.store.id=560294649 : kv insert: Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING
`

I'm in a docker swarm environment 
Bellow is my filter.toml 

```
[leveldb2]
enabled = false

[cassandra]
enabled = true

# ScyllaDB connection settings
hosts = ["scylla-node01:9042","scylla-node02:9042","scylla-node03:9042","scylla-node04:9042"]
keyspace = "seaweedfs"

# Connection pool settings optimized 
connection_timeout_millisecond = 10000
operation_timeout_millisecond = 20000
connections_per_host = 16

# Consistency settings
write_consistency = "LOCAL_QUORUM"
read_consistency = "LOCAL_ONE"

# Performance settings 
concurrent_writes = 256
concurrent_reads = 128

# Datacenter awareness
local_dc = "BHS8"

# Connection settings
protocol_version = 4
socket_connect_timeout_millisecond = 10000


[filer.options]
# Filer-specific options
saveToFilerLimit = 10485760 
defaultReplication = "010"   
disableDirListing = false
maxMB = 4                    
dirListingLimit = 100000  
```

And  the docker compose (stack) to deploy to swarm : 

```
# Filer - Provides S3 API and file access with ScyllaDB backend
  seaweedfs-filer:
    image: chrislusf/seaweedfs:3.90
    command: >
      filer
      -master=seaweedfs-master:9333
      -port=8888
      -ip.bind=0.0.0.0
      -ip=seaweedfs-filer 
      -metricsPort=9326
    networks:
      - seaweed
      - cloud-public  
    volumes:
      - /data/seaweedFS/filer/filer.toml:/etc/seaweedfs/filer.toml:ro
    deploy:
      replicas: 2  # For HA with Traefik load balancing
      placement:
        preferences:
          - spread: node.labels.rack  # Distribute across racks
```
