### ISSUE TITLE
Empty folder is not removed automatically

### ISSUE THREAD

**Issue by tanchihpin0517** [seaweedfs/seaweedfs#6927]
Hi, 

I followed the instruction in [wiki](https://github.com/seaweedfs/seaweedfs/wiki/Amazon-S3-API#empty-folders) to have s3 server delete empty folder with no file, but it didn't work.

I tried to setup docker container with these three different commands:
```
server -s3 -filer -ip.bind=0.0.0.0 -master.defaultReplication 000 -master.volumeSizeLimitMB 100000 -s3.config /weed_config/s3.json  # no flag set
```
```
server -s3 -filer -ip.bind=0.0.0.0 -master.defaultReplication 000 -master.volumeSizeLimitMB 100000 -s3.config /weed_config/s3.json -s3.allowEmptyFolder  # toggle
```
```
server -s3 -filer -ip.bind=0.0.0.0 -master.defaultReplication 000 -master.volumeSizeLimitMB 100000 -s3.config /weed_config/s3.json -s3.allowEmptyFolder false  # set with value
```

I ran s3 server as the backend of JuiceFS (with s3 protocal). After I deleted a file in juicefs, I checked filer and made sure chucks had been removed. However, the empty folder was not automatically removed.

**Comment by chrislusf** [comment]
Need steps to reproduce it and confirm the fix.

**Comment by tanchihpin0517** [comment]
The testing environment is Ubuntu24.04

Here are steps to reproduce:

1. Use docker-compose to create a testing seaweedfs server
```
version: '3.8'
services:
  server:
    image: chrislusf/seaweedfs:3.92_large_disk_rocksdb
    container_name: seaweedfs-server
    ports:
      - 9333:9333
      - 19333:19333
      - 8080:8080
      - 18080:18080
      - 8888:8888
      - 18888:18888
      - 8333:8333
    command: "server -s3 -filer -ip.bind=0.0.0.0 -master.defaultReplication 000 -master.volumeSizeLimitMB 1000"
```
Note that the unused options are removed, and `s3.allowEmptyFolder` is not provided in this template which indicates the first command (with no flag)

2. Download a [juicefs](https://juicefs.com/docs/community/getting-started/installation) binary. In this testing, I use `apt` to install it.

3. Run `juicefs format sqlite3://test.db test --storage s3 --bucket http://127.0.0.1:8333/juicefs --trash-days 0` to create a juicefs file system and use seaweedfs s3 as the object storage. The direcotory `/buckets/juicefs/test/` will appear in filer web page.

4. Run `juicefs mount sqlite3://test.db ./mount` to mount the testing file system to the path `./mount`.

5. Copy anything to `./mount`. Juicefs will upload data chunks into `/buckets/juicefs/test/chunks/0/0`.

6. Remove copied file.

7. Chunks in `/buckets/juicefs/test/chunks/0/0` are deleted but the empty directory isn't.

**Comment by chrislusf** [comment]
default value for "allowEmptyFolder" is true.

**Comment by tanchihpin0517** [comment]
How to set this option correctly?

I've tried `-s3.allowEmptyFolder false` but it didn't work.

New compose file would look like:
```
version: '3.8'
services:
  server:
    image: chrislusf/seaweedfs:3.92_large_disk_rocksdb
    container_name: seaweedfs-server
    ports:
      - 9333:9333
      - 19333:19333
      - 8080:8080
      - 18080:18080
      - 8888:8888
      - 18888:18888
      - 8333:8333
    command: "server -s3 -filer -ip.bind=0.0.0.0 -master.defaultReplication 000 -master.volumeSizeLimitMB 1000 -s3.allowEmptyFolder false"
```
